volttron/platform/packages.py

Fixes issue #20 . Simple fix to `volttron/platform/packages.py`.  Wrapped `tmp_dir` code section in `VolttronPackageWheelFileNoSign.add_files()` with `try...finally` as was done in `remove_files()`.
Due to the larger indentation change, file difference best viewed with `git diff -b` to ignore whitespace.

Fix tmp_dir cleanup during pkg configure

---

volttron/platform/agent/utils.py

Resolves issue #24 
Updated volttron.platform.agent.utils.set_logging() to check for
existing root logging handler before instantiating new handler.

Prevent setup_logging multiple handlers

---

volttron/platform/control.py
volttrontesting/testutils/test_platformwrapper.py
volttrontesting/utils/platformwrapper.py

The problem occurred because volttron-ctl was not making an rpc call to remove
agent but was calling the AIPPlatform instance directly.  The inline call removed the
installed agent files but did not remove the agent from volttron's list of agents.
This commit includes a new test in test_platformwrapper: test_can_remove_agent,  along
with a corresponding change in PlatformWrapper.remove_agent which now makes a remote
call rather than calling the aip inline.  Its possible this was a workaround for
some other problem but I don't see any new tests failing because of the change.  Let me know if I've missed something.
I do see an indeterminate number of 'auth' tests failing (6-9) before and after
this change which I assume is related to my environment.  All other tests are passing.
---
This …

Resolves #71, 'volttron-ctl remove' fails to remove agent.

---

pytest.ini
services/core/VolttronCentral/tests/test_webapi.py
volttron/platform/agent/base_historian.py
volttrontesting/utils/platformwrapper.py

This reverts back to when there was a single thread for processing and the other thread was a querying thread.
It also merges back in the cache db size that was implemented.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/589)

Merge revert-historain into releases/3.5rc1

---

volttrontesting/testutils/test_platformwrapper.py

The api changed to returning the param (encrypted or unencrypted) and then the wrapper instance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/626)

Attempt to fix issue with get_volttron_instances api change

---

services/core/MongodbHistorian/mongodb/historian.py

This shouldn't have happened.  This is probably an issue upstream in pymongo, but this does fix the issue and shouldn't break any other sources with it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/644)

Fixed: #643 Fixed issue with querying mongo on Fedora 23

---

docs/source/devguides/deployment/Linux-Platform-Hardening-Recommendations-for-VOLTTRON-users.rst

This documentation uses pipes in a fair amount of places and it messes
with the way rst collapses the content
If there is a reason for the pipes just reject this request and let me know, I had started to normalize the pipes so they were every line and it shouldn't be too hard to get back to that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/742)

Fix the deployment documentation for Linux

---

services/core/ActuatorAgent/tests/test_actuator_pubsub.py
services/core/SQLHistorian/tests/test_sqlhistorian.py
services/core/VolttronCentral/tests/test_vc_vcp_local.py
volttrontesting/utils/platformwrapper.py

calling volttron-ctl command to install agent instead of rpc.call('control','install_agent',wheel_file,channel_name,vip_identity) in the hope to fix the "ZMQ too many open files" error on travis ci
removed pytest.mark.dev from test cases
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/763)

Possible fix for "ZMQ too many open files" error on travis ci

---

volttron/platform/control.py

As I was going through `volttron-control auth add` documentation I realized that it makes more sense for the default mechanism field to be `CURVE` rather than `NULL`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/843)

changed default mechanism from NULL to CURVE in volttron-ctl auth add

---

services/core/FailoverAgent/tests/test_failover.py
services/core/FailoverAgent/tests/test_simple_failover.py
services/core/ForwardHistorian/tests/test_forward_historian.py
services/core/ForwardHistorian/tests/test_forwardhistorian.py
services/core/VolttronCentralPlatform/tests/test_platformagent.py
volttron/platform/aip.py
volttron/platform/control.py
volttron/platform/keystore.py
volttron/platform/main.py
volttron/platform/vip/agent/core.py
volttrontesting/platform/auth_test.py
volttrontesting/platform/connection_test.py
volttrontesting/platform/keystore_test.py
volttrontesting/utils/build_agent.py
volttrontesting/utils/platformwrapper.py

* `volttron-ctl upgrade` removes and installs agent while preserving the agent's existing authorization entry in `$VOLTTRON_HOME/auth.json`
* Changed `KeyStore` methods `public` and `secret` to properties (this helped with preserving authorization entry and it is more pythonic)
* Removed unused imports of `KeyStore`, `AuthEntry`, and `AuthFile`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/849)

Added 'volttron-ctl upgrade' command

---

volttron/platform/vip/agent/core.py

The effect of this typo was limited to the case when `Agent` is initialized with a non-`None` `serverkey` and `developer_mode=True`. Even then, the keys would not be used in VIP, but calling `agent.core.serverkey` would return a `serverkey` that wasn't actually used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/865)

fixed typo bug in Core._set_keys

---

volttron/platform/vip/agent/core.py
volttron/platform/vip/agent/subsystems/pubsub.py

This is a pretty common pattern:
```
greenlet = gevent.spawn_later(seconds, func, *args, **kwargs)
self.greenlet.link(lambda glt: greenlet.kill())
```
we could probably remove it in more places but this one is the most noticeable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/869)

remove spawn later link #765

---

docs/source/core_services/security/Known-Hosts-File.rst
volttron/platform/control.py

Fixes: #945 serverkey not server-key is used everywhere else.  Made this consistent
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/946)

Consistent serverkey

---

volttron/platform/web.py

The removed code was not being run anyways, because the AuthFile will always have at least one entry (the platform itself).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1007)

do not add allow-all entry in MasterWebService, fixes #673

---

volttron/platform/aip.py
volttron/platform/control.py

fixes #1070
Now `volttron-ctl install` and `volttron-ctl upgrade` will always try to add the agent's authorization entry. If it already exists, then it will continue on silently. I couldn't think of a good reason to warn the user if the entry already exists.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1072)

volttron-ctl upgrade adds agent authorization if it does not exist

---

docs/source/core_services/security/Key-Stores.rst
volttron/platform/control.py
volttron/platform/keystore.py

`volttron-ctl auth keypair` used to write to `$VOLTTRON_HOME/keystore` (the platform's key pair) by default, and the user could specify an optional path to write to a different file. The platform automatically generates a key pair on startup if it does not already exist, so this default behavior of the `keypair` command was not very useful.
Now running `volttron-ctl auth keypair` generates a new key pair and writes it to `stdout`:
```
(volttron)$ volttron-ctl auth keypair
{
"secret": "HMbnbEQnWYMZNbNCwplORUajhXa-tzx7hGGGlJRJmQk", 
"public": "VchRI7e8zKQOaypl4VTzEwjet0hENi0tXl3L0AFMORo"
}
```
Side note: because it is in JSON format, the user can redirect the command's output to a file to replace a keystore (which is *currently* a JSON file):
```(volttron)$ volttron-ctl auth keypair > …
```

volttron-ctl auth keypair now prints keys to stdout rather than a file

---

docs/source/core_services/drivers/Driver-Configuration.rst

campus is a required field for device hierarchy, non-standard example was confusing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1100)

added campus to example command

---

docs/source/core_services/drivers/BACnet-Proxy-Agent.rst
services/core/MasterDriverAgent/master_driver/interfaces/bacnet.py
services/core/MasterDriverAgent/master_driver/test_bacnet1.config
services/core/MasterDriverAgent/master_driver/test_bacnet2.config

The timeout for how long master driver would wait for the BACnet proxy to scrape requested points was hardcoded to 10 seconds, on large scrapes with slower devices, this timeout could be reached. The timeout is now exposed for each device config. This resolves  #1136 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1134)

Added timeout to device config for BACnet Proxy Agent

---

volttron/platform/vip/socket.py

#1210  ipv6 failed due to the missing import.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1211)

#1210 Fixed missing import for re

---

start-volttron
stop-volttron

Added a script that will allow simple startup of a deployed volttron in the background.  The shell need not be activated in order to run the script.  The environment does need to be bootstrapped however.  It uses the rotatinglog.py script as it's mechanism for logging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1236)

Added start-volttron script

---

scripts/bacnet/bacnet_scan.py
scripts/bacnet/grab_bacnet_config.py
scripts/scalability-testing/virtual-drivers/bacnet.py

The new version of BACpypes has changes to module names which break the import statements in the BACnet helper scripts.  Updating the import statements per http://bacpypes.readthedocs.io/en/stable/migration/migration001.html#localdeviceobject allowed me to successfully run bacnet_scan.py and grab_bacnet_config.py.  I also updated one other place where the same import statements appear, though I have not tested anything there. There is a fourth instance, which was not updated, but it is in a directory marked deprecated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1352)

Bacpypes imports fix

---

services/core/MasterDriverAgent/master_driver/driver.py

Fixes #1302 which was caused by the gevent.Timeout not inheriting exception, thereby not being caught and logged correctly, here we explicitly catch the gevent.Timeout as well as other exceptions and log them correctly, because there was a bunch of trailing whitespace, there are a lot of changes, however the only one that actually affects the code is on line 262
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1323)

improved master driver timeout log output

---

volttron/platform/web.py

This should address #1344, need a good way to test, if agreeable, this could be applied to the rpc exported functions in the web system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1391)

log message when attempting to register websocket without web

---

scripts/pycharm-launch.py

This pull request addresses #1022 (at least for pycharm) and #1297 for VOLTTRON_HOME.  The AGENT_CONFIG should default to config if config is present.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1426)

Fixes #1022 auto adding auth if agent id doesn't exist

---

README.md

Documentation link now points to /latest/ instead of /master/
Also used HTTPS instead of HTTP when possible
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1445)

Fixed all documentation links in README.md

---

services/core/MessageDebuggerAgent/messagedebugger/agent.py

When a message originates from MasterDriverAgent, its topic is in
frame 7 (the eighth frame) of the routed message. Fix the
Message Debugger's mapping for this value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1474)

Fix Message Debugger topic value for routed messages from devices

---

examples/JupyterNotebooks/README

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1475)

Correct a bad documentation URL in JupyterNoteboks/README

---

docs/source/devguides/roadmap/4.1-5.0_Migration.rst

ops instead of operations
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1522?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1522'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Fix a typo in migration doc

---

examples/rotatinglog.py

<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1538?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1538'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Fixed filename to be back to volttron.log

---

volttron/platform/vip/agent/core.py

Now the correct signal INT handler gets called when an agent is stopped. However, the platform needs to be cleanly shutdown as well and we need to have further discussion on that.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/VOLTTRON/volttron/pull/1627%23issuecomment-369988410%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/VOLTTRON/volttron/pull/1627%23issuecomment-369988410%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Related%20to%20%231615%22%2C%20%22created_at%22%3A%20%222018-03-02T17%3A17%3A39Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/3979063%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/craig8%22%7D …

Added default signal int handler to list of flags to override

---

services/core/VolttronCentral/package.json
setup.py

This pull request downgrades wheel to be stuck at 0.30 as the upgrade to 0.31 has broken installing agentss
#1652
Installed agent before change and it was messed up...after the patch and it works as expected.
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1653?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1653'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Downgrades wheel to 0.30

---

bootstrap.py

Fixes #1660 
Tested installing against clean branch.
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1661?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1661'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Fixes #1660 Installs 0.30 version of wheel before requirements.txt

---

volttron/platform/control.py

Added a simple "no agents installed message when running 'vctl list' without any agents, previously there was no output, which was a little confusing, as you couldn't tell if there was an exception or there just weren't any agents.
Fixes #1666 
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/VOLTTRON/volttron/pull/1667%23issuecomment-382546415%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/VOLTTRON/volttron/pull/1667%23issuecomment-382546415%22%2C%20%22comments%22%3A%20 …

added default message for vctl list when no agents are installed

---

bootstrap.py

On Ubuntu 18.04 the bootstrap fails because of the lack of https in downloading the initial package.
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/jhaack%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars0.githubusercontent.com/u/6992449%3Fv%3D4%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/VOLTTRON/volttron/pull/1679%23issuecomment-385827841%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222018-05-02T00%3A16%3A11Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars0.githubusercontent.com/u/6992449%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jhaack%22%7D%7D%5D%2C%20%22title%22%3A%20%22Genera …

require https for ubuntu 18.04

---

services/core/MarketServiceAgent/config

The MarketServiceAgent could not parse its config file via utils.load_config.
changed quotes to double-quotes and the value of the 'verbose_logging'  key to 0 instead of
False.
with the platform running, from a command shell,  i ran:
pydev-python MarketServiceAgent/market_service/agent.py
with AGENT_CONFIG set to 
MarketServiceAgent/config
before modifying config file, the agent call to
config = utils.load_config(config_path)  failed.
after modifying config file(per 'Fixes' above), the agent call to
config = utils.load_config(config_path)  succeeded.
<a …

make platform market service config file parsible by utils.load_config.

---

docs/source/conf.py

Fixed a call to sphinx when building readthedocs
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1698?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1698'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

fixed issue with readthedocs sphinx

---

services/core/SQLHistorian/sqlhistorian/historian.py
volttron/platform/dbutils/basedb.py
volttrontesting/services/historian/test_dbdriver.py
volttrontesting/services/historian/test_historian.py

If a database connection is closed, perhaps by the remote end or due to an unhandled exception, an exception will be raised when creating a cursor using the connection's cursor() method. Because there doesn't seem to be consensus between the different database drivers about the exact exception raised, any non-standard exception should be logged and ignored while forcing the connection to be recreated.
It is also important to ensure cursors are closed for autocommit features to work properly. A context manager will ensure proper closure.
Fixes #1732 
I tested the change against yet-to-be-published PostgreSQL and Redshift drivers as well as the sqlite3 version of the SQLHistorian using the included unit tests.
<a href='#crh-start'></a><a …

1132 unhandled closed connections

---

examples/ListenerAgent/config
scripts/install-agent.py
volttron/platform/agent/utils.py

This pull request updates the install-agent.py script to be more robust in error handling of parsing json as well as yaml configuration files.  It handles the \t parse error in yaml parser.
Fixes #1713, #1700 
Tested against config file with tab characters in json file.  Testing with invalid json file and with yaml file.
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1735?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1735'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
<a …

Updated yaml config file parsing

---

README.md
services/core/ActuatorAgent/tests/test_actuator_pubsub.py
services/core/MasterDriverAgent/tests/test_global_override.py
volttron/platform/aip.py
volttron/platform/control.py
volttron/platform/vip/agent/core.py
volttron/platform/vip/rmq_router.py
volttron/utils/rmq_mgmt.py
volttrontesting/fixtures/volttron_platform_fixtures.py
volttrontesting/multiplatform/test_multiplatform_pubsub.py
volttrontesting/platform/connection_test.py
volttrontesting/platform/control_test.py
volttrontesting/services/aggregate_historian/test_aggregate_historian.py
volttrontesting/testutils/test_single_instance.py
volttrontesting/utils/platformwrapper.py

The platform should now run properly with
1. ZMQ message bus
2. RMQ message bus without authentication
3. RMQ message bus with SSL based authentication
Some of the text fixtures were updated to run existing test scripts with both ZMQ and RMQ message bus. Here's the current status.
Module                | (pass/fail/error status)
actuator               | passed
actuator_pubsub | passed
agent                   | passed
auth                     | errors
control                 | passed
config_store         | passed
forwarder             | passed
gevent                  | passed
historian               | passed
keystore               | passed
mongodb             | skipped
pa                         | passed
driver                    | passed
subsystems           | passed
web …

Rabbitmq volttron auth

---

README.md
examples/ListenerAgent/listener/agent.py
requirements.txt
volttron/platform/certs.py
volttron/utils/rmq_setup.py

Initial implementation of non sudo user install of rabbitmq server. All logic is in rmq_setup.py for now so that  Nate can test with it.
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/shwethanidd%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/19616893%3Fv%3D4%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/VOLTTRON/volttron/pull/1760%23issuecomment-411156216%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222018-08-07T18%3A29%3A54Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/19616893%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/shwetha …

Rabbitmq volttron

---

volttron/utils/rmq_setup.py

When platform was started with command 
"volttron -vv -l l1.log&" 
Info and debug statements were getting redirected to stdout. Logging level was set to info in rmq_setup.py which was getting called from instance_setup.py which was causing the problem
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1775?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1775'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Issue #1771

---

services/core/ForwardHistorian/tests/test_forward_historian.py
services/core/VolttronCentral/tests/test_vc.py

Differences in floats through the message bus depending upon the underlying operating system/python versions are causing comparison issues
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1776?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1776'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Fix historian tests

---

services/core/ForwardHistorian/forwarder/agent.py
services/core/ForwardHistorian/tests/test_forwarder_reconnections.py
volttron/platform/agent/base_historian.py
volttrontesting/utils/utils.py

Changes the base historian so that it only reports the total published on specified period.
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1785?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1785'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

ForwardHistorian should publish all by default

---

services/core/VolttronCentral/volttroncentral/platforms.py
services/core/VolttronCentralPlatform/vcplatform/agent.py

Changes to both the VolttronCentralPlatform and VolttronCentral agent were necessary to resolve 
the issue observed on the VolttronCentral web UI (list.performance RPC returns an empty 'performance' list).
VolttronCentralPlatform changes:
- _publish_stats: publish platform 'status/cpu' metrics under the topic:
platforms/vcp-tcp___127_0_0_1_22916/status/cpu
instead of:
datalogger/platforms/vcp-Test_Platform_1/status
(it is my understanding that topics starting with datalogger/* are being used for communication from VolttronCentralAgent to the VolttronCentral web UI and topics starting with platform/* are being used for communication from VolttronCentralPlatform to VoltronCentral)
VolttronCentral changes:
- init: the topic to subscribe to (from VolttronCentralPlatform) was changed to match …

VolttronCentral: fix missing Performance metric list issue

---

docs/source/core_services/historians/Historian-Topic-Syntax.rst
examples/ExampleDrivenControlAgent/example/drivenagent.py
examples/ExampleSubscriber/subscriber/subscriber_agent.py
examples/NodeRed/node_red_publisher.py
examples/NodeRed/node_red_subscriber.py
examples/StandAloneListener/standalonelistener.py
services/contrib/WeatherAgent/weather/agent.py
services/core/ActuatorAgent/tests/test_actuator_pubsub.py
services/core/DataMover/tests/test_datamover.py
services/core/ForwardHistorian/tests/test_forward_historian.py
services/core/ForwardHistorian/tests/test_forwardhistorian.py
services/core/InfluxdbHistorian/tests/test_influxdb_historian.py
services/core/MasterDriverAgent/master_driver/driver.py
services/core/MasterDriverAgent/master_driver/interfaces/chargepoint/tests/TestAgent/tester/agent.py
services/core/MongodbHistorian/tests/test_mongohistorian.py
services/core/SQLHistorian/tests/test_sqlitehistorian.py
volttron/drivers/deprecated-remove-5.0/base.py
volttron/platform/agent/base_historian.py
volttron/platform/messaging/headers.py
volttrontesting/services/aggregate_historian/test_aggregate_historian.py
volttrontesting/services/historian/test_historian.py
volttrontesting/services/tagging/test_tagging.py
volttrontesting/utils/utils.py

Adds an optional synchronized timestamp to allow grouping device scrapes by timestamp. An example is a historian that creates wide tables grouping values by the synchronized timestamp. The default behavior does not change. The synchronized timestamp can be used by setting `synchronized_timestamp = true` in the historian configuration.
- Calculates synchronized timestamp is using the time slot offset in device scrapes
- Message bus carries the synchronized timestamp
- Updates base historian to capture header timestamp instead of header date from the device data
- Fixes broken unit tests for historian
This was tested using a single emulated modbus device with a master driver configured with multiple devices using the same emulator. We tried various configurations to change the device groups …

Updates master driver/base historian to include synchronized timestamp

---

volttron/platform/agent/cron.py

When a schedule like the following is used:
`cron.schedule('0 1 * * *', start=datetime(2018, 10, 18, 12))`
the first date returned should be `2018-10-19 01:00:00`. Before this fix,
however, `2018-10-01 01:00:00` was returned because first_day was not
being used to create the day range.
Fixes #1824
This was tested using the code snippet above with a range of start dates as well as iterating over the returned generator to ensure it reset in the following month.
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1825?approve=1'><img …

Fixes incorrect start day bug in cron scheduler

---

docs/source/devguides/agent_development/Agent-Development-Cheatsheet.rst
examples/CAgent/c_agent/agent.py
examples/DDSAgent/ddsagent/agent.py
examples/DataCleaner/data_cleaner/agent.py
examples/ExampleSubscriber/subscriber/subscriber_agent.py
examples/NodeRed/node_red_subscriber.py
examples/StandAloneListener/standalonelistener.py
examples/StandAloneWithAuth/standalonewithauth.py
examples/WeatherForecastCSV_UW/weatherdata/agent.py
services/core/DNP3Agent/tests/MesaTestAgent/testagent/agent.py
services/core/ExternalData/external_data/agent.py
services/core/MarketServiceAgent/market_service/director.py
services/core/MongodbHistorian/mongodb/historian.py
services/core/ObixHistoryPublish/obix_history/agent.py
services/core/OpenADRVenAgent/openadrven/agent.py
services/core/OpenADRVenAgent/test/ControlAgentSim/controlagentsim/agent.py
services/ops/AgentWatcher/watcher/agent.py
services/ops/FailoverAgent/failover/agent.py
services/ops/SysMonAgent/sysmon/agent.py
services/ops/TopicWatcher/topic_watcher/agent.py
volttron/platform/agent/cron.py
volttron/platform/scheduling.py
volttron/platform/vip/agent/__init__.py
volttron/platform/vip/agent/core.py
volttron/platform/vip/agent/example.py
volttron/platform/vip/agent/subsystems/heartbeat.py

Adds the ability to pass iterable objects to the core schedule decorator and associated method (dualmethod) as the deadline parameter. The iterable should yield datetime objects in increasing order and the scheduled function will be executed at the first time and automatically rescheduled at each execution, using the next time in the iterator. A new periodic() generator is added to use with the updated schedule functions, obsoleting the periodic decorator and associated method, which are now marked as deprecated.
Fixes #1823 
Functionality was tested using a simple agent that schedules simple tasks using cron.schedule() and periodic() generators. The full suite of CI tests was also successfully run.
<a href='#crh-start'></a><a …

Iterable schedule

---

services/core/ActuatorAgent/tests/test_actuator_rpc.py
services/core/DataMover/tests/test_datamover.py
services/core/ForwardHistorian/tests/test_forward_historian.py
services/core/ForwardHistorian/tests/test_forwardhistorian.py
services/core/InfluxdbHistorian/tests/test_influxdb_historian.py
services/core/SQLHistorian/tests/test_sqlitehistorian.py

#Description
Travis tests on the ForwardHistorian were sometimes failing because a comparison of floats which were nearly equivalent (off by 1e-16) returned false. The approx method in pytest does an epsilon comparison of floats with eps=1e-6 by default, which is good enough for our purposes, so I used approx within the ForwardHistorian test to compare floats. I also dug through the rest of the services/core dirs to find other places where questionable floats were being compared and used approx on those as well.
##Type of change
Bug fix (non-breaking change which fixes an issue)
#How Has This Been Tested?
I first tested the approx method in a sandbox environment to ensure that it would work appropriately on cases like those one would expect in the ForwardHistorian. I then integrated …

Use pytest's approx method to compare equality of floats in tests

---

bootstrap.py

virtualenv 16.1.0 changes the package structure pin virtualenv to 16.0.0
Fixes #1834 
Tested on linux mint
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1836?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1836'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Fixes #1834 - develop

---

bootstrap.py

virtualenv 16.1.0 changes the package structure pin virtualenv to 16.0.0
Fixes #1834 
Tested on linux mint
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1835?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1835'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Fixes #1834

---

examples/StandAloneListener/settings.py
examples/StandAloneListener/standalonelistener.py

Updated documentation of examples/StandAloneListener agent
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/VOLTTRON/volttron/pull/1841%23discussion_r234325487%22%2C%20%22https%3A//github.com/VOLTTRON/volttron/pull/1841%23discussion_r234326521%22%2C%20%22https%3A//github.com/VOLTTRON/volttron/pull/1841%23discussion_r234327585%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%20adced64fd53e1492d621a9e44cdb1721e5be0daa%20examples/StandAloneListener/standalonelistener.py%205%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/VOLTTRON/volttron/pull/1841%23discussion_r234325487%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22There%20should%20be%20a%20preamble%20before%20starting%20at%201.%22%2C%20%22created_at%22%3A%20%222018-11-16T19%3A40%3A16Z%22 …

Add documentation to standalone agent.

---

README.md

Modified README.md to alert users that one could use the rabbit_dependencies.sh script if they are running an Ubuntu system.
Documentation change.
N/A as this is soely a documentation update. Used markdown previewer provided by PyCharm to ensure markdown format was correct.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/VOLTTRON/volttron/pull/1838%23discussio …

Modified README.md to account for rabbit_dependencies script

---

pytest.ini
scripts/rabbit_dependencies.sh
volttron/utils/rmq_setup.py
volttrontesting/utils/platformwrapper.py

Changes - 
updated script that installs dependencies for Rabbit to handle centos 
Updated logic to check rabbitmq status
Added HOME, and LANG to env when starting volttron in platformwrapper so that Rabbitmq will work right
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1851?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1851'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Fixed rmq test issues. Updated logic to check rabbitmq status

---

services/core/MasterDriverAgent/master_driver/driver.py
services/core/MasterDriverAgent/master_driver/interfaces/bacnet.py

Updates driver to use the correct configuration/topic combinations when publishing COV messages.
Updates bacnet interface to use the configured COV lifetime rather than always using the default lifetime.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/VOLTTRON/volttron/pull/1855%23discussion_r239547920%22%2C%20%22https%3A//github.com/VOLTTRON/volttron/pull/1855%23discussion_r239555650%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%2044732ba303602bdb04658a7e2fe7b3f92877dc61%20services/core/MasterDriverAgent/master_driver/driver.py%2016%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/VOLTTRON/volttron/pull/1855%23discussion_r239547920%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22The%20message%20is%20wrong%20for%20the%20publish_depth_fi …

Bacnet COV fixes

---

services/core/DNP3Agent/dnp3/agent.py
services/core/DNP3Agent/dnp3/base_dnp3_agent.py
services/core/DNP3Agent/dnp3/mesa/agent.py
services/core/DNP3Agent/dnp3/mesa/functions.py
services/core/DNP3Agent/dnp3/mesa_points.config
services/core/DNP3Agent/dnp3/outstation.py
services/core/DNP3Agent/dnp3/points.py
services/core/DNP3Agent/mesaagent.config
services/core/DNP3Agent/tests/data/mesa_points.config
services/core/DNP3Agent/tests/data/mesaagent.config
services/core/DNP3Agent/tests/test_mesa_agent.py

- Now able to send a single DNP3 point.
- mesaagent.config: add function_validation field with default value to false. If function_validation is false, it is allowed to send a single point without throwing function validation exception. If function_validation is true, the function will be checked to make sure there are no duplicate steps, that the steps are received in order, and that no mandatory steps are missing.
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1868?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a …

DNP3: send single point 

---

volttron/platform/config.py
volttron/platform/main.py
volttron/utils/rmq_config_params.py
volttron/utils/rmq_setup.py

Created more descriptive error message in the event that yml file has incorrect syntax errors. Note: current fix results in error message being printed twice (which is why change is currently listed as breaking change below).
Fixes #1864
Removed colons after ``volttron-host`` and ``amqp-port`` in ``examples/configurations/rabbitmq/rabbitmq_config.yml`` 
Run ``vcfg --rabbitmq single /home/username/volttron/examples/configurations/rabbitmq/rabbitmq_config.yml``
Current output:

RMQ Config yml  syntax error message

---

services/core/DNP3Agent/dnp3/agent.py
services/core/DNP3Agent/dnp3/base_dnp3_agent.py
services/core/DNP3Agent/dnp3/mesa/agent.py

Updates the DNP3 and Mesa Agents to properly use config store. Fixes default configuration overriding config store configuration.
Unit tests still pass (as often as this did before, anyway)
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1885?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1885'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Fixes for DNP3 and Mesa's use of the config store.

---

services/core/InfluxdbHistorian/influx/historian.py

influx historian cannot handle 'record/*' topic format and raises error when messages are written to 'record/*'. To avoid the error 'record/*' messages are being excluded from handling. No further dependencies.
String message has been published on 'record/*' in our test installation, no more errors raised.
No unit-tests because fixture 'volttron_instance' is hanging (no response) on OSX installation (known problem?)
Where can I find the styleguide?
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1833?approve=1'><img …

influx historian cannot process topic data of record/*

---

services/core/CrateHistorian/cratedb/historian.py

Remove datetime tzinfo before Crate Historian sends query to Crate client. Functionality unaffected, since base historian has already enforced UTC.
Fixes #1888 
- Bug fix (non-breaking change which fixes an issue)
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1889?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1889'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

fix datetime tzinfo mismatch with crate client

---

volttron/platform/instance_setup.py

Fixed #1887
Initially required a .git folder to be present in order to run vcfg.  This has been removed.
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1890?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1890'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Removed git requirment

---

volttron/platform/control.py

Fixed #1896 causing an error when restoring agent data from installer.

Fixed broken control function

---

volttron/platform/scheduling.py

When a cron schedule like the following is used:
```
from volttron.platform.agent import cron
print next(cron('0 0 * * 1-5', start=datetime(2019, 2, 3, 0)))
>>> 2019-02-01 00:00:00
```
the first datetime should be 2019-02-04 00:00:00, the next weekday after the start date. However, 2019-02-01 00:00:00 is yielded first because first_day is not being used to create the weekday range.
Fixes #1892
Tested with the above snippet, iterating several times and with various start dates, similar to #1825

fix weekday scheduling bug

---

services/core/DataMover/README.rst
services/core/DataMover/config
services/core/DataMover/datamover/agent.py

Allows a specific identity to appear in a peer list on the destination (remote) machine.  Useful to detect outage from a central instance using the AgentWatcher.
Fixes #1900 
Tested on PNNL internal campus deployrment

Forwarder datamover remote identity

---

services/ops/TopicWatcher/config
services/ops/TopicWatcher/topic_watcher/agent.py
volttron/platform/vip/agent/subsystems/health.py
volttron/platform/vip/agent/utils.py

Updates the TopicWatcher to send alerts to a remote platform if a device doesn't publish in a specified period of time.  This does not change existing behaviour only enhances and allows a remote publishing of the alert.
Fixes #1899 
Tested on PNNL campus deployment

Update TopicWatcher Agent

---

volttron/platform/control.py
volttron/platform/vip/agent/core.py
volttron/platform/vip/proxy_zmq_router.py

Additional corrections to Issue#1962. Sending 'agentstop' message inside stop method is causing unexpected behavior during platform shutdown. Router is stopping before all the agents are stopped which not ideal. Will create a separate PR to resolve that issue.
Fixes # 1962

Fixes for Issue#1962.

---

examples/configurations/rabbitmq/rabbitmq_config.yml
volttron/utils/rmq_config_params.py
volttron/utils/rmq_setup.py

added additional use-existing-certs prompt to avoid prompts about existing certs. If this optional parameter is not set, user will be prompted when ssl certificate exists when running "vcfg --rabbitmq single"  command. If set to True, script will use existing certs. If set to False, script will create new certs overwriting any existing certs

added option to rabbitmq config to avoid prompts during setup

---

bootstrap.py

Fix the HTTPS issue for the virtualenv url
#1679 
Locally and travis
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1716?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1716'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

#1679 Require HTTPS

---

services/ops/ThresholdDetectionAgent/tests/test_thresholddetection.py

Fixed simple timing issue with rmq in thresholddetectionagent
tested locally and against run-test-docker

fixed timing issue with RMQ for thresholddetection tests

---

docs/source/community_resources/documentation.rst
docs/source/community_resources/index.rst
docs/source/index.rst

Replaced  VOLTTRON\ :sup:`TM` with .. unicode:: VOLTTRON U+2122
This replaces the TM superscript with the unicode TM.
This was done everywhere in the documentation.

Replaced large TM with small TM

---

pytest.ini
services/core/DNP3Agent/tests/mesa_master_cmd.py
services/core/DNP3Agent/tests/mesa_master_test.py
services/core/DNP3Agent/tests/test_dnp3_agent.py
services/core/DNP3Agent/tests/test_functions.py
services/core/DNP3Agent/tests/test_mesa_agent.py
services/core/DNP3Agent/tests/test_points.py
services/core/DNP3Agent/tests/unit_test_point_definitions.py
volttron/platform/messaging/topics.py
volttron/platform/vip/agent/subsystems/health.py
volttron/platform/vip/agent/subsystems/heartbeat.py
volttrontesting/subsystems/test_health_subsystem.py

This PR addresses an issue that was introduced when alerts started using identities instead of guid of the installed agent.  This issue is relevant when an agent attempts to send an alert due to agent health.
Note in the alert topic that is raised during the send_alert call, the identity has a string replacement for '.' to '_'.  This change allows rmq and other message buses that use a '.' delimiter to correctly subscribe to the alerts (such as EmailerAgent).
Fixes #2009 
test_health_subsystem now has a test which tests the contents of the alerts

alert handle using identity

---

volttron/platform/vip/agent/subsystems/pubsub.py
volttron/platform/vip/agent/subsystems/rmq_pubsub.py
volttrontesting/subsystems/test_pubsub_subsystem.py
volttrontesting/subsystems/test_rmq_pubsub.py

Allowed users to remove all subscription by sending None for prefix and callback to unsubscribe, fixed rmq_pubsub test
Fixes #1591 (previously closed)
response to https://volttron-community.slack.com/archives/C40SDK44E/p1557749359023200

pubsub unsubscribe issues

---

scripts/rabbit_dependencies.sh

Use erlang-solutions server rather than the link from bintray.  This seems to be a better standard for erlang distributions.
Fixes #2023
Tested with xenial xfce distribution.

Updated rmq dependencies

---

volttron/platform/main.py
volttron/platform/vip/rmq_router.py

Found 'error' and 'unknown operation' in list of peers when testing "vctl peerlist" command. This was introduced due to unintentional if-else condition in rmq router. Corrected the if-else error
Fixes #2015

 'error' and 'unknown operation' in peerlist

---

volttron/utils/rmq_config_params.py
volttron/utils/rmq_setup.py
volttrontesting/platform/test_platform_rmq.py
volttrontesting/utils/platformwrapper.py

Fixes in
- platform wrapper to do rmq single instance setup at init instead of platform start
- rmq config object to set defaults. Without this admin user is gets created as None
- Fixed test_platform_rmq to accommodate changes in platform wrapper, remove irrelevant test case, and added better error handling.

Changes to get all rmq certs tests to pass

---

bootstrap.py
optional_requirements.json

Issue:
optional installs of rabbitmq did not get installed when running 
`python bootstrap.py --rabbitmq` in a brand new environment (i.e. no env folder and volttron.egg-info folder)
Fix:
fixed rabbitmq optional installs on bootstrap in new env by adding the optional arguments to the list of packages to be installed 
Also added crate to list of optional requirements for --databases
Test:
Tested running bootstrap.py with --rabbitmq and other optional arguments in a new environment

fixed rabbitmq optional installs on bootstrap in new env. 

---

services/ops/EmailerAgent/emailer/agent.py

Fixes an issue with the emailer when a null message is passed the log message would have failed.
Added the ability to specify user in the email payload itself.
This has been tested on the internal campus deployment at PNNL.  I modified the test_send script to have a to-addresses entry and saw that it worked as expected.

Emailer Error and Enhancement

---

volttron/platform/instance_setup.py

The instance name was not changing correctly because instance_setup.py was not calling the config file after the change had been made to the instance name by setup_rabbitmq_volttron. This has been fixed.

Fixed bug when instance name was changed.

---

services/core/SQLHistorian/config.sqlite
volttron/platform/agent/base_historian.py
volttron/platform/agent/utils.py
volttron/platform/certs.py
volttron/platform/vip/agent/core.py
volttron/platform/vip/agent/subsystems/hello.py
volttrontesting/fixtures/volttron_platform_fixtures.py
volttrontesting/platform/web/test_discovery.py
volttrontesting/services/historian/test_multiplatform.py
volttrontesting/testutils/test_multimessagebus_fixture.py
volttrontesting/utils/platformwrapper.py

Added all_platform configuration to historian. By default this will be false. Added test case to test this using both multiple zmq instances and multiple rmq instance. Testing with rmq, required adding federation setup capability to platform wrapper and fixing handling of os.environ when there is more than one volttron platformwrapper instance used within a test case.

Added all_platform configuration to historian

---

volttron/utils/rmq_setup.py

The warning during settup of rabbitmq was displaying even though there may not have been one present

Fix display of warning without a rabbitmq_conf file

---

docs/source/devguides/walkthroughs/Driver-Creation-Walkthrough.rst
examples/CSVDriver/csvdriver.py

Fixes improperly named inherited methods in example code which leads to the driver failing to start on the Volttron platform.
Tested manually using master driver/listener and actuator/test CSV driver agents

Fixed bug with improperly implemented inherited methods in CSV Driver Examples and Update Walkthrough

---

docs/source/core_services/historians/SQL-Historian.rst
services/core/SQLHistorian/README.rst
volttron/platform/dbutils/postgresqlfuncts.py

Added support for using the TimescaleDB Hypertable backend for the PostgreSQL historian
Also updated readthedocs to include postgresql historian documentation.
* Hardware:
* Toolchain:
* SDK:

Added support for timescaleDB  and updated docs

---

volttron/platform/control.py

Removed debug statements that were causing a bug to occur when no capability was specified when using **vctl auth add**.
When capability was not specified, these print statements caused this error:
**auth: error: 'capabilities'**
Removing them fixes the issue.

Fixed bug when using vctl auth add

---

volttron/platform/control.py

There was an extra space in merge #2199 this addresses that issue.
Fixes #2199 
Tested running multiple commands without expected arguments
`vctl auth` etc

Fixed space issue which caused error

---

volttrontesting/utils/platformwrapper.py

***Issue Bug Fix*** #2201 
When running an agent test using `pytest`, the following exception is raised:
```
..
except:
exc_type, exc_value, tb = sys.exc_info()
exc_lines = traceback.format_exception(exc_type,
exc_value,
tb)
exc_value.child_traceback = ''.join(exc_lines)
os.write(errpipe_write, pickle.dumps(exc_value))
finally:
os._exit(1)
self._child_created = True
if gc_was_enabled:
gc.enable()
finally:
os.close(errpipe_write)
devnull_fd = getattr(self, '_devnull', None)
if p2cread != -1 and p2cwrite != -1 and p2cread != devnull_fd:
os.close(p2cread)
if c2pwrite != -1 and c2pread != -1 and c2pwrite != devnull_fd:
os.close(c2pwrite)
if errwrite != -1 and errread != -1 and errwrite != devnull_fd:
os.close(errwrite)
if devnull_fd is not None:
os.close(devnull_fd) …
```

Fix platformwrapper.py wrapper command in Develop branch tests

---

volttron/platform/main.py

This pull request simply turns down some of the logging that has been spread throughout the debugging process.  This turns logging level down to a fair amount of services on the volttron side.

Tone down logging to server side entitities

---

examples/StandAloneListener/settings.py
volttron/platform/agent/known_identities.py
volttron/platform/auth.py
volttron/platform/certs.py
volttron/platform/instance_setup.py
volttron/platform/main.py
volttron/platform/web/__init__.py
volttron/platform/web/admin_endpoints.py
volttron/platform/web/master_web_service.py
volttron/platform/web/templates/login.html
volttron/platform/web/templates/pending_auth_reqs.html
volttrontesting/fixtures/volttron_platform_fixtures.py
volttrontesting/platform/auth_control_test.py
volttrontesting/platform/test_platform_web.py
volttrontesting/platform/web/test_web_authentication.py
volttrontesting/services/test_masterweb.py

Added the ability to manage zmq credentials from the admin webpage when using https.
Works with both zmq and rabbitmq message buses.
Changed master.web to master_web for MasterWebServices identity.

Updated admin endpoints

---

volttron/platform/agent/utils.py
volttron/platform/instance_setup.py

Updated instance_setup.py to handle missing dependencies required b vcfg choices. 
Fixed race condition where volttron instance would try to start before previous volttron instance had fully stopped, leading to undesirable behavior.
Checks if the volttron instance is running using is_volttron_running.
VC questions have been re-enabled (VC and web PR to follow)
Checks if volttron instance needs to be shutdown on exit from the program.

Updates to vcfg

---

docs/source/core_services/drivers/master_driver_override.rst

Adds documentation to docs core_services/drivers covering driver override capability in master driver agent.
Fixes #1290
Documentation update only.

Issue 1290: Add master driver override capability docs to core_services/drivers

---

volttron/platform/aip.py

"agent-data" was created in the beginning. Now it is added during start of the agent

Adding statment to create agent-data directory

---

volttron/utils/rmq_setup.py

Using yaml.safe_load() instead of yaml.load() while reading rabbitmq federation/shovel config file.

Added yaml.safe_load while reading federation or shovel config file

---

README.md

Adds documentation line describing an additional step necessary if using the example rabbitmq yml config file during platform setup.
Fixes #2289
This documentation addresses a problem that can occur when using the example rabbitmq yml config file when setting up a rabbitmq volttron instance using vcfg

Added clarification to readme for using example rabbitmq yml file

---

examples/DataPublisher/README.rst
examples/DataPublisher/test.config

Added note in DataPublisher example config and README to alert the user to the need for the full filepath when specifying an input file.
Response to #2275

Minor documentation revision to DataPublisher agent.

---

volttron/platform/agent/utils.py
volttron/platform/aip.py
volttron/platform/control.py
volttron/platform/vip/socket.py

This PR fixes two underlying problems. When the agent gets upgraded, the same public key and secret key is being used. But the secret key was getting encoded twice which was causing assertion error. The second problem was "agent-data" directory was not created when agent is reinstalled to copy over saved agent data files. Fixed both the issues.
Fixes #2318

Fixes issue#2318 

---

README.md

A small fix to show the correct rabbitmq path.

docs(README.md): Remove rabbitmq_server duplication

---

docs/source/overview/version-history.rst

Small change to remove space in RabbitMQ.
Doc-change only.

Docs: Fix Spelling Error

---

docs/source/core_services/drivers/driver_configuration/modbus-tk-driver.rst
services/core/MasterDriverAgent/master_driver/interfaces/modbus_tk/client.py

Add's warnings on Modbus_Tk driver configuration documentation and Modbus_Tk client describing issue connecting 2 masters on one IP to 2 slaves on one IP
https://github.com/ljean/modbus-tk/issues/124
Built Sphinx documentation to validate styling

Documented issue with modbus_tk 2 masters on 1 IP to 2 slaves on one IP

---

volttron/platform/vip/agent/results.py

Incorrect Frame de-serialization of message identifier frame in fedora and ubuntu 19.10 systems was causing some of the features in VOLTTRON to break, namely
1. "vctl status" command 
2. "vctl auth serverkey" command
3. Database was not getting created at startup of historians
Changing the format of message identifier seems to have fixed the problem
Fixes #2324 #2323 #2322

Fixes issue#2324 #2323 #2322

---

docs/source/core_services/openadr/VtnServerConfig.rst
docs/source/core_services/openadr/VtnServerGuide.rst

Updates OpenADR VTN server documentation (configuration and use docs) to specify current known issues, missing features, and to specify that the existing code base for the VTN server in VOLTTRON applications was developed by Kisensum, and is not currently supported by the VOLTTRON core team.

Updated OpenADR VTN documentation on VOLTTRON core support and Known Issues

---

examples/CSVHistorian/csv_historian/historian.py

Fixed CSVHistorian failing to start and showing bad health as a result of opening a file in bytes mode and then using the Python3 CSV DictWriter to write headers as strings.
Fixes #2356
Installed and started CSVHistorian, configured master driver with fake driver, fake driver collected data points, confirmed contents of CSVHistorian's "database" (currently no unit tests exist for this example agent).

Fixed CSVHistorian opening file in bytes mode

---

volttron/platform/auth.py
volttron/platform/vip/agent/subsystems/peerlist.py

AuthService attempts to get peerlist to send the auth updates to all it's peers. The peerlist subsystem is able to get the list of peers from router, but is unable to set the result into asyn result object properly. As a workaround, peerlist subsystem now keeps track of list of peers to make it accessible to auth service
Fixes #2345

Fixes issue#2345. 

---

pytest.ini
volttrontesting/fixtures/docker_wrapper.py
volttrontesting/platform/dbutils/test_mysqlfuncts.py

Add level one integration tests for the MySQLFuncts class which provides the interface between a MySQL database and the SQL Historian agent. 
This test uses a Docker image of MySQL to act as the production database for testing. The database is seeded with data by executing SQL statements directly in the Docker container. [MySQLConnector/Python](https://dev.mysql.com/doc/connector-python/en/) is used to verify tests by reading the database and using that output to asserting that the actual result is equal to the expected result.
This test does not test the `get_agg_topics` method because I was still having problems getting it to work but didn't want that one test to block the publication and feedback of this PR. That method will be addressed in a later PR or commit to this PR.
The tests …

Add level one integration tests for MySqlFuncts

---

docs/source/community_resources/index.rst

Removes link to volttron slack signup page which threw a 404, replaces with email link.
Fixes # 2254
Tested against local Sphinx build for this branch

Updated references to Slack signup to use volttron mailing list

---

volttrontesting/fixtures/docker_wrapper.py

Remove duplicate try/except block so that the wrapper works as expected. Currently, the wrapper tests return None instead of a container, leading to failing tests.
I ran the current unit tests for the docker wrapper. See below:
```bash
$ pytest test_docker_wrapper.py
test_docker_wrapper.py::test_docker_wrapper PASSED                                                                                                               [25%]
test_docker_wrapper.py::test_docker_run_crate_latest PASSED                                                                                                  [50%]
test_docker_wrapper.py::test_docker_wrapper_should_throw_runtime_error_on_false_image_when_pull PASSED                  [75%] …
```

Remove duplicate try/except in docker_wrapper

---

scripts/rabbit_dependencies.sh

The latest commit for develop fails to build on Travis CI not because tests have failed but because one of the build scripts, `rabbit_dependencies.sh` fails to install rabbit dependencies, e.g. erlang, which is needed later in the build. One of the last lines in Travis logs shows that a rabbit dependency did fail to build (i.e. erlang):
```bash
/sbin/rabbitmq-plugins: 360: exec: erl: not found
```
Earlier in the Travis CI logs, it points to two lines in that script that are failing:
```bash
./scripts/rabbit_dependencies.sh: line 76: sudo: command not found
....
./scripts/rabbit_dependencies.sh: line 79: sudo: command not found
```
Because of this, rabbit dependencies such as erlang are not installed. Travis CI logs confirm this:
<details>
<summary> Click to see the logs</summary>
```bash …
```

Modify rabbit_dependencies.sh so that tests will run in Travis CI

---

ci-integration/virtualization/requirements_test.txt

Add mysql to requirements_test.txt to run level one integ tests for Mysql as part of CI. This change will allow `run-test-docker.sh` to run the MySQL level one integration tests in Travis CI.
I have ran `run-test-docker.sh` both locally and on Travis CI but the tests were not able to run due to a permissions error. I believe the issue lies in the container having root privileges to run docker commands within a container. However, that is an issue with running docker commands within a container that is not a root user, which is out of the scope of this PR.

Add mysql to requirements_test for testing in Docker

---

volttron/platform/vip/agent/results.py

Replaced counter initialization from random number generation function to datetime timestamp integer in results.py. This makes generation of counter time based and avoids overlapping with other object calls
Fixes#2417

Fixes Issue#2417 .

---

examples/ListenerAgent/config
examples/ListenerAgent/listener/agent.py

Adds runtime_limit option to have Listener agent automatically stop after a specified max interval. If not defined (None), the agent would run indefinitely (current behavior). 
Fixes #2231 
This update is tested on my virtual machine for the 30 and 120-second intervals. This function is also tested without the runtime_limit criteria on the config file.

listeneragentwithruntime

---

examples/DataPublisher/datapublisher/agent.py

Default unit is formatted incorrectly.
This caused an error related to meta data in historian agent.
So I modified the second return of the '_get_unit' function of datapublisher.

modify return value of _get_unit

---

.gitignore
pytest.ini
services/core/ActuatorAgent/tests/actuator_fixtures.py
services/core/ActuatorAgent/tests/test_actuator_pubsub_unit.py
services/core/ActuatorAgent/tests/test_actuator_rpc_unit.py

Add unit tests for Actuator's RPC and PUBSUB methods.
Fixes #2355
**Test Configuration**
- VM: Virtualbox
- OS: Ubuntu
- Python: 3.6.9
- TestFramework: Pytest
Pytest commands and output (commands were run in the directory of the source actuator files:
```bash
$ pytest -m actuator_unit
======== 64 passed, 159 deselected in 1.32s ======== 
```

Add unit tests for actuator

---

examples/DataPublisher/datapublisher/agent.py

Modify the DataPublisher agent for restarting playback and wrapping metadata as dict.
Fixes #2321
I tested the modification with the following configuration:
> 
"remember_playback": false,
"reset_playback": true,
"replay_data": true,
"topic_separator": "/"
>

modified for restarting playback and wrapping metadata as dict

---

volttron/platform/agent/base_historian.py

Fix saving of timezone metadata in base historian for datalogger topics where the timezone is not explicitly provided. 
#2351 
Write string representation of timezone to database rather than pytz.timezone object.
Publish datalogger topic without specifying 'tz' key explicitly. This will raise an error without the change when the metadata is saved to the sqlite.backup file without the change.  Works with the change.
* Hardware:
* Toolchain:
* SDK:

Fixed timezone in metadata to save string to database in place of pytz object.

---

bootstrap.py
requirements.py

#Description
Bootstrap was ignoring optional rabbitmq server install directory. Bootstrap now handles rabbitmq server installation separately so that non-default rabbitmq install path can be accepted.
Fixes #2110

Fixes issue#2110. 

---

volttron/platform/instance_setup.py

Removed rmq automatic installation from vcfg and replaced with message to users directing them to install from script and bootsrap due to changes in rmq installation.
Now checks for rmq using is_rabbitmq_available().

Vcfg fixed rmq issues

---

docs/source/agent-framework/agents-overview.rst
docs/source/agent-framework/core-service-agents/openadr-ven/ven-agent.rst
docs/source/agent-framework/example-agents/index.rst
docs/source/agent-framework/historian-agents/historian-framework.rst
docs/source/agent-framework/web-framework.rst
docs/source/deploying-volttron/platform-hardening.rst
docs/source/driver-framework/bacnet/bacnet-auto-configuration.rst
docs/source/driver-framework/drivers-overview.rst
docs/source/index.rst
docs/source/platform-features/config-store/commandline-interface.rst
docs/source/platform-features/config-store/configuration-store.rst
docs/source/platform-features/control/authentication-commands.rst
docs/source/platform-features/message-bus/index.rst
docs/source/platform-features/message-bus/vip/vip-overview.rst
docs/source/platform-features/security/volttron-security.rst
docs/source/platform-features/web-framework/web-framework-overview.rst

Updates the title of some Readthedocs articles to be more concise for the topic, less redundant, and remove excessive references to VOLTTRON.  
Tested with Sphinx build in docs dir.

Make RTD headings more concise and less redundant

---

docs/source/deploying-volttron/volttron-central.rst
docs/source/introduction/how-does-it-work.rst
docs/source/platform-features/security/running-agent-as-user.rst

After following the Volttron Central Demo on the docs, I noticed some inconsistencies on what was on the docs and what I actually saw when I went through the Central Demo docs. I also added some clarity on the web interface address to give users more idea of what it is and also to match the experience I had when first opening the web interface.
Note: I used Ubuntu 20.04 to run the Volttron Central Demo instructions.
I built the docs using the following commands and opened the docs on my local machine. Screenshots attached of the updated areas. Click the dropdown button below. 
<details>
<summary>Screenshots click here </summary>
</details>

Update output messages and web interface address in VCentral Demo docs

---

scripts/rabbit_dependencies.sh

missing `-y` flag to apt-get install in installer script

install needs -y

---

requirements.py

As part of getting volttron-docker to successfully create a container, `greenlet` needs to be pinned to an old version due to bug in gevent (see https://github.com/phovea/phovea_server/issues/130). 
By building the image in the Dockerfile in volttron-docker, I was able to execute the script and the rest of the Docker layers. I also was able to start volttron in `bootstart.sh`. Before this change, the container, running Python 3.7, failed to start volttron because of this greenlet issue.

Pin greenlet to old version

---

volttron/platform/dbutils/postgresqlfuncts.py
volttrontesting/platform/dbutils/test_postgresqlfuncts.py

Changes setup of aggregate historian tables so that all tables are properly set. Updates the associated tests. 
Detailed explanation below:
`setup_aggregate_aggregate_historian_tables` and `read_tablenames_from_db` both rely that the metadata table have the following values for the field 'table_name': data_table, topics_table, and meta_table. If those fields are not present or correctly spelled, then the aggregate tables will not be created and the table attributes of the `postgresfuncts` instance will be set to None instead of some name. In other words, `postgresfuncts` assumes that the metadata table exists and is properly initialized. In other words, this change ensures that some default value is given instead of None when a key is missing from a dictionary; see …

Fix setup of default aggregate historian tables

---

volttrontesting/platform/dbutils/test_postgresqlfuncts.py

Add additional test cases for `query_topics_by_pattern` method on Postgresql tests. 
In addition to testing for patterns in the prefix, we need to test for it in the middle and at the suffix. I have also added tests for case-insensitive cases ([MYSQL is case-insensitive by default when performing pattern matching](https://dev.mysql.com/doc/refman/5.7/en/pattern-matching.html)). I have also added a test for matching an exact match or greater (e.g. searching "foo" will match "fooooooobar" but not "fobar").
I've ran the test locally on my IDE.

Update test query topic

---

ci-integration/virtualization/Dockerfile.testing
pytest.ini
volttrontesting/platform/dbutils/test_sqlitefuncts.py

Add level one integration tests for sqlitefuncts. Since sqlite3 comes out-of-the-box with Python3, no test containers (docker wrapper) were required. In addition to adding the tests, I added a layer to Dockerfile.testing so that the container has sqlite3 installed. Most methods, mainly from the parent class DbDriver, were tested. Some static and sqlitefuncts-class specific were not tested since they were either out of scope and/or will be addressed in a later PR.
I ran the tests in three ways:
1. Ran tests locally in Pycharm and on the command line: `pytest -m sqlitefuncts`
1. Ran `run-test-docker-.sh` locally. 
1. Ran the tests on Travis CI on a throwaway branch. For results of the build, see: https://travis-ci.org/github/bonicim/volttron/builds/719382480
Code coverage on sqlitefuncts.py …

Add sqlite tests

---

pytest.ini
services/core/ActuatorAgent/tests/test_actuator_pubsub_unit.py
services/core/ActuatorAgent/tests/test_actuator_rpc_unit.py
volttrontesting/platform/dbutils/test_mysqlfuncts.py
volttrontesting/platform/dbutils/test_postgresqlfuncts.py

Add a 'unit' test marker in order to run all unit/level one integ tests from the command line using Pytest.
Use 'pytestmark' to mark a whole module with a custom marker. See https://docs.pytest.org/en/stable/reference.html#globalvar-pytestmark
Run the following on the command line; navigate to a certain directory to run all the tests under that directory
```bash
$ pytest -m unit services/core/AcutatorAgent
$ pytest -m unit volttrontesting/platform/dbutils 
```

Add unit marker to pytest

---

ci-integration/virtualization/requirements_test.txt
pytest.ini
volttrontesting/fixtures/docker_wrapper.py
volttrontesting/platform/dbutils/test_influxdbutils.py

Add level one integ tests for influxdbutils, which is the workhorse of Influxdb Historian. 
Note: I had to add the "version=auto" parameter to the docker_wrapper because when I ran the tests on TravisCI, the build would fail because the docker_wrapper was using a too new version of the docker client, giving an error message of:
```
docker.errors.APIError: 400 Client Error: Bad Request ("client version 1.39 is too new. Maximum supported API version is 1.38")
```
So to get around this problem on Travis, I set the "version" parameter on `docker.from_env()` to automatically detect and use the server's version of Docker.
1. Ran tests locally on Pycharm with Pytest. 
1. Ran `run-test-docker.sh` locally
1. Ran tests on TravisCI throwaway branch; for …

Add influxdbutils level one integ tests

---

scripts/bacnet/bacnet_scan.py

This updates the file write mode so that the `csv.DictWriter` usage works in Python 3. I wasn't sure if Python 2 support is deprecated or not so I left the existing code path intact with a version switch.
I tested the `scan_bacnet.py` script locally with python `2.7.17` and `3.6.9`
* Hardware:
* Toolchain:
* SDK:

Fix bacnet_scan.py in python3

---

ci-integration/run-test-docker.sh
ci-integration/virtualization/requirements_test.txt
scripts/bacnet/grab_multiple_configs.py
scripts/rabbit_dependencies.sh

This PR fixes `scripts/bacnet/grab_multiple_configs.py` in Python 3 and also adds an optional `--ini` flag which is passed through to the other bacnet scripts. 
I also helped the travis build to get further - the tests now run (before failing at an `apt-get` step) but still aren't passing. Figure that's a step in the right direction at least
Ran this locally with `Python 3.6.9` and was able to grab sensor metadata from devices successfully
* Hardware:
* Toolchain:
* SDK:

fix grab_multiple_configs.py in python3, add optional --ini cli flag

---

volttron/platform/aip.py
volttron/utils/rmq_mgmt.py

HTTPError exception does not contain 'message' attribute. Replaced that with 'status_code'. Catching the raised exception in caller method (remove_agent)
Fixes #2466

Fixes #2466. 

---

docs/source/agent-framework/historian-agents/sql-historian/sql-historian.rst
services/core/SQLHistorian/README.rst
services/core/SQLHistorian/config.sqlite
services/core/SQLHistorian/config_device_data_filter.sqlite

Fixes #2526 
Adds clarification on 'database' parameter that it should be a non-empty string, gives two examples, and revises the statements regarding the location of the database in secure vs regular mode. 
I tested creating a sqlite historian with an empty string for 'database' parameter and verified that no connection could be made since a location was not given:
```
{
"connection": {
"type": "sqlite",
"params": {
"database": ""
}
}
}
20-12-04 22:09:46,842 (sqlhistorianagent-3.7.0 109) volttron.platform.dbutils.basedb DEBUG: kwargs for connect is {'database': '/home/volttron/.volttron/agents/6272c40a-5e5a-40c4-910d-5423772a2f73/sqlhistorianagent-3.7.0/sqlhistorianagent-3.7.0.agent-data/', 'detect_types': 3, 'timeout': 10}
2020-12-04 22:09:46,842 (sqlhistorianagent-3.7.0 109) …
```

Add clarification on comments for 'database' parameter in sqlite historian config

---

volttron/platform/install_agents.py

When installing agents using scripts/install_agent.py, the script will sometimes fail for certain agents (i.e. MasterDriver/PlatformDriver), because `filename` is set to opts.install_path, which sometimes can return None. More importantly, it appears that 'filename'  was intended to be set to another variable 'install_path' as inferred from this block of code: https://github.com/VOLTTRON/volttron/blob/develop/volttron/platform/install_agents.py#L241-L244
I also removed an unused variable, `aip`.
Fixes #2548  
Installed MasterDriver (which was the case that made scripts/install_agent.py fail) and observed successful installation. 
```
$ python scripts/install-agent.py -s services/core/MasterDriverAgent --vip-identity platform.driver --force -c …
```

Fix install_agents.py to set filename to correct 'install_path'

---

services/core/BACnetProxy/bacnet_proxy/agent.py

Removes commented logging message and fixes indentation for one function in BACnet Proxy agent

Remove comment and fix function indentation in BACnet Proxy

---

volttron/platform/control.py

Initialized opts.connection to None
Modified opts.connection to only be set when volttron is running.

Modified opts.connection to only be set when volttron is running.

---

docs/source/deploying-volttron/multi-platform/forward-historian-deployment.rst
docs/source/developing-volttron/contributing-documentation.rst

After going through the current forward historian guide at https://volttron.readthedocs.io/en/develop/deploying-volttron/multi-platform/forward-historian-deployment.html#forward-historian-deployment, I found the guide hard to follow. Instead, I've changed the narrative of the guide to focus on only two things: 1) configuring a new Forward Historian Agent 2) setting up supporting Agents to verify that the Forward Historian is working. I've created two separate sections in the guide to emphasize this. 
Also, I've updated the local file path when building the docs locally through `make html`. It appears that the 'overview' directory is not created by `make html`. If the current path is entered on a browser, readthedocs does not render because the 'overview' directory does not exists. …

Update Forward Historian guide in Multi-Platform Connection section

---

docs/source/platform-features/control/platform-commands.rst
scripts/pycharm-launch.py

This PR allows a default config, config.yml or config.json file to be loaded when running pycharm-launch script.  
-

Support yml json config

---

volttron/platform/control.py
volttron/platform/install_agents.py
volttrontesting/platform/test_vctl_commands.py

Installing using vctl install --agent-config was not using the config file instead it was making an empty config in the agent directory.
Fixes # jira-356
Added tests to test the installation with an empty or non-existent config file as well as one with a listener config

Fix vctl install

---

volttron/platform/vip/agent/__init__.py
volttrontesting/utils/platformwrapper.py

Heartbeat is tied to status for vctl therefore it is necessary for this to have all installed agents get their status reported correctly.
Replaces: #2576 

Agents heartbeat autostart

---

docs/source/deploying-volttron/deployment-planning-options.rst
docs/source/deploying-volttron/secure-deployment-considerations.rst
docs/source/index.rst

Adding page u nder deploying volttron describing security considerations based on report from SSC.
Expanded documentation
- Local sphinx build renders the new page as expected including links.
- there are 71 build warnings, none of which appear to be new

adding comments from SSC

---

docs/source/introduction/platform-install.rst

Updates docs for installing RMQ. 
* Fixes hyperlinks to use RST syntax instead of Markdown
* Updates how to check RMQ status by using the RABBIT_MQ env variable, which is given by running bootstrap.py --rabbmitq
* Reemphasizes need to initially bootstrap and activate the virtual environment
* Removes unnecessary step of activating the environment since it was already done in Step 1 
* Removes illegal (Markdown) hyperlink to examples directory 
Ran make html and checked output on Browser. See screenshots:

Fix Documentation for RabbitMQ installation steps 

---

services/core/DNP3Agent/tests/test_dnp3_agent.py
services/core/DNP3Agent/tests/test_mesa_agent.py
services/core/PlatformDriverAgent/platform_driver/interfaces/ecobee.py

Fixes references to platform driver's interfaces in Ecobee Driver and MESA master in Mesa/Dnp3 tests.
Tested with Ecobee driver unit tests.

Fix broken references from Dnp3Agent and Ecobee Driver

---

docs/source/deploying-volttron/multi-platform/multi-platform-multi-bus.rst
docs/source/deploying-volttron/multi-platform/multi-platform-rabbitmq-deployment.rst
docs/source/deploying-volttron/secure-deployment-considerations.rst

Modified demos that used the web based cert authorization to include an optional method using the new auth remote sub-commands.

Updated Command Line Cert Handling in Demo Documentation

---

volttron/platform/auth.py
volttron/utils/rmq_setup.py

The federation user on upstream instance is getting created with insufficient permissions. Giving it full default permissions for now.
Fixes # Jira ticket number VOLTDEV-385

Added default permissions to federation user in the upstream instance

---

docs/source/api_doc_config.yml
docs/source/index.rst

Included ops agents' readme.md files into readthedocs. 
jira_376

Rtd pages for ops agents readme.md files

---

services/core/ActuatorAgent/tests/test_actuator_pubsub.py
services/core/ActuatorAgent/tests/test_actuator_rpc.py

Fixes path for Volttron fixture in Actuator integ tests. Currently, integ tests cannot run locally because the fixture (volttron instance) required for testing fails to be created. This happens when adding configuration files to the config store. Specifically, the path given for the config store files is a relative path, causing the tests to look for a path that does not exists (in this case "scripts/scalability-testing". To fix this, prepend the Volttron root to the path to get the absolute path to "scripts/scalability-testing".
Environment:
- Mac 10.15.7 (Catalina)
- Virtual Box 6.1
- Ubuntu 18.04 (Bionic)
- Python 3.6.9
```bash
$ pytest -m actuator
```
<details>
<summary> <b>Test results; click here</b> </summary>
``` bash
platform linux -- …
```

Fix path for fixtures in Actuator integ tests

---

volttron/platform/__init__.py
volttron/platform/aip.py
volttrontesting/platform/security/test_aip_security.py
volttrontesting/utils/platformwrapper.py

* Fixes paths to agent_dir, test helper methods to ensure both tests and fixtures are succesfully created
* Fixes SecureExecutionEnvironment's ```stop``` method to update path to internal volttron scripts
* Adds helper method to update paths to internal volttron script if not called from volttron root directory 
* Add ```VOLTTRON_ROOT``` env variable to PlatformWrapper to allow AIP tests to call internal volttron scripts (e.g. 'scripts/secure_stop_agent.sh`) 
* Remove unused imports and variables
VirtualBox 6.1
Ubuntu 18.04
Python 3.69
Ran securityagent tests on both PyCharm IDE and command line. 
Ran tests on both ZMQ and RMQ. 
<details>
<summary> <b> For Pytest results, CLICK HERE </b> </summary>
```bash …
```

Fix Integ tests for Security features 

---

volttrontesting/subsystems/test_config_store.py

Tests need test agent with config store enabled and by default it is disabled

Set enable_config_store=True for test agents

---

.github/workflows/pytest-auth.yml
.github/workflows/pytest-testutils.yml

Only changes the reporting of pytests in github actions.  Adds the -rf flag which reports failed tests at the end of the report.  This should not cause any other tests to fail!

Failed list only

---

services/core/PlatformDriverAgent/platform_driver/interfaces/modbus_tk/helpers.py
services/core/PlatformDriverAgent/tests/test_eagle.py
services/core/PlatformDriverAgent/tests/test_global_override.py

Various bug fixes in tests in platform driver's tests collection
* modbus_tk test used "long" type (removed in python3)
* exception format change causing platform driver override tests to fail
* fixed override after restart test not actually restarting platform driver instance
Platform driver integration test suite.

Bug fixes in platform driver tests

---

docs/source/setup/index.rst
requirements.py

Voltrron7 fixes

---

services/core/MasterDriverAgent/master_driver/interfaces/modbus_tk/helpers.py

Fixed reference to long type removed in python3 in ModbusTK
Master driver unit/integration tests.

Fixed reference to long type removed in python3

---

.github/workflows/pytest-testutils.yml
services/core/VolttronCentral/tests/test_vc_autoregister.py
services/core/VolttronCentral/tests/test_webapi.py
services/core/VolttronCentral/tests/vc_fixtures.py
services/core/VolttronCentral/tests/vctestutils.py
services/core/VolttronCentral/volttroncentral/agent.py
services/core/VolttronCentralPlatform/tests/test_platform_agent_rpc.py
services/core/VolttronCentralPlatform/tests/test_platformagent.py
volttrontesting/ci_test.py
volttrontesting/fixtures/cert_fixtures.py
volttrontesting/fixtures/volttron_platform_fixtures.py
volttrontesting/platform/web/test_admin.py
volttrontesting/platform/web/test_discovery.py
volttrontesting/utils/platformwrapper.py

Modifications/Fixes:
- Updated zmq for multi-messagebus fixture to use ssl.
- Removed extraneous uses of create_web_admin.
- Refactored how web admin is set in platformwrapper. Now only sets once.
- Reworked test_admin to include two tests, test_can_authenticate_admin_user and test_can_create_admin_user.
- test_can_create_admin_user is set to skip at this time (Needs to be reworked since create_web_admin is already called in platformwrapper).
- Added verify to requests.post in vctestustils to resolve openssl issue.
- Modified cleanup_wrapper to ensure platform_wrapper is terminated (may help with cleanup issues)
- Modified VolttronCentral jsonrpc unhandled exception case to properly propagate the error message through.
- Added certs_profile_2 for returning a test certificate bundle when a …

VC and Web SSL test fixes

---

docs/source/driver-framework/drivers-overview.rst
docs/source/driver-framework/platform-driver/platform-driver.rst

Fix formatting, typos in PlatformDriver docs.

Fix typos; formatting for PlatformDriver docs

---

docs/source/driver-framework/fake-driver/fake-driver.rst
volttron/platform/web/__init__.py
volttron/platform/web/authenticate_endpoint.py
volttron/platform/web/platform_web_service.py

JWT tokens used by the web framework are updated to include expiry information, and checks are made to refuse access if the token is not valid at the current time. The authenticate endpoint now accepts POST (which returns a refresh token and an access token), PUT, which returns a new access_token, and DELETE (though this currently just returns UNIMPLEMENTED). The response is now application/json, rather than text/plain. Several fixes have also been made in separate commits to unreachable code and a missing return statement which were discovered while making these changes.
Tests have not been updated, but the authentication mechanism has been tested manually using Postman.

Web Authentication updates

---

pytest.ini
services/core/PlatformDriverAgent/platform_driver/interfaces/chargepoint/tests/test_chargepoint_driver.py
services/core/PlatformDriverAgent/tests/test_eagle.py
services/core/PlatformDriverAgent/tests/test_global_override.py
services/core/PlatformDriverAgent/tests/test_global_settings.py

* Adds 'contrib' marker for pytests on community-contributed code
* Skip tests on test_eagle.py, which is community-contributed and does not work
* Add sleep for connection fixture in test_global_override and test_global_settings so that tests setup succeeds on RMQ-related tests
Ran pytest on all tests in a VM running Ubuntu 18.04. All tests pass or are skipped as configured.

Add pytest markers for contributed agent tests; add sleep for test_global_override and settings tests

---

examples/SchedulerExample/schedule_example/agent.py
services/core/ActuatorAgent/README.md

* Adds `set_multiple_points` RPC call to SchedulerExample agent in examples.
* Update Actuator README with link to SchedulerExample
Fixes #2675 
Built docs locally and checked hyperlink. Screenshot attached:

Update SchedulerExample agent and Actuator README docs

---

services/core/PlatformDriverAgent/tests/test_device_groups.py

* Add sleep to config_store_connection fixture so that connection fixture can reset the driver config store as part of the test setup (this fixture fails to build for integ tests running on Volttron platform running on RMQ)
* Remove unused parameters in fixtures
Ran pytest. See output below:
```shell
$ pytest services/core/PlatformDriverAgent/tests/test_device_groups.py 
======================================================== test session starts ========================================================
platform linux -- Python 3.7.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /home/mark2/Workplace/volttron/env/bin/python
cachedir: .pytest_cache
rootdir: /home/mark2/Workplace/volttron, configfile: pytest.ini
plugins: timeout-1.4.2
timeout: 240.0s
timeout method: signal
timeout func_only: …
```

Add sleep for config_store_connection fixture

---

volttrontesting/platform/web/test_admin.py
volttrontesting/platform/web/test_discovery.py
volttrontesting/platform/web/test_web_authentication.py

Description
-------------
Added integration tests to test_web_authentication.py for testing RPC calls to AuthService for management of pending ZMQ credentials.
Added check to test_web_authentication.py to verify if the user has a web-enabled VOLTTRON installation before running tests.
Type of change
-----------------
Updated Tests
How Has This Been Tested?
------------------------------
Ran pytest on the web/tests directory using PyCharm IDE. Some of the new integration tests in test_web_authentication.py needed to be re-ran separately before they passed. These were re-ran using the re-run failed tests option from within PyCharm, or by running the tests individually. All tests are passing.

Updated tests in proper directory

---

volttron/platform/vip/pubsubservice.py

Errors need to be serialized before sending using ZMQ's send_multipart().

Egain errors needs to be serialized

---

volttron/platform/agent/base_historian.py

removed double_precision parameter when doing ujson.dumps(). This was removed in ujson version > 2
jira396
Tested:
Ran mongo historian integration test cases to verify that nothing breaks.

removed double_precision parameter when doing ujson.dumps. 

---

volttron/platform/web/admin_endpoints.py

When the access token expires and the admin web page is refreshed, an exception is caused. With this fix, when the access token expires and the page is refreshed, a warning will be stored in the log and the user will be redirected to the login page.
Bug fix (non-breaking change which fixes an issue)
Manual test using a very reduced access token expiration time (30 seconds).
Verified that on a refresh the warning is logged, and the website is reset to the login page.
Ran web pytests and verified all pass.

Web Admin Page Timeout Fix

---

docs/source/platform-features/control/agent-management-control.rst

Clarify in the example command that the -p option is needed to set the priority.

Update Agent Auto-Start Documentation

---

scripts/install-agent.py
volttron/platform/control.py
volttron/platform/install_agents.py

This pr removes the duplication between the scripts/install-agent.py script and the vctl install command which accomplishes the same thing.  The vctl install command will be continued on and the install-agent.py script will eventually go away when we move to a partitioned library.
In addition I ran black on the install-agent.py script before committing changes to the core code.
This has been tested running both the install-agent script with options that are suitable to test the install-agent.py functionality including:
--tag --start --force --config --agent-source etc.

Install agent wrapper around vctl install

---

.github/workflows/pytest-dbutils.yml

This PR sets max to 600 seconds for the dbutils workflow.

Set timeout to max for the dbutils workflow.

---

volttrontesting/platform/dbutils/test_influxdbutils.py

Remove influxdb:latest image from influxdb tests. Influxdb:latest requires specific configuration on Docker and thus negatively impacts the influxdb test setup, which uses a different Docker configuration.
Related to issue #2738 
Ran tests locally and verified that influxdb:latest was not used for testing.

Remove influxdb:latest image

---

.github/workflows/pytest-dbutils.yml

Set CI env var in dbutils workflow so that only a limited number of images are run.
For details on env var in GitHub Workflows see https://docs.github.com/en/actions/reference/environment-variables
Tested the workflow on my GitHub account. See https://github.com/bonicim/volttron/actions/runs/1121248820

Add CI env var to dbutils workflow

---

docs/source/driver-framework/bacnet/bacnet-auto-configuration.rst
services/core/PlatformDriverAgent/tests/test_bacnet.py

Adds limited integ testing of the BACnet driver using a live BACnet device. Also fixes some documentation on using bacnet scripts.
Ran pytest on an Ubuntu VM. See output below:
```bash
pytest services/core/PlatformDriverAgent/tests/test_bacnet.py 
========================================================================= test session starts ==========================================================================
platform linux -- Python 3.7.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /home/mark2/Workplace/volttron/env/bin/python
cachedir: .pytest_cache
rootdir: /home/mark2/Workplace/volttron, configfile: pytest.ini
plugins: timeout-1.4.2
timeout: 240.0s
timeout method: signal
timeout func_only: False
collected 4 items …
```

Add integ tests for BACnet driver

---

requirements.py

This pr pins tzlocal==2.1
```
2021-08-17 23:24:33,863 volttron.platform.vip.agent.core DEBUG: Running onstart methods.
Traceback (most recent call last):
File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
File "/home/runner/work/volttron/volttron/volttron/platform/vip/agent/subsystems/heartbeat.py", line 79, in onstart
self.start()
File "/home/runner/work/volttron/volttron/volttron/platform/vip/agent/subsystems/heartbeat.py", line 91, in start
self.scheduled = self.core().schedule(periodic(self.period), self.publish)
File "/home/runner/work/volttron/volttron/volttron/platform/vip/agent/core.py", line 430, in schedule
self._schedule_iter(it, event)
File "/home/runner/work/volttron/volttron/volttron/platform/vip/agent/core.py", line 462, in _schedule_iter …
```

Pin tzlocal to 2.1

---

volttron/platform/control.py

vctl auth parser has some commands that do not require the platform to be running to execute. vctl auth serverkey relies on the platform to be running, but does not check if a connection to the platform is available. This PR is to address that.
Fixes #
Tested using vctl with and without platform running.

vctl auth serverkey requires volttron to be running.

---

services/core/VolttronCentralPlatform/vcplatform/agent.py

Change to status_agent returns 4 variables instead of 3. List_agents in vcp calls status_agent, and expected 3 arguments, causing an unpacking error to occur.

Fixed Unpacking Issue in VCP list_agents

---

.github/workflows/pytest-dbutils-backup_db.yml
.github/workflows/pytest-dbutils-influxdbfuncts.yml
.github/workflows/pytest-dbutils-sqlitefuncts.yml
.github/workflows/pytest-dbutils-timescaldbfuncts.yml
volttrontesting/platform/dbutils/test_influxdbutils.py
volttrontesting/platform/dbutils/test_mongoutils.py
volttrontesting/platform/dbutils/test_mysqlfuncts.py
volttrontesting/platform/dbutils/test_postgresql_timescaledb.py
volttrontesting/platform/dbutils/test_postgresqlfuncts.py

Creates separate Workflows for each of the test for dbutils except for mongoutils because MongoDBHistorian is unsupported. 
Reduces number of database images to be tested to 2-3 images in accordance with what documentation states on what databases have been tested on. 
Ran Workflows on my personal Github account. See https://github.com/bonicim/volttron/actions

Add workflows for dbutils tests; update db images for testing

---

volttron/platform/instance_setup.py

Vcfg used **vctl install** internally to install agents to the volttron instance with the "--config" option to set the agent configuration.  The "--config" option is used to select the configuration of the volttron instance that vctl is using, not the agent config. This has been corrected to use the correct option for setting the agent's configuration file "--agent-config". This bug was discovered when attempting to install the SQL Platform Historian with vcfg. The agent installed correctly, but was unable to start due to a broken configuration.
Manually tested using vcfg to install the SQL Platform Historian, and verified it was able to start correctly.

Fixed Agent Install Config in VCFG

---

volttrontesting/platform/auth_tests/test_auth_control.py

Modified test fixture to reduce ambiguity in pytests.
Re-ran tests on file to ensure pytests are still passing.

Updated test_auth fixture name to mock_zmq_credential to reduce ambiguity

---

.github/workflows/pytest-dbutils-backup_db.yml
.github/workflows/pytest-dbutils-influxdbfuncts.yml
.github/workflows/pytest-dbutils-mysqlfuncts.yml
.github/workflows/pytest-dbutils-postgresqlfuncts.yml
.github/workflows/pytest-dbutils-sqlitefuncts.yml
.github/workflows/pytest-dbutils-timescaldbfuncts.yml
.github/workflows/pytest-testutils.yml
.github/workflows/pytest-vctl.yml
.github/workflows/pytest-web.yml
README.md
services/core/PlatformDriverAgent/tests/test_dnp3_driver.py
volttrontesting/platform/dbutils/test_mongoutils.py
volttrontesting/platform/dbutils/test_mysqlfuncts.py
volttrontesting/platform/dbutils/test_postgresql_timescaledb.py
volttrontesting/platform/dbutils/test_postgresqlfuncts.py

* Refactors integ tests for mysqlfuncts, postgresqlfuncts, and timescaledb to use one container as the test db container instead of creating a new container for every tests, significantly reduces testing time (e.g. for postgresqlfuncts on one image, test completion went from 10m 45seconds to 49 seconds when run locally on a VM. 
* Adds GH Workflows for postgresql and mysqlfuncts
* Adds pytest skip for DNP3 Driver test, which is unsupported
Tested alll tests locally on my machine. Used the following commands:
```shell
pytest  ~/volttron/volttrontesting/platform/dbutils/test_mysqlfuncts.py
pytest  ~/volttron/volttrontesting/platform/dbutils/test_postgresqlfuncts.py
pytest  ~/volttron/volttrontesting/platform/dbutils/test_timescaledbfuncts.py
pytest pytest …
```

Change test setup  and add GH Workflows for mysqlfunct, postgresqlfuncts; update DNP3 tests

---

.github/workflows/pytest-dbutils-backup_db.yml
.github/workflows/pytest-dbutils-influxdbfuncts.yml
.github/workflows/pytest-dbutils-mysqlfuncts.yml
.github/workflows/pytest-dbutils-postgresqlfuncts.yml
.github/workflows/pytest-dbutils-sqlitefuncts.yml
.github/workflows/pytest-dbutils-timescaldbfuncts.yml

For the GitHub Workflows that run the dbutils tests, the workflow step, Archive test results, shows the following warning:
```
Warning: No files were found with the provided path: output/test-test_postgresql_timescaledb.py-ubuntu-20.04-3.6-results.xml. No artifacts will be uploaded.
```
Note that even though the Workflows UI shows all green checkmarks, the warnings are highlighted in the 'annotations' section in the Workflow Summary page. 
The cause of the problem is that the 'test_output_suffix' parameter in the 'Run pytest on...' test is incorrectly configured. That parameter must match the output suffix used in the step, 'Archive test results'. 
Tested the affected Workflows on my personal GH account. Checked the summary page and ensured that the warning did not show up and that the …

Change output_suffix in build-action step

---

volttron/platform/update_auth_file.py
volttron/platform/vip/agent/subsystems/auth.py
volttrontesting/platform/auth_tests/test_auth_file.py

Added volttron-update-auth to upgrade older auth files. This will include the identity field in each auth entry so long as the agent is installed on the platform. The command uses the publickey of the agent to map the identity from the installed agent's directory to the auth entry. This command must be run locally. Once this is done, the agent can use dynamic rpc authorizations.
Allows backwards compatibility for dynamic rpc authorization. 
Prevents the "Auth entry not found for <agent_id>: rpc_method_authorizations not updated" from occurring unexpectedly.
Verified that by running the command, empty/missing identity fields for existing installed agents were added.

Added volttron-update-auth

---

README.md
docs/source/volttron-topics/change-log/upgrading-versions.rst
volttrontesting/platform/auth_tests/test_auth_control.py

Added note about required steps to upgrade to version 8.x, by running volttron-update-auth.
This was added to the README and the upgrading-version.rst doc file.
Updated test_auth_control.py to be more robust.
Ran test_auth_control.py locally twice to verify passing.

Added VOLTTRON 8.x Update Message to README

---

bootstrap.py
requirements.py
scripts/rabbit_dependencies.sh

Pin 7.x release branches requirements.
Tests:
- Installed all optional requirements
- Ran through vcfg without issue on http with vc, vcp, master driver, and listener
- python 3.6.13

Pin 7.x branch #2795

---

services/core/DNP3Agent/dnp3/mesa/functions.py
volttron/platform/messaging/socket.py

From #2472: "Importing ABC directly from collections has been deprecated and will be removed in Python 3.10". This PR changes all deprecated uses of importing ABC's directly from collections in favor of 'collections.abc".
For details, see https://docs.python.org/3/library/collections.abc.html
Fixes #2472 

Change importing abstract base classes from collections to collections.abc

---

services/contrib/PrometheusScrapeAgent/prometheus_scrape/agent.py
services/core/Darksky/darksky/agent.py
services/core/PlatformDriverAgent/platform_driver/interfaces/modbus_tk/maps/__init__.py
services/core/WeatherDotGov/weatherdotgov/agent.py
services/unsupported/MongodbHistorian/mongodb/historian.py
volttron/platform/agent/base_tagging.py
volttron/platform/dbutils/influxdbutils.py
volttron/platform/dbutils/mysqlfuncts.py
volttron/utils/__init__.py
volttrontesting/platform/auth_tests/test_auth_control.py
volttrontesting/services/aggregate_historian/test_aggregate_historian.py
volttrontesting/services/historian/test_historian.py

Starting with Python 3.6, invalid escape sequences in string literals are now deprecated[1]. Automatic style checkers such as flake8 will complains about invalid escape sequences (W605)[2].
[1] https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior
[2] https://www.flake8rules.com/rules/W605.html
Ran flake8 on specific directories to catch all valid W605 warnings. 
```shell
$ flake8 --select W605 examples integrations scripts services volttron volttron_data volttrontesting bootstrap.py
```

Fix all W605 invalid escape sequence warnings

---

scripts/install-agent.py

Update to install-agents script to ensure return codes from subprocesses make it back to the script return. Should resolve #2829

return subprocess returncodes

---

volttron/platform/agent/utils.py

Fixes issue where volttron.platform.agent.utils.load_config can return None when the agent config file is empty, potentially causing agent installation to fail.

Fix bug in load_config

---

docs/source/conf.py
services/core/VolttronCentral/tests/test_webapi.py
services/core/VolttronCentralPlatform/vcplatform/agent.py
services/core/VolttronCentralPlatform/vcplatform/vcconnection.py
volttron/platform/__init__.py
volttron/platform/control.py
volttron/platform/install_agents.py

There was a bug in VOLTTRON Central, preventing agents from being installed properly from the interface. This was caused by the updated install agent functionality removing the method called by VCP (VOLTTRON Central Platform). To fix, VCP now uses the same functionality that Control Services uses, with a client-server structure for installing the agent.
Fixes #2841
- Tested through manual set up of a VC and VCP instance on a local machine, and verified that a packaged listener agent could be installed, started, stopped, and removed. 
- Tested by creating a separate instance of VOLTTRON on the same machine, and remotely connecting to the VC instance. Verified that a packaged listener agent could be installed, started, stopped, and removed on this remote instance through the VC interface.

Fix VCP Install Agent Bug (hotfix 8.1.3)

---

volttron/platform/instance_setup.py

Updated vcfg to check volttron config file for a predefined messagebus.
Vcfg will default to zmq if no message-bus is set in volttron config.
Tested vcfg when a specific message-bus already exists.
Ran instance_setup pytests.

VOLTTRON-cfg Default Message-bus

---

volttron/platform/aip.py
volttrontesting/platform/control_tests/test_control.py

Corrected missing validation of priority in aip.py:priortize_agent. Added tests for valid uuid and priority input to test_control.py.
- Tested in ipython & with vui API.
Added tests to volttrontesting/platform/control_tests/test_control.py:
- 2 of 9 cases for this test xfail due to existing issue: both bytes calls in prioritize_agent method fail with TypeError('string argument without an encoding') when the uuid or priority is not a string. This preempts the intended TypeError from prioritize_agent. Note that the same pattern appears many other places in 9 other places in the …

prioritize_agent validation fix

---

volttron/platform/vip/socket.py

Under the function socket.bind(), the function will raise the following message on ZMQError:
> Attempted to bind Volttron to already bound address {}, stopping
However, according to @jak42: "[T]his message is misleading as the error can occur if, for example ZMQ is asked to open a socket on an IP address which is not bound to the container/instance/machine." For details, see #2885. 
This PR updates that error message to provide the error number to help the user root cause the error. The patch was provided courtesy of @jak42.
The new errror message would look like the following:
> Attempt to bind ZMQ socket to address: {} Returned socket error code: {}, exiting.
Fixes #2885 

Update error msg on ZMQError in socket.bind()

---

start-volttron

- Double quote variables https://github.com/koalaman/shellcheck/wiki/SC2086
- Use new command substitution https://github.com/koalaman/shellcheck/wiki/SC2006
Clean up start-volttron to use best practices and prevent potential issues.

Cleanup start-volttron

---

examples/ConfigActuation/README.md

Added a README for the ConfigActuation example agent. Tested that I am able to run the agent.
This is a part of Jira ticket [VOLTDEV-143](https://jira.pnnl.gov/jira/browse/VOLTDEV-143) but does not close the ticket. 
Looked through code and tested that I could run the example agent.

Add README for ConfigActuation example agent

---

docs/source/agent-framework/core-service-agents/platform-driver/platform-driver-agent.rst

Hot fix documentation typo/sphinx syntax error
In volttron/docs/source/agent-framework/core-service-agents/platform-driver/platform-driver-agent.rst
Fixes #2940 2940

hot fix sphinx ref syntax error

---

volttron/platform/agent/utils.py

Added a ValueError that is raised in load_config when the config_path does not exist. 
Fixes #2847 
Tried installing some example agents with an agent config path that does not exist and was given an error. The error that is displayed is thrown in the install_agent_directory function which runs before we reach the load_config function so we don't see the load_config error.

AGENT_CONFIG not existing should be an error

---

docs/source/deploying-volttron/single-machine.rst

Fixes #2942 
- command line: `cp <some_file> configs/` (using the original file name) missing `/`
- cp services/core/PlatformDriverAgent/platform-driver.agent configs/
- cp services/core/SQLHistorian/config.sqlite configs/
- cp examples/configurations/drivers/fake.config configs/
- cp examples/configurations/drivers/fake.csv configs/
- Add `mkdir configs`. (To make the instruction completed.)
- Modified …

hot fix CLI command error, sphinx syntax error

---

bootstrap.py
docs/source/deploying-volttron/bootstrap-process.rst

Removed the --upgrade option from bootstrap.py. This is now the default behavior.
Fixes #2984
Ran bootstrap.py without --upgrade option, and verified that it called pip --upgrade on all packages. Pinned packages were skipped.

Bootstrap upgrade always

---

README.md
docs/source/agent-framework/web-framework.rst
docs/source/index.rst
docs/source/platform-features/web-api/introduction.rst
docs/source/platform-features/web-api/platform-endpoints.rst
docs/source/platform-features/web-api/platforms/agent-endpoints.rst
docs/source/platform-features/web-api/platforms/agents/config-endpoints.rst
docs/source/platform-features/web-api/platforms/agents/enabled-endpoints.rst
docs/source/platform-features/web-api/platforms/agents/health-endpoints.rst
docs/source/platform-features/web-api/platforms/agents/rpc-endpoints.rst
docs/source/platform-features/web-api/platforms/agents/running-endpoints.rst
docs/source/platform-features/web-api/platforms/agents/status-endpoints.rst
docs/source/platform-features/web-api/platforms/agents/tag-endpoints.rst
docs/source/platform-features/web-api/platforms/device-endpoints.rst

Added link in index.rst for web-api documentation.
#2983
make html, then pull up in browser. Currently, this has the top-level link to the web-api documentation, but does not expand the menu on the left with sub-topics.
* Hardware:
* Toolchain:
* SDK:

Added toctree link to web-api documentation.

---

volttron/platform/control/control_parser.py
volttron/platform/control/control_utils.py
volttrontesting/platform/control_tests/test_vctl_commands.py

This PR is a cherry-pick of PR: https://github.com/VOLTTRON/volttron/pull/2882/files
#2882 should have gotten merged into develop. However, during the control refactoring work, this change on control.py didn't make it into the refactoring. Oddly, the tests for --all-tagged did make it into develop. 
Tests pending....

Add --all-tagged option back 

---

services/core/PlatformDriverAgent/tests/test_global_override.py

The test, test_global_override.py, cannot run because its test fixture, the config store, does not get created during test setup. 
This PR refactors the test setup that removes the config store test fixture; instead, the refactor simplifies the test setup by using a test agent to manage the config store of the volttron instance. 
Ubuntu 20.04, Python 3.8.10
```
pytest test_global_override.py
22 passed, 11 skipped in 369.49s (0:06:09)
```

Refactor PlatformDriver test

---

volttrontesting/platform/dbutils/test_sqlitefuncts.py

The expected output for `test_create_aggregate_store` could vary because the [PRAGMA  index_list](https://www.sqlite.org/pragma.html#pragma_index_list) statement is producing different outputs depending on what machine is being used to run the test.
I ran this test on Centos 7.0 and saw that `test_create_aggregate_store` failed because the actual output did not match the expected output. This test makes a PRAGMA statement to get a list of indexes and then compares that list to the expected list. When this test is run on Ubutntu, the PRAGMA statement returns `["0|idx_AVG_1984|0|c|0", "1|sqlite_autoindex_AVG_1984_1|1|u|0"]`, but on Centos 7.0, it returns `['0|idx_AVG_1984|0', '1|sqlite_autoindex_AVG_1984_1|1']`. To ensure that tests can run on both flavors of Linux, this PR modifies the …

Modify expected output

---

examples/DataPublisher/README.rst

Small updates to README.
This change is a documentation update
Ran a Listener agent with the DataPublisher agent and checked the volttron.log file to see that the data was being published to the message bus

DataPublisher example agent

---

docs/source/agent-framework/historian-agents/sql-historian/sql-historian.rst
docs/source/deploying-volttron/platform-configuration.rst
docs/source/deploying-volttron/secure-deployment-considerations.rst
docs/source/platform-features/control/platform-commands.rst
docs/source/platform-features/security/agent-isolation-mode.rst
docs/source/platform-features/security/volttron-security.rst
scripts/secure_stop_agent.sh
scripts/secure_user_permissions.sh
scripts/stop_agent_running_in_isolation.sh
services/ops/TopicWatcher/tests/test_topic_watcher.py
volttron/platform/agent/base_historian.py
volttron/platform/agent/utils.py
volttron/platform/aip.py
volttron/platform/auth/auth_protocols/auth_rmq.py
volttron/platform/auth/certs.py
volttron/platform/instance_setup.py
volttron/platform/main.py
volttron/platform/store.py
volttron/platform/upgrade/rename_config_for_agent_isolation.py
volttron/platform/vip/agent/utils.py
volttrontesting/fixtures/rmq_test_setup.py
volttrontesting/fixtures/volttron_platform_fixtures.py
volttrontesting/platform/security/test_aip_security.py
volttrontesting/utils/platformwrapper.py

Fixes issue #3035 
Fixes:
Updated config parameter name to agent-isolation-mode
Updated all code variables from secure_agent_users to agent_isolation_mode
Updated all documents to use agent isolation mode instead of secure mode. 
Updated volttron-upgrade command to look for "secure-agent-users" parameter in volttron config and replace it with "agent-isolation-mode" if param exists
Tested by run pytests, setup script and upgrade script. Build rst docs locally to verify links to renamed documents

Renamed secure mode to agent isolation mode - fix for #3035

---

.github/workflows/code_analysis.yml

v1 will be deprecated in 2022-12
https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/

Update CodeQL to v2

---

volttron/platform/agent/utils.py
volttron/platform/auth/auth.py
volttron/platform/main.py
volttron/platform/vip/agent/core.py
volttron/platform/vip/pubsubservice.py

This PR includes updates to the logger as well as improvements in the way the watchers work.  Files that were modified also were reformatted, though I tried to keep the reformatting as different commits than the true changes.
Fixes #3307
Tested on my branch and develop using python 3.8 on ubuntu 20.04

fix auth loops

---

services/core/DNP3Agent/dnp3/mesa/conversion.py
services/core/DNP3Agent/dnp3/mesa/functions.py
services/core/DNP3Agent/tests/test_mesa_agent.py
services/core/PlatformDriverAgent/platform_driver/interfaces/modbus_tk/config_cmd.py
services/core/PlatformDriverAgent/platform_driver/interfaces/modbus_tk/maps/__init__.py
volttron/platform/main.py

Replaces yaml.load(file) with yaml.safe_load(file). This is necessary for yaml 6.0 compatability, and also closes a possible code injection possiblity.
Fixes # 3100
Tests for the modbus_tk driver have been run manually, and work after the change.

Updaed yaml.load(file) to yaml.safe_load(file).

---

bootstrap.py

Reverts VOLTTRON/volttron#3094
This doesn't work with python 3.10 because inside the virtual environment created by bootstrap.py the default pip version is the older 22.0.2 and when install is done within this virtual environment pip commands fail with no such option "--config-settings"

Revert "Pip fix"

---

volttron/platform/__init__.py

adds check for is_auth_enabled before building connection string

Fix for issue #3099

---

examples/EnergyPlusAgent/energyplus/agent.py
examples/EnergyPlusAgent/ep_building1.config
examples/EnergyPlusAgent/ep_building1.yml
integrations/energyplus_integration.py

Backport of changes to modular EnergyPlusAgent. 
* Allows this code to work with configuration files of the style supported by the version of the agent in volttron-pnnl-applications (inputs and outputs may now be dict of dicts or list of dicts).
* Updates json configuration to current property names and makes file locations consistent in both configuration files.
* Fixes assignment to an object variable in the agent which is actually part of the integration class.
Agent was installed and started using both json and yaml configuration files packaged with the agent.  It was confirmed to run and generate periodic publishes for both configurations.

Updates to Energy Plus Agent

---

volttron/platform/control/control_utils.py

Hot fix: uuid has extra char when using vctl status
Before
```
kefei@ubuntu-22:~/project/volttron$ vctl install examples/ListenerAgent --tag listener
Agent 6e4546f6-2c28-4830-9fab-973097f12ebc installed
kefei@ubuntu-22:~/project/volttron$ vctl status
UUID AGENT             IDENTITY            TAG      STATUS          HEALTH
6 listeneragent-3.3 listeneragent-3.3_1 listener                 
kefei@ubuntu-22:~/project/volttron$ vctl install examples/ListenerAgent --tag listener2
Agent 85c28535-46a1-49e2-8abd-c89c1450e11e installed
kefei@ubuntu-22:~/project/volttron$ vctl status
UUID AGENT             IDENTITY            TAG       STATUS          HEALTH
6e4546 listeneragent-3.3 listeneragent-3.3_1 listener                  
85c285 listeneragent-3.3 listeneragent-3.3_2 listener2   
```
After …

revivied Craig s code to resolved the issue that uuid has extra char when using vctl status

---

docs/source/deploying-volttron/platform-configuration.rst
volttron/platform/agent/utils.py
volttron/platform/instance_setup.py
volttrontesting/platform/test_vcfg_config_update.py

Added ability to add multiple agent configurations to configuration store using vcfg update-config-store command. This can be run when VOLTTRON is not running.  One part of feature request #3121 
This feature is very useful for automated deployment use cases where we auto generate multiple agent configurations before we deploy a VOLTTRON instance. 
- Manual testing with platform driver, economizer and ilc agent configurations and configuration metadata generated for intellimation 
- Unit test cases in volttrontesting/platform/test_vcfg_config_update.py

Fix for - #3121 - vcfg command to set multiple configuration-store entries at a time

---

docs/source/agent-framework/driver-framework/home-assistant/HomeAssistantDriver.rst
services/core/PlatformDriverAgent/platform_driver/interfaces/home_assistant.py
services/core/PlatformDriverAgent/tests/test_home_assistant.py

Previously, home assistant tests required the use of a light entity. Considering not everyone has smart lights or the time to create a fake one, input_boolean controls have been implemented into the tests. This makes it much easier to run tests with a fresh installation of home assistant. 
To test the home assistant tests. You need your IP, Access token, and port from home assistant. You also need to create a input_boolean entity by going to Settings > Devices & services > Helpers > Create Helper > Toggle within home assistant. Name this toggle volttrontest. Once you have done that, you can run the pytest with pytest volttron/services/core/PlatformDriverAgent/tests/test_home_assistant.py.

Fixed home assistant tests

---

volttrontesting/fixtures/volttron_platform_fixtures.py
volttrontesting/utils/build_agent.py

* Hardware:
* Toolchain:
* SDK:

don't import agent into the global space for tests.

---

volttron/platform/instance_setup.py

work around for issue #3154

---

bootstrap.py
requirements.py

fix for pip's deprecated --install-options issue.  We now use the latest 24.0 version of pip inside the virtual environment created by bootstrap.  Tested the change on Ubunu 20 + python 3.8 and Ubuntu 22 +python 3.10. In both the case volttron bootstraps, starts and vctl install, vctl status, vctl start, vctl stop works fine

fix for issue#3159 (fix for deprecated pip --install-options)

---

volttrontesting/services/historian/test_historian.py

Handling gevent time out in test case that makes rpc calls to non existent vip-id.  
With this change, sqlite, postgresql, and mysql test cases pass

handled timeout on test_historian.py

---

volttron/platform/main.py
volttron/platform/vip/agent/subsystems/rpc.py
volttrontesting/platform/auth_tests/test_auth_control.py
volttrontesting/platform/auth_tests/test_auth_group_roles.py
volttrontesting/platform/auth_tests/test_auth_integration.py
volttrontesting/utils/platformwrapper.py

Fix and test case for issue #3168

Fix for security issue #3168

---

docs/source/conf.py
services/core/PlatformDriverAgent/platform_driver/driver.py
volttron/platform/__init__.py
volttron/platform/vip/agent/subsystems/auth.py
volttron/platform/web/admin_endpoints.py
volttron/platform/web/topic_tree.py

Provides better handling of case where there are missing or duplicate registry entries both for driver, when it is loading configurations, and in the web API when it is building a TopicTree from the driver configurations.
#3183
Started driver with test configurations which are missing registry entries and which have duplicated point names.  Observed that correct warnings appeared in log. Navigated through vui/platforms/.../devices endpoints in browser. Found correct devices and points without errors.  Confirmed that log receives notice of duplicate points when building TopicTree.

Handle duplicate point names

---

services/core/ActuatorAgent/actuator/agent.py
services/core/ActuatorAgent/actuator/scheduler.py
services/core/PlatformDriverAgent/platform_driver/agent.py
services/core/PlatformDriverAgent/platform_driver/interfaces/bacnet.py

Fixes for actuator schedule requests and exception handling in driver agent related to BACnet ping and heartbeat signals.
- [ x I have performed a self-review of my own code

Actuator and driver agent fixes

---

services/core/PlatformDriverAgent/platform_driver/interfaces/bacnet.py

Replaced and extended broken functionality to get_priortity_array on get_point. Added ability to set different properties on points than are configured in registry.
Has been tested by getting and setting additional properties on real bacnet devices.

Added on_property method to get_point and set_point.

---

services/core/PlatformDriverAgent/platform_driver/interfaces/chargepoint/README.rst
services/core/PlatformDriverAgent/platform_driver/interfaces/chargepoint/__init__.py
services/core/PlatformDriverAgent/platform_driver/interfaces/chargepoint/async_service.py
services/core/PlatformDriverAgent/platform_driver/interfaces/chargepoint/credential_check.py
services/core/PlatformDriverAgent/platform_driver/interfaces/chargepoint/requirements.txt
services/core/PlatformDriverAgent/platform_driver/interfaces/chargepoint/service.py
update_scripts/update.driver

Replace "suds" library to "zeep" library for the ChargePoint interface since the previous library is less actively maintained.
**To Test**
1. Get the API key and password from ChargePoint cloud
2. Prepare the registration configuration file 
* Ubuntu 22.04
* Python 3.10

ChargePoint interface upgrade

---

services/ops/EmailerAgent/emailer/agent.py

Added more error logging in the emailer agent to help users understand what went wrong. 

added more logging

---

requirements.py
services/core/PlatformDriverAgent/platform_driver/interfaces/__init__.py

The device_path is passed from the DriverAgent to the Inteface on initialization, but was not being saved. It is a required argument to BACnetProxy RPC "create_cov_subscription." Added self.device_path variable in BaseInterface.
Fixes #2484
This has been tested on real hardware.

Fixed missing Interface attribute required for BACnet COV.

---

requirements.py

The watchdog package added a requirement for keyword arguments in version 5.0.0. The current version watchdog is 6.0.0, so new environments will fail when the VolttronHomeFileReloader or AbsolutePathFileReloader are used. This affects the web API on startup, since VolttronHomeFileReloaders is used for web-users.json.
Unfortunately, simply updating to use keyword arguments also broke other things when running on python 3.8, as watchdog removed support for python 3.8 in the same version. Instead, pinned watchdog version to less than 5.0.0, since we need to continue support for python 3.8.
Fixes #3200
Started Volttron with and without the change while a bind-web-address was set. The error described in #3200 is present without the fix and no longer …

Pinned watchdog to less than version 5.

---

requirements.py
services/core/PlatformDriverAgent/platform_driver/driver.py

Try blocks are added to avoid breaking the DriverAgent instance for a device if an RPC method is called before the onstart runs for the DriverAgent.  This is necessary because the interface is not ready at the time the RPC arrives. Checking for readiness, meanwhile, would add overhead to every read and write, when this can only happen in the first second or two after creating the device. Instead, we avoid the problem by catching the AttributeError and simply logging that this has happened.
#3202

Driver rpc tries

---

docs/source/platform-features/web-api/introduction.rst

Clarified, in documentation, agents required to utilize the devices endpoints within the RESTful API.
Fixes # 3204

API docs update
