VOLTTRON/volttron

Agents/HelloAgent/config1, Agents/HelloAgent/hello/agent.py, Agents/PlatformAgent/platformagent/agent.py, Agents/PlatformManagerAgent/platformmanager/agent.py, volttron/platform/agent/vipagent.py
environment VIP_ADDR or extrapolated from VOLTRON_HOME.  Also, added the
check for linux.
This should take care of #40.
Please look at this @hashstat @jhaack @timothykang
=> Made changes to vipagent.py such that vip_address is taken from envornment

Agents/PlatformAgent/platformagent/agent.py
This is a timing issue I believe.
=> fixed issue #124 by adding a wait before the periodic starts

Agents/VolttronCentralAgent/ui-src/js/components/line-chart.jsx, Agents/VolttronCentralAgent/volttroncentral/webroot/index.html, Agents/VolttronCentralAgent/volttroncentral/webroot/js/app-36d69177.js
=> Fix tooltip date format (d = day of week, D = day of month)

examples/DataPublisher/datapublisher/publisher3.py, examples/SimpleForwarder/forwarder.config
Adds feature to the dataplayback agent to allow it to fast forward to wherever it was if the agent is interrupted. #192.
=> Data Playback Enhancement

volttron/platform/control.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/271)
=> Add agent restart to volttron-ctl. Closes #270

services/core/MongodbHistorian/mongodb/historian.py
This change allows the user to specify multiple ip/hostname port combinations in order to take advantage of the replecaset's abilities.  This replaces #262's fix in that replecaset is not used any longer in the config file.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/292)
=> Added the ability to connect mongo to replicaset through ip addresses

requirements.txt
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/363)
=> Fixes #226

services/core/MongodbHistorian/mongodb/historian.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/408)
=> Update mongo to behave more like sqlhistorians

volttron/platform/auth.py, volttrontesting/fixtures/volttron_platform_fixtures.py, volttrontesting/platform/auth_file_test.py, volttrontesting/utils/platformwrapper.py
Conflicts:
volttrontesting/fixtures/volttron_platform_fixtures.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/410)
=> Fixes: #409 Auth now allows overwriting of credentials.

services/core/ForwardHistorian/forwarder/agent.py, services/core/ForwardHistorian/tests/test_forward_historian.py, volttron/platform/agent/base_historian.py, volttron/platform/agent/parser.out, volttron/platform/agent/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/411)
=> Fixed forwardhistoan and added a test method for it

services/core/SQLHistorian/sqlhistorian/db/basedb.py, services/core/SQLHistorian/sqlhistorian/historian.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/412)
=> fix historian bug and cleanup #386

volttrontesting/platform/auth_test.py, volttrontesting/utils/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/421)
=> moved poll_gevent_sleep into volttrontesting/utils/utils.py

services/core/EmailerAgent/emailer.config, services/core/EmailerAgent/emailer/agent.py, volttron/platform/messaging/health.py, volttron/platform/messaging/topics.py, volttron/platform/vip/agent/subsystems/health.py, volttrontesting/subsystems/test_health_subsystem.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/447)
=> Feature/emailer #275

scripts/core/pack_install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/460)
=> Remove newlines from package result

volttron/platform/keystore.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/470)
=> create keystores with file permissions set to 0660, fixes #392

docs/source/roadmap/3.0-to-3.5-Migration.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/484)
=> Add 3.5 migration doc

services/core/VolttronCentral/volttroncentral/agent.py, services/core/VolttronCentralPlatform/vcplatform/agent.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/524)
=> bugfix #509 If there isn't any topics to replace.

services/core/MasterDriverAgent/master_driver/test_fake.csv, services/core/MasterDriverAgent/master_driver/test_fakedriver.config, services/core/VolttronCentral/tests/test_webapi.py, services/core/VolttronCentral/ui-src/css/app.css, services/core/VolttronCentral/ui-src/js/action-creators/platform-action-creators.js, services/core/VolttronCentral/ui-src/js/action-creators/platform-chart-action-creators.js, services/core/VolttronCentral/ui-src/js/action-creators/platforms-panel-action-creators.js, services/core/VolttronCentral/ui-src/js/app.jsx, services/core/VolttronCentral/ui-src/js/components/dashboard.jsx, services/core/VolttronCentral/ui-src/js/components/navigation.jsx, services/core/VolttronCentral/ui-src/js/components/platform-chart.jsx, services/core/VolttronCentral/ui-src/js/components/platforms-panel-item.jsx, services/core/VolttronCentral/ui-src/js/components/platforms-panel.jsx, services/core/VolttronCentral/ui-src/js/constants/action-types.js, services/core/VolttronCentral/ui-src/js/stores/platform-chart-store.js, services/core/VolttronCentral/ui-src/js/stores/platforms-panel-items-store.js, services/core/VolttronCentral/ui-src/js/stores/platforms-panel-store.js, services/core/VolttronCentral/ui-src/js/stores/platforms-store.js, services/core/VolttronCentral/volttroncentral/webroot/css/app-7b8ad1ab.css, services/core/VolttronCentral/volttroncentral/webroot/index.html, services/core/VolttronCentral/volttroncentral/webroot/js/app-afd92889.js, services/core/VolttronCentral/volttroncentral/webroot/new-register.html, services/core/VolttronCentralPlatform/vcplatform/agent.py, volttron/platform/web.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/574)
=> Merge from release/3.5rc1 back into develop

volttron/platform/agent/base_historian.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/585)
=> clear successful published in base historian

volttron/platform/agent/base_historian.py
I missed this when I was reverting the historian stuff.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/596)
=> Added back in the removal of successful published.

volttron/platform/agent/base_historian.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/597)
=> Added back in the removal of successful published. (#596)

bootstrap.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/602)
=> virtualenv url has changed.

bootstrap.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/603)
=> Fix for virtualenv url change #600

applications/pnnl/AirsideRCxAgent/airside/airside_retuning_rcx.py, applications/pnnl/AirsideRCxAgent/airside/diagnostics/common.py, applications/pnnl/AirsideRCxAgent/airside/diagnostics/reset_sched_rcx.py, applications/pnnl/AirsideRCxAgent/airside/diagnostics/satemp_rcx.py, applications/pnnl/AirsideRCxAgent/airside/diagnostics/stcpr_rcx.py, applications/pnnl/AirsideRCxAgent/airside/drivenagent.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/608)
=> Reduce redundant data storage (publishing to bus) to historian.

services/core/VolttronCentral/ui-src/css/app.css, services/core/VolttronCentral/ui-src/js/components/navigation.jsx, services/core/VolttronCentral/volttroncentral/webroot/css/app-d2abefe4.css, services/core/VolttronCentral/volttroncentral/webroot/index.html, services/core/VolttronCentral/volttroncentral/webroot/js/app-8f81ceb4.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/621)
=> Added funding info to login page.

volttron/platform/control.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/623)
=> simplify restart agent control method

services/core/VolttronCentral/ui-src/css/app.css, services/core/VolttronCentral/volttroncentral/webroot/css/app-a2cc9424.css, services/core/VolttronCentral/volttroncentral/webroot/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/627)
=> task #620 Adjusted spacing and added more font options.

docs/source/contributing.rst
This should be all that is necessary to follow the new paradigm for forking and stuff.  To see the page in action you can view at http://craig8-demo.readthedocs.io/en/releases-3.5rc1/contributing.html which is built by my readthedocs site.
If you want to edit this before pulling you can pull from my repo using 
````
git remote add craigs https://github.com/craig8/volttron
git pull craigs releases/3.5rc1
````
Make sure you are in a "clean" branch based upon the VOLTTRON releases/3.5rc1 branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/657)
=> Added contributing.rst file

examples/CAgent/c_agent/agent.py, examples/CAgent/c_agent/cdriver.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/663)
=> fix c agent documentation errors

services/core/MasterDriverAgent/master_driver/interfaces/universal.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/662)
=> update to universal.py

services/core/SysMonAgent/tests/test_sysmonagent.py, services/core/ThresholdDetectionAgent/tests/test_thresholddetection.py, services/core/ThresholdDetectionAgent/thresholddetection/agent.py, volttrontesting/utils/platformwrapper.py
Also added `agent_class` parameter to `PlatformWrapper.build_agent` in order to build custom agents in tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/658)
=> Added tests for SysmonAgent and ThresholdDetectionAgent

scripts/core/make-agent.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/677)
=> Fixed #652 Check for volttron/platform directory now

services/core/VolttronCentralPlatform/vcplatform/agent.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/686)
=> Added protection for not being connected to vc.

docs/source/install.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/685)
=> meeting not workshop

docs/source/install.rst, volttron/platform/main.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/687)
=> minor fixes in documentation and output from main script

Dockerfile
renaming user to more common
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/688)
=> fixing home directory permissions, adding nano

volttron/platform/main.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/695)
=> Fix zmq bind collision in router #692

scripts/bacnet/grab_bacnet_config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/694)
=> Improvements to bacnet config grabber

scripts/bacnet/grab_bacnet_config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/701)
=> Added cherry picked items to releases/3.5rc1

volttron/platform/auth.py, volttron/platform/vip/agent/core.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/702)
=> add exception to set auth event before router is started

docs/source/core_services/drivers/Driver-Configuration.rst, volttron/platform/control.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/705)
=> Add identity to status and list commands.

docs/source/specifications/agent-vip-id.rst, examples/AlertMonitor/alertmonitor/agent.py, examples/Alerter/alerter/agent.py, services/core/ActuatorAgent/actuator/agent.py, services/core/BACnetProxy/bacnet_proxy/agent.py, services/core/EmailerAgent/emailer/agent.py, services/core/ForwardHistorian/forwarder/agent.py, services/core/MasterDriverAgent/master_driver/agent.py, services/core/MongodbHistorian/mongodb/historian.py, services/core/OpenEISHistorian/openeis/historian.py, services/core/SQLHistorian/sqlhistorian/historian.py, services/core/SysMonAgent/sysmon/agent.py, services/core/ThresholdDetectionAgent/thresholddetection/agent.py, services/core/VolttronCentral/tests/test_webapi.py, services/core/VolttronCentral/volttroncentral/agent.py, services/core/VolttronCentralPlatform/tests/test_platformagent.py, services/core/VolttronCentralPlatform/vcplatform/agent.py, volttron/platform/agent/utils.py, volttron/platform/main.py, volttron/platform/vip/agent/core.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/706)
=> Moved AGENT_VIP_IDENTITY evaluation to vip_main.

services/core/AlertAgent/alerter/agent.py, services/core/AlertAgent/config, services/core/AlertAgent/setup.py, services/core/AlertAgent/tests/test_alert_agent.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/708)
=> Alert agent to look for missing device publishes

services/core/AlertAgent/alerter/agent.py, services/core/AlertAgent/config, services/core/AlertAgent/setup.py, services/core/AlertAgent/tests/test_alert_agent.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/709)
=> Alert agent in rc1

services/core/SQLHistorian/config.sqlite.platform.historian, volttron/platform/instance_setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/713)
=> #712 Fixed volttron-cfg to set platform.historian identity on historian

services/core/VolttronCentral/volttroncentral/agent.py, services/core/VolttronCentral/volttroncentral/webroot/api-tests.html, services/core/VolttronCentralPlatform/vcplatform/agent.py
Updated api-tests.html to allow testing of the entires stack.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/714)
=> #711 Fixed issue with calling agent methods on remote platforms

volttron/platform/messaging/topics.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/716)
=> Added missing BACNET topic back

volttron/platform/agent/utils.py
This fix addresses #719
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/720)
=> Added the retrieval of VOLTTRON_HOME to vip_main

services/core/AlertAgent/IDENTITY, services/core/AlertAgent/alerter/agent.py, services/core/AlertAgent/tests/test_alert_agent.py, volttron/platform/agent/known_identities.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/718)
=> Add rpc methods to alerter #710

services/core/MasterDriverAgent/master_driver/interfaces/fakedriver.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/727)
=> Updated fakedriver.py to have more options for configuration

docs/source/specifications/agent-vip-id.rst, volttron/platform/agent/utils.py, volttron/platform/aip.py, volttron/platform/vip/agent/__init__.py, volttrontesting/platform/control_test.py, volttrontesting/testutils/test_identity.py
A follow on pull request #733 
Changed to not throw an error in the Agent class.
Updated documentation to have a better definition of what a VIP IDENTITY is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/734)
=> Restrict identity

volttron/platform/vip/agent/subsystems/configstore.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/739)
=> Improved illegal set and delete call detection. Improved docs.

scripts/bacnet/proxy_grab_bacnet_config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/749)
=> Fixed code path copy paste error.

docs/source/core_services/control/PlatformCommands.rst, volttron/platform/config.py, volttron/platform/instance_setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/735)
=> Refactor volttron-cfg

scripts/admin/volttron.service
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/751)
=> Add example systemd unit file

volttron/platform/control.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/756)
=> let installs skip the channel subsystem for local installs

scripts/bacnet/proxy_grab_bacnet_config.py, scripts/core/pack_install.sh
Modified the pack_install script to take care of the file:// prefix for users.  This helps take care of the last comment on #756.
We need to also figure out why the logging does not work on the function install agent.  See #757
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/758)
=> Fix file in pack install

scripts/core/pack_install.sh, volttron/platform/control.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/759)
=> volttron-ctl direct install if using ipc address

volttron/platform/agent/utils.py
inotify is not supported on OS X/MacOS. This change
catches the library import error and changes watch_file()
to log warning that runtime changes are not supported on
the platform.  In the future, OS X FS Events API could be
used to implement the same functionality on OS X/MacOS.
This has been tested on Ubuntu 14.04 and OS X 10.10.5.
Let me know if you would prefer to handle this platform
dependency in some other way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/768)
=> Disable watch_file() if inotify is not supported on platform.

ci-integration/run-tests.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/772)
=> really fixed the issues with running tests.

volttron/platform/instance_setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/775)
=> quote instance name in volttron-cfg #774

services/core/VolttronCentralPlatform/vcplatform/agent.py, volttron/platform/control.py, volttron/platform/vip/agent/subsystems/channel.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/769)
=> update file transfer over channel subsystem

services/core/FailoverAgent/failover/agent.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/807)
=> failover move changed state check to logging

volttron/platform/instance_setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/813)
=> add port request to volttron-cfg vcp for #798

services/core/VolttronCentralPlatform/vcplatform/agent.py, volttron/platform/control.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/809)
=> remove channel use from platform agent

volttron/platform/agent/base_historian.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/817)
=> Fixes #797

services/core/SQLHistorian/config.sqlite, services/core/SQLHistorian/config.sqlite.platform.historian
#810 Add platform.historian identity back into sqlite platform historian config. Take out bad entry in regular sqlite config.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/812)
=> #810 Fix and update sqlite config files

docs/source/core_services/service_agents/failover/Failover.rst, services/core/FailoverAgent/config, services/core/FailoverAgent/failover/agent.py, services/core/FailoverAgent/setup.py, services/core/FailoverAgent/tests/test_simple_failover.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/823)
=> failover updates

scripts/core/make-agent.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/845)
=> #844 Modified make-agent script to enable a NO_START env variable

examples/StandAloneListener/standalonelistener.py, volttron/platform/vip/agent/__init__.py
Fixed bug in log message in base agent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/829)
=> Fixes #828

volttron/platform/control.py, volttron/platform/keystore.py
closes #851, fixes #838
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/856)
=> Removed --keystore-file and --known-hosts-file from volttron-ctl

scripts/bacnet/proxy_bacnet_scan.py, scripts/bacnet/proxy_grab_bacnet_config.py, scripts/install_master_driver_configs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/864)
=> updated scripts to use KeyStore's public and secret property

docs/source/core_services/drivers/BACnet-Auto-Configuration.rst
Fixes #847
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/860)
=> Fixed bacnet docs.

docs/source/devguides/agent_development/Agent-Development.rst, docs/source/devguides/agent_development/TestAgent.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/866)
=> add config store info to test agent doc

services/core/FailoverAgent/failover/agent.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/859)
=> make failover more optimistic when starting #848

docs/source/devguides/walkthroughs/VOLTTRON-Central-Demo.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/874)
=> make terminal images link to themselves #872

docs/source/devguides/agent_development/Agent-Development.rst, docs/source/devguides/agent_development/TestAgent.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/885)
=> add import to testagent setup, fix logging method #880

scripts/scalability-testing/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/889)
=> Fix scalability scripts docs.

scripts/core/upgrade-agent.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/890)
=> Missed adding config to package.

scripts/core/upgrade-agent.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/892)
=> Use $SOURCE rather than $2 for this script.

docs/source/core_services/control/PlatformCommands.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/897)
=> Docs to address #837

volttron/platform/vip/agent/__init__.py, volttron/platform/vip/agent/connection.py, volttron/platform/vip/agent/core.py
#833
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/906)
=> add reconnect interval option to agents

docs/source/supporting/examples/ListenerAgent.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/910)
=> Fixes for listener agent example documentation

docs/source/supporting/examples/SchedulerExampleAgent.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/913)
=> Update scheduler example agent

services/core/EmailerAgent/emailer/agent.py, services/core/EmailerAgent/tests/send_email.py, volttron/platform/messaging/topics.py, volttron/platform/vip/agent/utils.py
This patch updates the emailer and fixes #911 
Included is a test send email script that when ran will connect and send an email via the alert system as well as through the pubsub system.
Note you must configure the emaileragent correctly for this to happen and have a valid smtp address.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/912)
=> Emailer Update and Fixes

volttron/platform/vip/agent/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/917)
=> Updated Kwargs

docs/source/apidocs.rst, docs/source/conf.py, docs/source/devguides/agent_development/Agent-Development.rst, docs/source/sample_applications/sample-applications.rst, scripts/core/start_historian.sh, scripts/core/start_platform.sh, scripts/historian-scripts/start-historian-mysql.sh, scripts/historian-scripts/start-historian-openeis.sh, scripts/historian-scripts/start-historian-sqlite.sh, scripts/scalability-testing/make-masternode, scripts/scalability-testing/make-modelnode
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/915)
=> Fixes #876

services/core/FailoverAgent/failover/agent.py, services/core/FailoverAgent/setup.py, services/core/FailoverAgent/tests/test_simple_failover.py
for #922
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/924)
=> add version to failover agent.py

services/core/AlertAgent/alerter/agent.py, services/core/ForwardHistorian/forwarder/agent.py, services/core/MasterDriverAgent/master_driver/agent.py, services/core/OpenEISHistorian/openeis/historian.py, services/core/SQLHistorian/sqlhistorian/historian.py
#922 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/928)
=> Several version fixes. #922

docs/source/devguides/setup/Building-VOLTTRON.rst
Addresses #746
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/932)
=> Add warning about running volttron in disowned state.

docs/source/core_services/security/Update-Notes.rst, scripts/update_curve_key.py
* added script to update curve.key to key store, fixes #936
* documented security-related changes, see #939
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/940)
=> Added update-key script and documented security changes

docs/source/supporting/examples/DDSAgent.rst, docs/source/supporting/examples/Example-Agents.rst, examples/DDSAgent/README, examples/DDSAgent/config, examples/DDSAgent/ddsagent/agent.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/927)
=> dds example without library included

services/core/VolttronCentral/volttroncentral/agent.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/953)
=> Missed a place where we checked for platform uuid.

services/core/FailoverAgent/failover/agent.py, services/core/FailoverAgent/tests/test_simple_failover.py
#941 #943
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/954)
=> Failover update

services/core/VolttronCentralPlatform/vcplatform/agent.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/957)
=> Protect against not being able to get to a peer identity

docs/source/devguides/deployment/Deployment-Options.rst, scripts/admin/volttron, scripts/admin/volttron.service
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/959)
=> Add different VOLTTRON_HOME support to deployment docs.

docs/source/devguides/walkthroughs/VOLTTRON-Central-Demo.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/958)
=> Add auth allow all to vc demo

docs/source/core_services/drivers/BACnet-Auto-Configuration.rst, docs/source/core_services/drivers/BACnet-Proxy-Agent.rst, docs/source/core_services/drivers/Driver-Configuration.rst, docs/source/devguides/setup/Building-VOLTTRON.rst, docs/source/specifications/agent-vip-id.rst
-Typos fixed
-Hyperlinks added for vip identity asignment and agent deployment
-Corresponding missing links fixed in driver documentation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/960)
=> fixes for typos and broken links

docs/source/devguides/walkthroughs/VOLTTRON-Central-Demo.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/990)
=> rearrange vc demo doc for clarity #987

volttron/platform/agent/base_historian.py
#978
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/986)
=> remove double all topic in base historian

docs/source/core_services/drivers/Using-Third-Party-Drivers.rst, docs/source/devguides/agent_development/Develop-Driver-Agent.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/981)
=> Docs on how to use third party drivers.

services/core/SQLHistorian/mysql-create.sql, services/core/SQLHistorian/sqlhistorian/historian.py, services/core/SQLHistorian/sqlite-create.sql
Fixes for #991  and  #988
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/999)
=> Historian fixes

docs/source/core_services/service_agents/actuator/ActuatorScheduleRequest.rst
#598
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1006)
=> Mention timezone sensitivity in actuator doc

volttron/platform/vip/socket.py, volttron/platform/web.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/998)
=> print message instead of stack trace on zmq rebind 

pytest.ini, services/core/SQLHistorian/mysql-create.sql, services/core/SQLHistorian/sqlhistorian/historian.py, services/core/SQLHistorian/sqlite-create.sql, volttron/platform/packaging.py, volttrontesting/platform/test_packaging.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1010)
=> Sync some develop code into 4.0.1

services/core/AgentWatcher/config, services/core/AgentWatcher/setup.py, services/core/AgentWatcher/tests/test_agent_watcher.py, services/core/AgentWatcher/watcher/agent.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1011)
=> Agent watcher

README.md, volttron/platform/vip/agent/subsystems/heartbeat.py, volttrontesting/testutils/test_platformwrapper.py
#1014
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1015)
=> remove uuid from heartbeat publishes

services/core/AgentWatcher/config, services/core/AgentWatcher/setup.py, services/core/AgentWatcher/tests/test_agent_watcher.py, services/core/AgentWatcher/watcher/agent.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1012)
=> add agent watcher to 4.0.1

services/core/ForwardHistorian/tests/test_forward_historian.py, services/core/MongodbHistorian/mongodb/historian.py, services/core/MongodbHistorian/tests/test_mongohistorian.py, services/core/SQLHistorian/tests/test_sqlhistorian.py, volttron/platform/dbutils/mysqlfuncts.py, volttron/platform/dbutils/sqlitefuncts.py, volttrontesting/platform/test_packaging.py, volttrontesting/services/historian/test_historian.py
Fix for task #1027 
Also combined sqlhistorian and mongo historian test cases into single historian test case
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1031)
=> Historian query change to make end time exclusive

services/core/AlertAgent/alerter/agent.py, services/core/EmailerAgent/emailer/agent.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1045)
=> Fix alerter

services/core/MasterDriverAgent/master_driver/interfaces/modbus.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1061)
=> Fixes for the Modbus driver.

examples/CAgent/c_agent/driver/cdriver.py, examples/CAgent/c_agent/driver/test_cdriver.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1055)
=> update c driver example to support config store

scripts/scalability-testing/README.md, scripts/scalability-testing/config_builder.py, services/core/ForwardHistorian/tests/test_forwardhistorian.py, volttron/platform/agent/base_historian.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1063)
=> Updated the scalability test script builder.

services/core/ActuatorAgent/actuator/agent.py, services/core/ActuatorAgent/tests/actuator-no-lock.config, services/core/ActuatorAgent/tests/actuator2.config, services/core/ActuatorAgent/tests/test_actuator_rpc.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1069)
=> Added support for no-lock-write mode.

services/core/ForwardHistorian/forwarder/agent.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1081)
=> New fix forward historian

services/core/ForwardHistorian/forwarder/agent.py
This takes care of #1084
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1085)
=> Upstream develop master

docs/source/core_services/service_agents/threshold/ThresholdAgent.rst, docs/source/core_services/service_agents/threshold/index.rst, services/core/ThresholdDetectionAgent/tests/test_thresholddetection.py, services/core/ThresholdDetectionAgent/thresholddetection.config, services/core/ThresholdDetectionAgent/thresholddetection/agent.py
#1057 #982
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1064)
=> Add config store support to Threshold Detection Agent

docs/source/supporting/examples/ConfigActuation.rst, examples/ConfigActuation/config, examples/ConfigActuation/config_actuation/agent.py, examples/ConfigActuation/setup.py, examples/ConfigActuation/tests/test_config_actuation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1090)
=> add example for actuation via configstore update

volttron/platform/instance_setup.py
Log now gets saved to  $VOLTTRON_HOME/volttron.cfg.log
#1087
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1091)
=> volttron-cfg save log

volttron/platform/vip/socket.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1092)
=> add patch for old urlparse

docs/source/core_services/drivers/Driver-Configuration.rst, docs/source/specifications/chargepoint_driver.rst, examples/configurations/drivers/chargepoint.csv, examples/configurations/drivers/chargepoint1.config, examples/configurations/drivers/chargepoint2.config, services/core/MasterDriverAgent/master_driver/interfaces/chargepoint/README.rst, services/core/MasterDriverAgent/master_driver/interfaces/chargepoint/__init__.py, services/core/MasterDriverAgent/master_driver/interfaces/chargepoint/async_service.py, services/core/MasterDriverAgent/master_driver/interfaces/chargepoint/requirements.txt, services/core/MasterDriverAgent/master_driver/interfaces/chargepoint/service.py, services/core/MasterDriverAgent/master_driver/interfaces/chargepoint/tests/TestAgent/install-test-agent.sh, services/core/MasterDriverAgent/master_driver/interfaces/chargepoint/tests/TestAgent/setup.py, services/core/MasterDriverAgent/master_driver/interfaces/chargepoint/tests/TestAgent/testagent.config, services/core/MasterDriverAgent/master_driver/interfaces/chargepoint/tests/TestAgent/tester/agent.py, services/core/MasterDriverAgent/master_driver/interfaces/chargepoint/tests/test_chargepoint_driver.py
The Chargepoint API Driver for VOLTTRON enables real-time monitoring
and control of Chargepoint EVSEs within the VOLTTRON platform
by creating a standard VOLTTRON device driver on top of the
Chargepoint Web Services API.  Each managed chargestation
looks like a standard VOLTTRON device, monitored and controlled
through the VOLTTRON device driver interface. Resolves #994.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1074)
=> Chargepoint API Driver Version 1.0

examples/ConfigActuation/update_config.py, volttron/platform/control.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1096)
=> add configstore update script

services/core/ForwardHistorian/forwarder/agent.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1115)
=> Fix event issue for forwarder see #1107

scripts/bacnet/proxy_grab_bacnet_config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1122)
=> Fixes #1121 hard coded bacnet scripts.

services/core/MasterDriverAgent/master_driver/interfaces/rainforesteagle.py, services/core/MasterDriverAgent/master_driver/test_eagle.json, services/core/MasterDriverAgent/master_driver/test_rainforesteagle.config, services/core/MasterDriverAgent/tests/test_eagle.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1110)
=> Rainforest driver

services/core/VolttronCentral/volttroncentral/agent.py, services/core/VolttronCentral/volttroncentral/platforms.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1139)
=> Fixed to bugs where the backend wasn't properly sending data to the front end for the tree.

docs/source/core_services/service_agents/alerter/AlertAgent.rst, docs/source/core_services/service_agents/alerter/index.rst, services/core/AlertAgent/alerter/agent.py, services/core/AlertAgent/config, services/core/AlertAgent/tests/test_alert_agent.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1083)
=> Add grouping to alert agent

docs/source/specifications/driver-override.rst, services/core/MasterDriverAgent/master_driver/agent.py, services/core/MasterDriverAgent/master_driver/tests/test_global_override.py
1. Created spec for global override
2. Updated master driver to support global override
3. Added associated pytests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1093)
=> Added global override implementation, pytests and specification doc

services/core/ActuatorAgent/actuator/agent.py, services/core/ActuatorAgent/tests/test_actuator_rpc.py, services/core/MasterDriverAgent/master_driver/agent.py, services/core/MasterDriverAgent/master_driver/driver.py, services/core/MasterDriverAgent/master_driver/interfaces/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1133)
=> add get_multiple_points to actuator and master driver

services/core/MasterDriverAgent/master_driver/interfaces/modbus.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1143)
=> Fix for #1128

volttron/platform/dbutils/mysqlfuncts.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1153)
=> backport mysql fix to releases/4.0.1

volttron/platform/dbutils/mysqlfuncts.py
Handles issue #1144
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1152)
=> Superseeds pull request #1145

docs/source/install.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1163)
=> fix incorrect command on install page

services/core/EmailerAgent/emailer.config, volttron/platform/agent/utils.py
#1169 Fix for epoch time issue in utils
Fix Emailer agent config to be valid
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1170)
=> #1169 fix get_utc_seconds_from_epoch to not return the same time

services/core/ActuatorAgent/actuator/agent.py, services/core/ActuatorAgent/tests/test_actuator_rpc.py, services/core/MasterDriverAgent/master_driver/agent.py, services/core/MasterDriverAgent/master_driver/driver.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1149)
=> make scrape_all accessible through rpc

volttron/platform/main.py
An addition to #1167 pull request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1175)
=> #1158 Added volttron-root to ./volttron_instances

docs/source/specifications/message-debugging.rst
Spec for a new message debugging feature, previously submitted for review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1101)
=> Message debugging spec

scripts/bacnet/grab_bacnet_config.py, scripts/bacnet/proxy_grab_bacnet_config.py, services/core/VolttronCentralPlatform/vcplatform/bacnet_proxy_reader.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1201)
=> Handle case where proxy might return none

services/core/DataMover/datamover/agent.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1193)
=> add timeout to datamover #1192

services/core/VolttronCentral/ui-src/js/components/platform-chart.jsx, services/core/VolttronCentral/volttroncentral/webroot/css/app-2079453d0174235ff513.css, services/core/VolttronCentral/volttroncentral/webroot/index.html, services/core/VolttronCentral/volttroncentral/webroot/js/app-2079453d0174235ff513.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1190)
=> Removed commented-out code from platform-chart.

docs/source/core_services/historians/Crate-Historian.rst, services/core/CrateHistorian/crate_historian/historian.py, services/core/CrateHistorian/tests/test_crate_historian.py, volttron/platform/dbutils/cratedriver.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1203)
=> Updates to crate and documentation

services/core/CrateHistorian/crate_historian/historian.py
Added Exception handling and recovery from loss of connection to server.
Added 30s wait period when there was a problem connecting to the server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1205)
=> Hardened crate historian.

services/core/CrateHistorian/crate_historian/historian.py, services/core/CrateHistorian/scripts/crate_config, services/core/CrateHistorian/scripts/drop_tables.py, services/core/CrateHistorian/scripts/mongo_to_crate.py, volttron/platform/dbutils/cratedriver.py
Updated crate_config to use test_import table rather than anything else.
Updated mongo_to_crate script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1207)
=> Modified table structure for crate so that numeric is default.

docs/source/specifications/external-rpc-enhancement.rst
Specification document that describes external RPC communication between remote platforms going forward.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1209)
=> Adding spec for external RPC communication

docs/source/core_services/historians/DataMover-Historian.rst, docs/source/core_services/historians/Forward-Historian.rst
#1185 
DataMover doc created and ForwardHistorian cleaned up a bit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1215)
=> #1185 Update historian documentation

services/core/CrateHistorian/README, services/core/CrateHistorian/config, services/core/CrateHistorian/crate_historian/historian.py, volttron/platform/dbutils/cratedriver.py
Fixed errors in the CrateHistorian and provided alternate Schema for testing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1224)
=> Cratehistorianraw

services/core/BACnetProxy/bacnet-proxy.agent, services/core/BACnetProxy/bacnet_proxy/agent.py
Added configuration option for default max_per_request, used during device discovery and point scanning
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1237)
=> Bacnetproxyconfig

services/core/CrateHistorian/crate_historian/historian.py
Resolves #1231 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1233)
=> fixed errors checked into develop on crate historian

docs/source/conf.py, services/core/CrateHistorian/crate_historian/historian.py, services/core/ForwardHistorian/forwarder/agent.py, services/core/MongodbHistorian/mongodb/historian.py, services/core/OpenEISHistorian/openeis/historian.py, services/core/SQLHistorian/sqlhistorian/historian.py, volttron/utils/docs.py
Fixed #1244
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1245)
=> Added fix to documenting concrete base classes.

docs/source/conf.py, setup.py, volttron/platform/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1256)
=> Releases/4.1 Update

scripts/install-agent.py, scripts/instance.py, services/core/CrateHistorian/crate_historian/historian.py, volttron/platform/__init__.py, volttron/platform/packaging.py
Fix install_agent script. Replaces pull request #1257
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1268)
=> Fixing parsing when there is not an agent with specified identity already

services/core/CrateHistorian/config, services/core/CrateHistorian/crate_historian/crate_utils.py, services/core/CrateHistorian/crate_historian/historian.py
Handle arrays as values as json data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1275)
=> Crate Arrays

volttron/platform/aip.py, volttron/platform/control.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1277)
=> Upgrade agent data

scripts/install-agent.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1280)
=> Fixed #1279 Comment # is now stripped out of the configuration file 

services/core/MongodbHistorian/mongodb/historian.py, volttron/platform/dbutils/mongoutils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1282)
=> querying multi topic queries in parallel and setting minPoolSize for mongo

docs/source/core_services/drivers/Driver-Configuration.rst, scripts/scalability-testing/virtual-drivers/modbus.py, services/core/MasterDriverAgent/master_driver/interfaces/modbus.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1293)
=> Added support for mixed endian MODBUS values.

volttron/platform/control.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1295)
=> Fixes install-agent and tests.

scripts/install-agent.py
The print statement causes issues with json parsing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1296)
=> removed extranous print statement.

scripts/install-agent.py
#1310 Fix script to require identity when forcing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1311)
=> #1310 Fix script to require identity when force is used

volttron/platform/packaging.py, volttrontesting/utils/platformwrapper.py
This cherry-picks the relevant code to handle #1307 into the releases/4.1 branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1318)
=> Un-Quited some errors

services/core/MasterDriverAgent/master_driver/interfaces/universal.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1325)
=> Updated to 4.0

volttron/platform/instance_setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1328)
=> Fixed #1327 During vcfg setup the password is now not echoed to stdout.

scripts/install-agent.py, volttron/platform/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1338)
=> Fixes #1337 try to handle / on the end of volttron_home

scripts/install-agent.py, volttron/platform/__init__.py
Added logging to #1338
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1339)
=> Added warnings about volttron_home

scripts/admin/volttron.service
This allows volttron to run as a service and be able to be stopped.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1341)
=> Added ExecStop to the systemd service.

examples/WebRPC/example.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1340)
=> Changed to a loopback IP address

docs/source/devguides/deployment/Deployment-Options.rst, docs/source/devguides/walkthroughs/Deployment-Walkthrough.rst, docs/source/devguides/walkthroughs/VC-Device-Configuration-Demo.rst, docs/source/index.rst, docs/source/install.rst, docs/source/planning-install.rst, docs/source/setup/VOLTTRON-Prerequisites.rst
minor edits and 1 new file for planning deployments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1351)
=> documentation updates

scripts/core/pack_install.sh, scripts/core/upgrade-agent.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1357)
=> Fixes #1356 by having a longer search string for awk

docs/source/volttron_applications/Simulated-Drivers.rst
@rob-calvert please verify that this was what you were meaning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1361)
=> Removed broken link

docs/source/volttron_applications/Simulated-Drivers.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1376)
=> Revised agent install instructions as suggested by Craig

services/core/ForwardHistorian/forwarder/agent.py
This will hopefully stop the merge conflicts with master and releases/4.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1386)
=> fixed version of fowarder that's in develop

docs/source/volttron_applications/index.rst, docs/source/volttron_applications/ven_agent.rst
Spec for a new VENAgent that participates in OpenADR demand response events.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1375)
=> OpenADR interface spec

docs/source/devguides/supporting/examples/Example-Agents.rst, docs/source/devguides/supporting/examples/ListenerAgent.rst, docs/source/devguides/supporting/examples/SchedulerExampleAgent.rst, docs/source/devguides/supporting/utilities/ProcessAgent.rst, examples/CSVHistorian/config, examples/CSVHistorian/csv_historian/historian.py, examples/CSVHistorian/launch_my_historian.sh, examples/CSVHistorian/setup.py
Example CSV historian agent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1363)
=> Add example CSV historian.

volttrontesting/utils/platformwrapper.py
Found bad test fixturing while refactoring web subsystem
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1389)
=> fixed regression in test fixturing for platformwrapper

docs/source/devguides/supporting/examples/CSVHistorianAgent.rst
Missing docs file from CSV historian.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1398)
=> Docs for CSV historian.

optional_requirements.json
#1401 Pin pytest version to avoid recursion error
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1402)
=> Pin pytest version to avoid error

services/core/ForwardHistorian/tests/test_forwardhistorian.py, volttron/platform/agent/base_historian.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1399)
=> Historian NaN fix

examples/ListenerAgent/listener/agent.py, services/core/MasterDriverAgent/master_driver/driver.py, services/core/MasterDriverAgent/master_driver/interfaces/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1405)
=> Better messges for debugging drivers.

docs/source/core_services/drivers/Driver-Configuration.rst, services/core/MasterDriverAgent/master_driver/agent.py, services/core/MasterDriverAgent/master_driver/driver.py, services/core/MasterDriverAgent/master_driver/tests/test_device_groups.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1404)
=> Device scrape grouping.

docs/source/volttron_applications/ven_agent.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1413)
=> Remove the OpenADR spec's references to a specific project

services/core/ActuatorAgent/actuator/agent.py, volttron/platform/vip/agent/core.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1416)
=> Fixes #1415

services/contrib/PrometheusScrapeAgent/prometheus_scrape/agent.py, volttron/platform/vip/agent/subsystems/web.py, volttron/platform/web.py, volttrontesting/utils/platformwrapper.py
This is an example implementation of these features added in a backwards compatible way with agents using the JSON-RPC interface.
This addresses #1378, #1379, #1382, #1367 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1388)
=> Web refactor to support custom headers, binary data, and status codes

volttrontesting/platform/test_platform_web.py, volttrontesting/utils/platformwrapper.py
Associate with #1388
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1417)
=> Added tests to the web refactor

services/core/WeatherAgent/weather/weatheragent.py
Fixes #831 
Based on https://github.com/VOLTTRON/volttron/pull/1047  addresses @craig8 formatting concerns.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1414)
=> Fixes #831

docs/source/core_services/service_agents/emailer/index.rst, docs/source/core_services/service_agents/failover/index.rst, docs/source/core_services/service_agents/index.rst, docs/source/core_services/service_agents/threshold/index.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1422)
=> Update and correct the service agents documentation.

services/core/CrateHistorian/crate_historian/historian.py
Addresses #1424
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1425)
=> fixed change in error class introduced by crate 2.x

scripts/extract_config_store.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1421)
=> Create extract_config_store.py script.

volttrontesting/platform/test_platform_web.py, volttrontesting/utils/platformwrapper.py
Makes #1379 OBE since I did pull requests out of order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1418)
=> Fixed merge issue for Prometheus agent

docs/source/core_services/config_store/Commandline-Interface.rst, volttron/platform/control.py, volttron/platform/store.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1431)
=> Add edit subcommand to vctl config. Fixes #1428

services/core/MongodbHistorian/mongodb/historian.py, services/core/SQLHistorian/sqlhistorian/historian.py, volttron/platform/agent/base_historian.py, volttron/platform/dbutils/mysqlfuncts.py, volttron/platform/dbutils/sqlitefuncts.py, volttrontesting/services/historian/test_historian.py
fix for task #1419 in sql and mongo historian. 
Added check for optional metadata in base historian to avoid array index error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1420)
=> fix for task #1419 in sql and mongo historian. 

docs/source/core_services/drivers/Driver-Configuration.rst, docs/source/core_services/drivers/index.rst, services/core/MasterDriverAgent/master_driver/interfaces/rainforestemu2.py, services/core/MasterDriverAgent/master_driver/test_emu2.json, services/core/MasterDriverAgent/master_driver/test_rainforestemu2.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1263)
=> add emu2 driver

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1450)
=> Modified Readme Added releases 4.1 status to image

services/core/EmailerAgent/emailer/agent.py
Fixed emailer agent to respect headers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1453)
=> Fixes #1452

volttron/platform/control.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1451)
=> Added better support for editing new configs. Fixes #1446

volttron/platform/__init__.py, volttron/platform/main.py, volttrontesting/platform/test_core_agent.py
This pushes roughly the same changes that were made during #1462  to the develop branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1463)
=> Better version accountability for develop branch

optional_requirements.json, scripts/get_versions.py, volttron/platform/__init__.py, volttron/platform/main.py, volttrontesting/platform/test_core_agent.py
Added the ability to get version info from the platform to the agent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1462)
=> Better version accountability for relases/4.1 branch

docs/source/devguides/supporting/Python-for-Matlab-Users.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1458)
=> add python for matlab users doc

volttron/platform/main.py, volttrontesting/utils/platformwrapper.py
To address issues #1322  #1448
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1472)
=> Fail when configurations are invalid, log logging config

examples/JupyterNotebooks/Observer.ipynb
. Don't shut down agents unexpectedly while initializing other data.
. Don't delete the historian database unexpectedly.
. Add a missing right-parenthesis in code that tests for file existence.
. Enhance historian SQL queries, allowing queries within a timeframe.
. Expand session-shutdown options at the end of the notebook.
. Move agent starting above the notebook's data analysis section.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1476)
=> Bug fixes and changes to the Observer JupyterNotebook.

volttron_data/agent_templates/setup.py_
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/VOLTTRON/volttron/pull/1488%23issuecomment-331332258%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/VOLTTRON/volttron/pull/1488%23issuecomment-331332258%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5CnReviewed%201%20of%201%20files%20at%20r1.%5CnReview%20status%3A%20all%20files%20reviewed%20at%20latest%20revision%2C%20all%20discussions%20resolved%2C%20some%20commit%20checks%20failed.%5Cn%5Cn---%5Cn%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/volttron/volttron/1488%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222017-09-22T02%3 …
=> Fixes #1487

examples/configurations/drivers/bacnet1.config
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1502?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1502'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volttron/volttron/1502)
=> Fix interval.

services/core/CrateHistorian/crate_historian/historian.py
This is for crate and http.connectionpool (nothing to do with volttron)
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1508?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1508'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> turn down logging

requirements.txt, services/core/BACnetProxy/bacnet_proxy/agent.py, setup.py
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1511?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1511'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Update bacpypes to 0.16.4.

services/core/MQTTHistorian/mqtt_historian/agent.py
#1512 Took config out of call to super init
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/VOLTTRON/volttron/pull/1515%23issuecomment-335641232%22%2C%20%22https%3A//github.com/VOLTTRON/volttron/pull/1515%23issuecomment-335641588%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/VOLTTRON/volttron/pull/1515%23issuecomment-335641232%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22What%20is%20the%20context%20for%20this%20change%3F%22%2C%20%22created_at%22%3A%20%222017-10-10T23%3A54%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/4081515%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/mikeroup%22%7D%7D%2C%20%7B%22body%2 …
=> #1512 MQTT historian fix

services/core/MQTTHistorian/mqtt_historian/agent.py, volttron/platform/__init__.py
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1518?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1518'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Updated version

services/core/MongodbTaggingService/config.mongodb, services/core/SQLiteTaggingService/config
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1521?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1521'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> removed unused parameter from example configuration of tagging service

examples/rotatinglog.py
#1530 Took out breaking changes in rotatingLog
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1531?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1531'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> #1530 Took out breaking changes

docs/source/core_services/multiplatform/Multiplatform-RPC.rst, docs/source/devguides/roadmap/4.1-5.0_Migration.rst, volttron/platform/vip/agent/subsystems/pubsub.py, volttron/platform/vip/pubsubservice.py
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/craig8%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/3979063%3Fv%3D4%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/VOLTTRON/volttron/pull/1534%23issuecomment-337391555%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222017-10-17T22%3A19%3A59Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/3979063%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/craig8%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/VOLTTRON/volttron/pull/1534 …
=> Multiplatform issue1532

.travis.yml, volttron/platform/vip/pubsubservice.py
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1536?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1536'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Multiplatform fix1532

volttron/platform/vip/agent/subsystems/pubsub.py
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/VOLTTRON/volttron/pull/1539%23issuecomment-337747475%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/VOLTTRON/volttron/pull/1539%23issuecomment-337747475%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Looks%20fine.%22%2C%20%22created_at%22%3A%20%222017-10-18T22%3A34%3A49Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/19616893%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/shwethanidd%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'><img src='http://www.codereviewhub.com/site/github-bar.png' …
=> Update pubsub.py error logging of unknown op

volttrontesting/subsystems/test_health_subsystem.py, volttrontesting/subsystems/test_pubsub_subsystem.py
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1551?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1551'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Updated tests

scripts/tagging_scripts/insert_id_and_ref_tags.py, services/core/SQLiteTaggingService/sqlite/tagging.py, volttron/platform/agent/base_tagging.py, volttron/platform/dbutils/sqlitefuncts.py, volttrontesting/services/tagging/test_tagging.py
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1543?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1543'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> task #1537 Fixed string comparison error in how existing table list is checked

scripts/pycharm-launch.py, services/core/CrateHistorian/cratedb/historian.py
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/VOLTTRON/volttron/pull/1554%23issuecomment-341238804%22%2C%20%22https%3A//github.com/VOLTTRON/volttron/pull/1554%23issuecomment-341246349%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/VOLTTRON/volttron/pull/1554%23issuecomment-341238804%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40kmonson%20%20Can%20you%20add%20the%20comment%20inline...that%20would%20help%20identify%20rather%20than%20having%20to%20list%20the%20line%20numbers%20here%21%22%2C%20%22created_at%22%3A%20%222017-11-01T20%3A52%3A28Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/3979063%3Fv%3D4%22%2C%20%22html_url%22 …
=> Crate configstore update

services/core/MongodbTaggingService/mongodb/tagging.py, services/core/SQLiteTaggingService/sqlite/tagging.py, volttron/platform/agent/base_tagging.py
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1555?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1555'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> fixed read the docs documentation for tagging service

volttron/platform/vip/agent/subsystems/pubsub.py, volttron/platform/vip/externalrpcservice.py, volttron/platform/vip/keydiscovery.py, volttron/platform/vip/pubsubservice.py, volttron/platform/vip/routingservice.py, volttrontesting/multiplatform/test_multiplatform_pubsub.py
1. Added error checking in all the files. 
2. Each pubsub message is handled within a greenlet to avoid deadlock. 
3. When an agent is stopped, a notification to other platforms have to sent with updated subscriptions
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1559?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1559'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Issue #1545 and #1553 

docs/source/devguides/walkthroughs/Multiplatform-Walkthrough.rst
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1560?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1560'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Modified the multiplatform setup documentation

services/core/CrateHistorian/cratedb/historian.py
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1564?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1564'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Fix crate connection issue

.travis.yml
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1572?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1572'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Fixed unintended crate install issue.

services/core/MasterDriverAgent/master_driver/agent.py
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1609?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1609'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Change Master Driver to use more reasonable publish defaults.

services/core/CrateHistorian/cratedb/historian.py, services/core/ForwardHistorian/forwarder/agent.py, services/core/SQLHistorian/sqlhistorian/historian.py, volttron/platform/agent/base_historian.py
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1611?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1611'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Fixes #1610 commented out debug messages that caused platform to hang.

services/core/MasterDriverAgent/tests/test_global_settings.py
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1612?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1612'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Fix master driver tests for new defaults.

examples/rotatinglog.py, services/core/CrateHistorian/cratedb/historian.py, services/core/ForwardHistorian/README.rst, services/core/ForwardHistorian/forwarder/agent.py, services/core/SQLHistorian/sqlhistorian/historian.py, volttron/platform/agent/base_historian.py
This update adds the removal of more logging from historians and adds a way to still get feedback on how your historians are doing.
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1614?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1614'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Logging update

volttron/platform/agent/base_historian.py, volttron/platform/vip/agent/core.py
Added signal handler to handle SIGINT signal. Handler sets stop event which enables a clean agent shutdown.
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/kmonson%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/2049915%3Fv%3D4%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/VOLTTRON/volttron/pull/1616%23issuecomment-367865182%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222018-02-23T00%3A04%3A28Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/2049915%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/kmonson%22%7D%7D%2C%20%7B%22body%22%3A%20% …
=> Onstop issue1615

volttron/platform/agent/base_historian.py
Fixes #1622
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1623?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1623'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Fixes #1622

bootstrap.py
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1641?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1641'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Fixes #1640 Handle if virtualenv is not synced with version from pypa

services/core/CrateHistorian/cratedb/historian.py, services/core/MongodbHistorian/config, services/core/MongodbHistorian/mongodb/historian.py, services/core/MongodbTaggingService/README.rst, services/core/MongodbTaggingService/config, services/core/MongodbTaggingService/mongodb/tagging.py, services/core/SQLHistorian/config.mysql, services/core/SQLiteTaggingService/README.rst, services/core/SQLiteTaggingService/config, services/core/SQLiteTaggingService/sqlite/tagging.py, volttron/platform/agent/base_historian.py, volttron/platform/agent/base_tagging.py, volttrontesting/services/tagging/test_tagging.py
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/VOLTTRON/volttron/pull/1586%23issuecomment-378399698%22%2C%20%22https%3A//github.com/VOLTTRON/volttron/pull/1586%23issuecomment-378403877%22%2C%20%22https%3A//github.com/VOLTTRON/volttron/pull/1586%23discussion_r180245431%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/VOLTTRON/volttron/pull/1586%23issuecomment-378399698%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22The%20tagging%20service%20configurations%20have%20the%20following%20line%3A%5Cr%5Cn%5Cr%5Cn%60%60%60%5Cr%5Cn%5C%22historian_vip_id%5C%22%3A%5C%22platform.historian%5C%22%5Cr%5Cn%60%60%60%5Cr%5Cn%5Cr%5CnAre%20tagging%20agents%20allowed%20to%20work%20as%20the%20platfor …
=> Tagging service fixes for task #1581 and task #1568. Updated test cases accordingly

docs/source/conf.py, optional_requirements.json
fix for task #1671.
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1673?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1673'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> fix for #task 1671

volttron/platform/agent/utils.py
Fixes #1680 
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1682?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1682'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Fix system logging

volttron/platform/control.py, volttron/platform/vip/agent/subsystems/health.py, volttron/platform/vip/agent/subsystems/heartbeat.py
Added health command function to Volttron Control to display a more verbose agent status.
Adjusted existing status command to display an agent's health status value.
Updated heartbeat to send agent's health status value (as opposed to the status object)
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/VOLTTRON/volttron/pull/1712%23discussion_r197588921%22%2C%20%22https%3A//github.com/VOLTTRON/volttron/pull/1712%23discussion_r197591703%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%20401b285c7d4612b6f152cf5b1b502cf08cede321%20volttron/platform/control.py%207%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/VOLTTRON/volttron/pull/1712%23discussion_r197588921%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22This%20import%20is%20never%20used.% …
=> Added health function to control

services/core/MarketServiceAgent/tests/test_market.py, services/core/MarketServiceAgent/tests/test_market_list.py
Fixes #1721 
Bug fix (non-breaking change which fixes an issue)
Test now run without market server requirements installed.
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
- [ x] Any dependent changes have been merged and published in …
=> Skip market service tests if requirements are not installed.

services/core/ActuatorAgent/actuator/agent.py, services/core/ActuatorAgent/tests/test_actuator_rpc.py
Add point kwargs to many actuator RPC methods.
Fixes #1719
New feature (non-breaking change which adds functionality)
Added appropriate tests to test_actuator_rpc.py.
- [ X] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the documentation
- [X ] My changes generate no new warnings
- [ X] I have added tests that prove my fix is effective or that my feature works
- [X ] New and existing unit tests pass locally with my changes
- [ X] Any dependent changes have been merged and published in downstream modules
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/VOLTTRON/volttron/ …
=> Added point kwarg to actuator rpc methods.

README.md, volttron/platform/vip/proxy_zmq_router.py
Documentation fixes
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1726?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1726'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Rabbitmq volttron auth

services/core/MarketServiceAgent/tests/test_market_list.py
Added on to #1722 for import issues.
Fixes #1721
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1731?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1731'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Fixes #1721 for real.

services/core/ForwardHistorian/forwarder/agent.py, volttron/platform/agent/base_historian.py, volttron_data/agent_templates/historian/agent.py_, volttron_data/agent_templates/historian/config
Add historian template for use with `vpkg init`
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1736?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1736'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Historian template

volttron/platform/agent/base_historian.py, volttrontesting/services/historian/test_base_historian.py
Improves the reporting of historian health and adds cache full reporting.
Updated unit tests.
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1738?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1738'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Cache reporting and health improvements

services/core/BACnetProxy/bacnet-proxy.agent, services/core/BACnetProxy/bacnet_proxy/agent.py
Increased the frequency of checks for new requests. This should help the performance of requests made serially. i.e. the configuration grabber.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/VOLTTRON/volttron/pull/1742%23discussion_r203569166%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%20b089e42a7419aab11f1db9405bf6d5a5ccae4cbe%20services/core/BACnetProxy/bacnet-proxy.agent%203%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/VOLTTRON/volttron/pull/1742%23discussion_r203569166%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22We%20should%20really%20just%20rename%20this%20to%20config%20to%20standardize%20it.%22%2C%20%22created_at%22%3A%20%222018-07-19T00%3A11%3A04Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.g …
=> Increased rate of checking for incoming BACnet requests.

volttron/platform/vip/agent/subsystems/rmq_pubsub.py, volttron/utils/rmq_mgmt.py
* Hardware:
* Toolchain:
* SDK:
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1748?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' …
=> federation and shovel updates

volttron/utils/rmq_mgmt.py
Federation is tested with or without SSL. Shovel is tested only without SSL. 
1749
RMQ management utility now works both with SSL and non SSL.
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1750?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1750'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Issue 1749: Fixes to federation and utility for non authentication mode

services/core/MasterDriverAgent/master_driver/interfaces/modbus_tk/client.py, services/core/MasterDriverAgent/master_driver/interfaces/modbus_tk/maps/battery_meter.csv, services/core/MasterDriverAgent/master_driver/interfaces/modbus_tk/maps/maps.yaml, services/core/MasterDriverAgent/master_driver/interfaces/modbus_tk/tests/test_battery_meter.py
Break into different request if total register size of the current request over the modbus limit
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1752?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1752'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Fix sending request limit

services/core/ForwardHistorian/forwarder/agent.py, services/core/MarketServiceAgent/tests/test_market.py, services/core/MarketServiceAgent/tests/test_market_list.py, services/core/MarketServiceAgent/tests/test_offer.py, services/core/MasterDriverAgent/master_driver/interfaces/__init__.py
Fix the signature to overridden base historian methods.
Fixes #1745
Run unit tests.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/VOLTTRON/volttron/commit/069f3d1d70ab380110ca538af418ca3382351d9a%23commitcomment-29926298%22%5D%2C%20%22comments%22%3A%20%7B%22Commit%20069f3d1d70ab380110ca538af418ca3382351d9a%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/VOLTTRON/volttron/commit/069f3d1d70ab380110ca538af418ca3382351d9a%23commitcomment-29926298%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22I%20hope%20that%20is%20all%20of%20%20these%21%22%2C%20%22created_at%22%3A%20%222018-08-01T19%3A30%3A06Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/ …
=> Fix the signature to overridden base historian methods. Fixes #1745

examples/FNCS/federate1.yml, examples/FNCS/fncs_example/agent.py
This pull request allows synchronizing one volttron agent and one fncs federate.
New feature (non-breaking change which adds functionality)
It is tested with a data published agent and FNCS develop branch.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/VOLTTRON/volttron/pull/1762%23discussion_r209405417%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%20aedc05b90ad2f43f6dcea4169d6e96409592f1d4%20examples/FNCS/federate1.yml%204%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/VOLTTRON/volttron/pull/1762%23discussion_r209405417%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22I%20think%20this%20comment%20is%20not%20in%20the%20right%20place...subscription_topic%20is%20below%20this..%22%2C%20%22created_at%22%3A%20%222018-08-10T23%3A26%3A13Z%22 …
=> Update FNCS example agent to include listening to volttron topic

examples/FNCS/federate1.yml
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1763?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1763'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> modify the annotation

README.md, bootstrap.py, volttron/platform/agent/utils.py, volttron/platform/certs.py, volttron/utils/rmq_mgmt.py, volttron/utils/rmq_setup.py, volttron/utils/rmq_setup_with_prompt.py
created copy of root-ca as trusted-cas.crt.
Updated readme. 
Made minor changes to rmq_setup to make a few parameters mandatory
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/shwethanidd%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/19616893%3Fv%3D4%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/VOLTTRON/volttron/pull/1770%23issuecomment-414379848%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222018-08-20T16%3A31%3A54Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/19616893%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/shwethanidd%22%7 …
=> More rmq setup and cert fixes

examples/SimpleWebAgent/simpleweb/agent.py, volttron/platform/web.py
Fixes the SimpleWebAgent and documents the process of responses.
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1777?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1777'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Fix web agent

README.md, volttron/platform/control.py
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/shwethanidd%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/19616893%3Fv%3D4%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/VOLTTRON/volttron/pull/1781%23issuecomment-415163272%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222018-08-22T20%3A10%3A26Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/19616893%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/shwethanidd%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/VOLTTRON/volttr …
=> fixed volttron-ctl rabbitmq add-user command

docs/source/devguides/walkthroughs/DrivenMatlabAgent-Walkthrough.rst, examples/ExampleMatlabApplication/matlab/example.m, examples/ExampleMatlabApplication/matlab/matlab_example.py
Updated documentation and fixed minor issues in example code
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/VOLTTRON/volttron/pull/1737%23discussion_r211034441%22%2C%20%22https%3A//github.com/VOLTTRON/volttron/pull/1737%23discussion_r211087707%22%2C%20%22https%3A//github.com/VOLTTRON/volttron/pull/1737%23issuecomment-414092390%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/VOLTTRON/volttron/pull/1737%23issuecomment-414092390%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Updated%20documentation%20based%20on%20review%20comments%5Cr%5Cn%5Cr%5CnFrom%3A%20Craig%20%5Bmailto%3Anotifications%40github.com%5D%5Cr%5CnSent%3A%20Friday%2C%20August%2017%2C%202018%202%3A29%20PM%5Cr%5CnTo% …
=> updated driven matalab agent documentation to add more details.

examples/StandAloneListener/settings.py, examples/StandAloneListener/standalonelistener.py
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1789?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1789'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> clean up of code and documenation of standalone code

docs/source/core_services/control/AgentStatus.rst
Added agent health command info to agent status docs page.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/VOLTTRON/volttron/pull/1791%23issuecomment-419234203%22%2C%20%22https%3A//github.com/VOLTTRON/volttron/pull/1791%23issuecomment-419255769%22%2C%20%22https%3A//github.com/VOLTTRON/volttron/pull/1791%23discussion_r215770560%22%2C%20%22https%3A//github.com/VOLTTRON/volttron/pull/1791%23discussion_r215792600%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/VOLTTRON/volttron/pull/1791%23issuecomment-419234203%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22please%20add%20the%20actual%20output%20from%20the%20vctl%20status%20command%20with%20at%20least%20a%20listener%20agent%20ins …
=> Added agent health command info to agent status docs page.

docs/source/devguides/walkthroughs/Deployment-Walkthrough.rst
Fixed a typo
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1803?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1803'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> errata: of the

docs/source/conf.py, volttron/platform/__init__.py
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/shwethanidd%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/19616893%3Fv%3D4%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/VOLTTRON/volttron/pull/1816%23issuecomment-426110235%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222018-10-02T00%3A47%3A43Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/19616893%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/shwethanidd%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/VOLTTRON/volttr …
=> bump version to volttron 6.0-rc1

scripts/rabbit_dependencies.sh
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1818?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1818'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Added script to install dependencies for rabbitmq debian distributions

examples/FNCS/README.md
Description/Fixes:
Step 2 in the FNCS installation was unclear: it says to "cd to the /python directory" and means the FNCS/python directory. 
When I opened the README file to edit, I found that step 2's actual text was "cd to the <FNCS_SRC/python> directory" but the <FNCS_SRC> part does not show up when the document gets displayed on GitHub. This may be because in markdown text inside of <> is interpreted as a link. I changed "<FNCS_SRC>/python" to "FNCS/python."
Type of change:
Documentation update
Testing:
None required; simple documentation update
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/VOLTTRON/volttron/pull/1817%23issuecomment-428268448%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https …
=> Clarify FNCS installation instructions (specify FNCS dir for setup.py)

volttron/platform/agent/base_historian.py, volttrontesting/services/historian/test_base_historian.py
Fixes #1844
Added new unit tests that covers failures in publish, setup, and tear down.
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1846?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1846'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
<a …
=> More robust base historian with tests.

services/core/SQLHistorian/sqlhistorian/historian.py
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1848?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1848'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> bump sqlhistorian version number

examples/EmailerAgent/emailer/agent.py
* Hardware:
* Toolchain:
* SDK:
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1859?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' …
=> fix emailer/agent.py

services/core/CrateHistorian/tests/test_crate_historian.py, volttron/platform/control.py, volttron/platform/main.py, volttrontesting/fixtures/volttron_platform_fixtures.py, volttrontesting/platform/control_test.py, volttrontesting/utils/platformwrapper.py
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/VOLTTRON/volttron/pull/1857%23issuecomment-445302484%22%2C%20%22https%3A//github.com/VOLTTRON/volttron/pull/1857%23discussion_r239884306%22%2C%20%22https%3A//github.com/VOLTTRON/volttron/pull/1857%23discussion_r241534125%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/VOLTTRON/volttron/pull/1857%23issuecomment-445302484%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22In%20a%20test%20can%20you%20build%20an%20installable%20fake%20agent%20that%20crashes.%22%2C%20%22created_at%22%3A%20%222018-12-07T17%3A18%3A59Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/3979063%3Fv%3D4%22%2C%20%22ht …
=> Fix for #1688 restart crashed agents

volttron/platform/aip.py, volttron/platform/control.py
Minor fix for #1784
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1880?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1880'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Minor change for issu #1784

examples/CSVHistorian/csv_historian/historian.py, examples/CSVHistorian/readme.rst
Added walkthrough for agent installation in readme.rst, and fixed csv path.
Fixes #1871 
Ran an instance of the agent on the Volttron platform.
<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1872?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1872'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> CSV historian fix and readme

services/core/MongodbHistorian/mongodb/historian.py, services/core/MongodbHistorian/tests/test_mongohistorian.py, services/core/MongodbHistorian/tests/test_prod_query_mongo.py, volttron/platform/agent/base_historian.py, volttrontesting/services/historian/test_base_historian.py, volttrontesting/utils/platformwrapper.py
Minor fixes in historian and mongo historian.  
Updated test cases to fix datetime format error gevent timing issues on slower virtual machine
=> Bug fix for failing mongo and base historian test case

services/core/DataMover/README.rst, services/core/DataMover/config, services/core/DataMover/datamover/agent.py, services/core/MongodbHistorian/mongodb/historian.py, services/core/MongodbHistorian/tests/test_mongohistorian.py, services/core/MongodbHistorian/tests/test_prod_query_mongo.py, services/ops/TopicWatcher/config, services/ops/TopicWatcher/topic_watcher/agent.py, volttron/platform/agent/base_historian.py, volttron/platform/scheduling.py, volttron/platform/vip/agent/subsystems/health.py, volttron/platform/vip/agent/utils.py, volttrontesting/services/historian/test_base_historian.py
* Hardware:
* Toolchain:
* SDK:
=> Merge dev again

ci-integration/run-tests.sh, optional_requirements.json, volttron/platform/agent/base_tagging.py, volttrontesting/services/tagging/test_tagging.py
Fixes #1907 
Reran all existing test cases. Fixed one test case to match the correct expected result.
=> Tagging fix

services/core/CrateHistorian/cratedb/historian.py, services/ops/TopicWatcher/topic_watcher/agent.py
Fixes a couple issues that happened in our deployment
=> Fixes in deployment

services/core/MongodbHistorian/config, services/core/MongodbHistorian/mongodb/historian.py
bug fix for #1917. Added small gevent.sleep in loop that queries data from data table and inserts data into hourly and daily tables
=> task #1917. Fixed issue. 

optional_requirements.json, services/core/CrateHistorian/cratedb/historian.py, services/core/MongodbHistorian/config, services/core/MongodbHistorian/mongodb/historian.py, services/ops/TopicWatcher/topic_watcher/agent.py, volttron/platform/agent/base_tagging.py, volttrontesting/services/tagging/test_tagging.py
Merging develop into rabbitmq-volttron to make sure all develop is in rabbitmq
=> Develop to rabbit

services/core/ForwardHistorian/forwarder/agent.py, volttron/platform/agent/utils.py, volttron/platform/instance_setup.py, volttron/platform/main.py, volttrontesting/fixtures/rmq_test_setup.py
=> Fixes ZMQ Forwarder and instance-name issues

volttron/platform/main.py, volttron/platform/web/master_web_service.py
This pull request adds the ability for VOLTTRON to serve web content via configured ssl (https) connections.
Fixes #1454
=> Add ssl zmq web

volttron/platform/main.py
Fixed issue with $ not being found in None argument
=> Fixed None issue with the ssl files.

volttron/utils/rmq_setup.py, volttrontesting/fixtures/rmq_test_setup.py, volttrontesting/fixtures/volttron_platform_fixtures.py, volttrontesting/platform/test_platform_rmq.py, volttrontesting/utils/platformwrapper.py
=> RabbitMQ-VOLTTRON: Fixes for issues 1921 and 1928

scripts/install-agent.py
Fixes #1936
* Hardware:
* Toolchain:
* SDK:
=> Fixes container loop issue

volttrontesting/fixtures/rmq_test_setup.py, volttrontesting/fixtures/volttron_platform_fixtures.py, volttrontesting/utils/platformwrapper.py
=> More fixes for #1921

services/core/ForwardHistorian/forwarder/agent.py, volttron/platform/vip/agent/core.py, volttron/platform/vip/agent/subsystems/auth.py
zmq and rmq through the auth subsystem.
=> Adds functionality to connect through a central mechanism to both

volttron/platform/certs.py, volttron/platform/vip/agent/subsystems/auth.py, volttron/platform/web/csr_endpoints.py, volttron/platform/web/discovery.py, volttron/platform/web/master_web_service.py, volttron/utils/rmq_mgmt.py
Discovery info response contains the AMQP/S address. That is used to build connection to remote RMQ based platform.
1941
=> To fix issue# 1941. AMQP/S address added into discovery info response.

volttron/platform/agent/base_historian.py, volttrontesting/services/historian/test_base_historian.py, volttrontesting/utils/platformwrapper.py
base historian test case fixes
platformwrapper improvements - now build_agent is called only once at instance startup. Rest of the method do not create dynamic agents.
=> base_historian tests and platformwrapper improvements

README.md, docs/source/setup/RabbitMQ/Backward_Compatibility.rst, docs/source/setup/RabbitMQ/Monitoring_RMQ.rst, docs/source/setup/RabbitMQ/RMQ_Multiplatform_Setup.rst, docs/source/setup/RabbitMQ/Troubleshooting_RMQ.rst, docs/source/setup/RabbitMQ/index.rst
Initial documentation update. Left only the basic rmq install details in README.md and moved many of the detailed topics as .rst files under doc/source.
=> Rabbitmq documentation update

examples/ConfigActuation/tests/test_config_actuation.py, services/core/ActuatorAgent/tests/test_actuator_rpc.py, services/core/ForwardHistorian/tests/test_forwardhistorian.py, services/core/MasterDriverAgent/master_driver/interfaces/chargepoint/tests/test_chargepoint_driver.py, services/core/MasterDriverAgent/tests/test_device_groups.py, services/core/MasterDriverAgent/tests/test_eagle.py, services/core/MasterDriverAgent/tests/test_global_override.py, services/core/MasterDriverAgent/tests/test_global_settings.py, services/core/MasterDriverAgent/tests/test_rest_driver.py, services/core/SQLHistorian/tests/test_sqlitehistorian.py, services/core/WeatherDotGov/tests/test_weather_dot_gov.py, services/ops/AgentWatcher/tests/test_agent_watcher.py, services/ops/TopicWatcher/tests/test_topic_watcher.py, volttrontesting/fixtures/rmq_test_setup.py, volttrontesting/fixtures/vc_fixtures.py, volttrontesting/fixtures/volttron_platform_fixtures.py, volttrontesting/platform/test_platform_rmq.py, volttrontesting/platform/test_platform_web.py, volttrontesting/services/historian/test_historian.py, volttrontesting/services/tagging/test_tagging.py, volttrontesting/testutils/test_platformwrapper.py, volttrontesting/testutils/test_single_instance.py, volttrontesting/utils/platformwrapper.py
Removed duplicate fixtures. 
Fixed rmq conf cleanup issues
=> task #1740. Removed duplicate fixtures.

examples/GridAPPS-DAgent/IDENTITY, examples/GridAPPS-DAgent/config, examples/GridAPPS-DAgent/gridappsdvolttron/agent.py, examples/GridAPPS-DAgent/requirements.txt, examples/GridAPPS-DAgent/setup.py
GRIDAPPSD/GOSS-GridAPPS-D#843
@afisher1 please look at this agent
=> Added a quick example for gridappsd

volttrontesting/services/tagging/test_tagging.py
All tagging tests except mongo historian tests pass
=> task #1740. Updates to tagging test cases

.gitmodules
This fix is for updating documentation on readthedocs https://github.com/rtfd/readthedocs.org/issues/5543
=> Fixes the submodule that was added some time ago

volttron/platform/vip/rmq_connection.py, volttron/platform/vip/zmq_connection.py
To fix accidental commit.
Fixes # 1962
=> Fix Issue#1962. Undo accidental commit

ci-integration/run-test-docker.sh
Replaced container ids with container names.
Fixes #1956
=> Replaced container id with container name

services/ops/TopicWatcher/tests/test_topic_watcher.py, services/ops/TopicWatcher/topic_watcher/agent.py, volttron/platform/vip/agent/core.py
=> Fix for #1963

services/core/MongodbHistorian/conftest.py, volttron/platform/agent/base_aggregate_historian.py, volttron/platform/agent/base_historian.py, volttron/platform/dbutils/basedb.py, volttron/platform/dbutils/mysqlfuncts.py, volttrontesting/services/aggregate_historian/test_aggregate_historian.py, volttrontesting/services/historian/test_dbdriver.py, volttrontesting/services/historian/test_historian.py
1. Fixed aggregate historian tests to run on both zmq and RMQ.
2. Fixed mysql cursor concurrent access error
3. Commented out Mongo test cases for now (need gevent loop error fix)
4. Fixed logic in base aggregate historian to handle configuration change once a aggregation collection is scheduled
=> Updated Aggregate historian and tests

services/core/MasterDriverAgent/tests/test_modbus_driver.py
Updated fixture behavior for modbus server to run once per set of tests (once for each message bus)
=> Changed fixture for test_modbus_driver to be used once per test run

services/core/MasterDriverAgent/master_driver/interfaces/modbus_tk/tests/test_battery_meter.py, services/core/MasterDriverAgent/master_driver/interfaces/modbus_tk/tests/test_modbus_tk_driver.py, services/core/MasterDriverAgent/master_driver/interfaces/modbus_tk/tests/test_scrape_all.py, services/core/MasterDriverAgent/tests/test_modbus_driver.py
Added dynamic IP and port for modbus_tk tests, formatted code
Tested with ci-integration docker script
=> Rabbitmq volttron test

.travis.yml
This should be added after #1989 as it included the same base code.  
This pull request makes travis use it as it's method for running the  builds
=> Travis docker running

ci-integration/run-test-docker.sh
* Hardware:
* Toolchain:
* SDK:
=> Testing updates

services/core/WeatherDotGov/agent/WeatherDotGovAgent.py
Bundled certs with grequest request to remote api, prevents ssl cert verification from failing during tests on rmq.
tested against local/run-test-docker
=> Bundled cert with grequests request in weather.gov agent

volttron/platform/vip/agent/core.py, volttrontesting/platform/test_rmq_platform_shutdown.py, volttrontesting/subsystems/test_health_subsystem.py, volttrontesting/utils/platformwrapper.py
More fixes to pytests.
Fixes #1740
=> More fixes to issue# 1740

ci-integration/run-test-docker.sh, volttrontesting/testutils/test_platformwrapper.py, volttrontesting/utils/platformwrapper.py
This is a follow on commit from #2026.  It fixes the issue with the control tests that were discovered. Following on #1740
=> Fix control tests

docs/source/core_services/messagebus_refactor/RabbitMQ-SSL-Auth.rst, docs/source/setup/RabbitMQ/Backward_Compatibility.rst, docs/source/setup/RabbitMQ/Multi-Platform-RMQ-CSR-Walkthrough.rst, docs/source/setup/RabbitMQ/RMQ_Multiplatform_Setup.rst, docs/source/setup/RabbitMQ/remote_agent.rst, docs/source/setup/index.rst
More documentation update for 6.0 release.
=> 6.0 doc update

volttron/platform/certs.py, volttron/platform/control.py
Allow creating of pkcs12 files.
=> Add cert builder

volttron/platform/instance_setup.py
=> Fixed #2083

docs/source/devguides/supporting/examples/MatLabAgent.rst, examples/StandAloneMatLab/testScript.py
New changes made to documentation to reflect feedback.
value in testScript.py changed to float to correct error.
=> Updated documentation

docs/source/core_services/control/AgentAutostart.rst
note that explicitly setting the priority requires using the --priority flag
* Hardware:
* Toolchain:
* SDK:
=> Documentation: fix priority syntax

volttron/platform/main.py, volttron/platform/vip/rmq_router.py, volttrontesting/platform/test_core_agent.py, volttrontesting/services/historian/test_base_historian.py, volttrontesting/services/historian/test_multiplatform.py
fix for getting correct platform-version in RMQ
fix for volttrontesting/services/historian/test_multiplatform.py
clean up in test_base_historian
=> more fixes

requirements.py, volttron/platform/instance_setup.py
removes vc/vcp from vcfg for a couple of days
=> remove vc vcp temporarily

docs/source/core_services/control/AuthenticationCommands.rst, docs/source/core_services/control/index.rst, docs/source/core_services/historians/DataMover-Historian.rst, docs/source/core_services/historians/index.rst, docs/source/core_services/multiplatform/index.rst, docs/source/core_services/openadr/VtnServerConfig.rst, docs/source/core_services/openadr/VtnServerGuide.rst, docs/source/core_services/restricted/Agent-Signing.rst, docs/source/core_services/security/index.rst, docs/source/core_services/service_agents/central_management/Webservice-API.rst, docs/source/devguides/agent_development/Agent-Development.rst, docs/source/devguides/agent_development/Developing-Market-Agents.rst, docs/source/devguides/supporting/utilities/ProcessAgent.rst, docs/source/index.rst, docs/source/overview/DefinitionOfTerms.rst, docs/source/setup/Third-Party-Agents.rst, docs/source/unused/deprecated/Logging.rst, docs/source/volttron_applications/Simulated-Drivers.rst
Minor spelling corrections in documentation
N/A Nonfunctional change
N/A Nonfunctional change
=> minor spelling corrections in documentation

docs/source/devguides/walkthroughs/Driver-Creation-Walkthrough.rst, examples/CSVDriver/CsvDriverAgent/CsvDriverAgent/agent.py, examples/CSVDriver/CsvDriverAgent/config, examples/CSVDriver/CsvDriverAgent/setup.py, examples/CSVDriver/csv_driver.config, examples/CSVDriver/csv_registers.csv, examples/CSVDriver/csvdriver.py
Adds documentation describing and performing walkthrough for driver development, and includes example driver, driver configurations, and test agent.
This PR is primarily for documentation purposes. Included driver and example agent have been tested manually, but exist for demonstration purposes only.
=> Volttron Driver Tutorial and Examples

services/core/ForwardHistorian/forwarder/agent.py
This resolves #2152
* Hardware:
* Toolchain:
* SDK:
=> Pass JSON status to Status.from_json()

.editorconfig
Fixed issue that had a bar at 40 characters instead of only at 120
=> Removed line at 40 characters in!

services/core/BACnetProxy/bacnet_proxy/agent.py, volttron/platform/agent/base_historian.py, volttron/platform/agent/base_weather.py, volttron/platform/async_.py, volttron/platform/vip/agent/core.py
If agent code uses the module volttron.platform.async they should upgrade to use volttron.platform.async_ instead.
Fixes #2144
=> Fixes to work with python3.7+

volttron/platform/instance_setup.py, volttron/platform/vip/router.py, volttron/utils/frame_serialization.py
Adds extra elif cases in deserialization of frames; needed for running on python 3.7.
- [x ] Bug fix (non-breaking change which fixes an issue) 
Installed and ran basic vcfg on debian 10 (on x86 and metal) with RMQ, platform configures and runs. Complete test suite not run.
=> commit changes from craig's patch

volttron/platform/vip/router.py
removed print statement from router._send()
=> Fix for issue #2203

services/core/MasterDriverAgent/tests/test_dnp3_driver.py, volttron/platform/main.py
Updates DNP3 driver tests, tests now passing for RMQ and ZMQ.
This pull request fixes existing DNP3 tests in Volttron 7.x which are previously not passing in develop.
=> Fix DNP3 driver tests

scripts/bacnet/grab_bacnet_config.py, scripts/bacnet/proxy_bacnet_scan.py, scripts/bacnet/proxy_grab_bacnet_config.py, services/core/BACnetProxy/bacnet-proxy.agent, services/core/BACnetProxy/bacnet_proxy/agent.py, services/core/MasterDriverAgent/master_driver/interfaces/bacnet.py, volttron/platform/agent/bacnet_proxy_reader.py
Fixes an issue with the way BACPypes was being used causing some values to be unreadable,
fixes file write for configuration scripts, includes several pep8 improvements.
Collected configurations from and gathered points for BACnet devices at PNNL. In the future integration tests with virtual BACnet devices are desireable.
*Currently there are no unit or integration tests for these scripts/agents, with the exception of the BACnet COV tests which do not interface with a device (these tests are passing).
=> BACnet Proxy Clean-Up and Fixes for Configuration Scripts

README.md, docs/source/community_resources/index.rst
Update readthedocs to refer to new zoom meeting and how to be invited. Cleanup for README document.
Fixes #1355 
Documentation update only.
This change is only for documentation.
=> Issue 1355: Office hours docs update

volttron/platform/instance_setup.py
=> Vcfg bugfixes for 2256 and 2257

README.md
=> docs: Fix spelling of listener agent.

volttron/platform/auth.py, volttron/platform/main.py, volttron/platform/vip/agent/subsystems/rpc.py, volttron/platform/vip/externalrpcservice.py, volttron/platform/vip/routingservice.py, volttrontesting/multiplatform/test_multiplatform_pubsub.py
This PR fixes the python 2 to 3 issues found in external rpc communication in multi-platform setup.
=> Adding fix for python2 to 3 for external rpc in multiplatform setup

volttron/platform/instance_setup.py
Fixed instance_setup after accidental push of older version
=> Reverted instance_setup.py to correct version

volttron/platform/vip/agent/subsystems/auth.py
Moved imports related to web inside "https" section of connect_remote_platform()
=> moved web imports into https section

docs/source/community_resources/contributing.rst, docs/source/community_resources/documentation.rst
=> docs: Basic spelling and grammar fixes

volttron/platform/web/admin_endpoints.py, volttron/platform/web/master_web_service.py, volttron/platform/web/templates/login.html
=> Modified web to allow for http-based admin and vc.

examples/DataPublisher/README.rst, examples/DataPublisher/datapublisher/agent.py
Reformat README
Fixed playback issues found with extra metadata.
Added support for specifying the separator in the headers.
Documented conversion changes.
Feature: Allows user to specify the delimiter to represent topic in header of csv file.  By default it is set to '/' but now it is able to be any other character.  This is used to separate "all" messages based upon different prefixes in the column headers.
Fixes: If a field is missing or not a float the system would fail and one would not know it until volttron stopped.  This case is now handled that if the value in a row is not specified or can't be converted to a float then the value and column is not included in the results set.  A message is logged of the fact as well.
Fixes #2276 #2278 …
=> Datapublisher fixes

volttron/platform/agent/base_historian.py, volttrontesting/services/historian/test_base_historian.py
Fix for issue #2286 
Also fixed test case failing in test_base_historian due to timing issue. 
Tested using base historian test cases. 
Re-ran sqlite historian test cases
=> Fixed base historian cache purge issue - #2286

services/ops/EmailerAgent/emailer/agent.py
Fixes issue#2292. replaced agent_uuid with agent_identity
=> Fixes issue#2292. replaced agent_uuid with agent_identity

services/core/BACnetProxy/requirements.txt
Fixed syntax in requirements.txt for BACnet proxy
BACnet proxy testing ongoing, confirmed that dependencies install with these change by using `install_agent` script
=> fix syntax in requirements file

volttron/platform/auth.py
Removes a decode statement in auth.py that caused the platform to be unable to start.
Fixes #2305
A subset of repository's unit tests were run, live data collection currently being performed.
=> Fix decode on string in auth.py causing platform to be unable to start

volttron/platform/auth.py
=> fixing #2305

README.md
Doc only change. This was not obvious to me immediately.
=> docs(README.md): Add note about deactivating environment

CONTRIBUTING.md, README.md
This project does not have a CONTRIBUTING.md document. On GitHub, a CONTRIBUTING guide is the convention for passing instructions to possible contributors, and is used to automatically suggest that users look it over before submitting PRs (see [here](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors)). I have always found them useful. 
Right now, there is an extensive Contributing Guide in the ReadTheDocs website, but it almost exclusively covers how to use GitHub and Git (which may not be relevant to many users), and takes multiple clicks to see. By having a Guide in the top level, we can increase the possibility of it being viewed, and it can be closer to the code, in general. 
The PR templates suggest that there are both tests …
=> docs: Add a Contributing Guide and slightly edit README

volttrontesting/fixtures/docker_wrapper.py, volttrontesting/testutils/test_fixtures.py
Provides a context manager for creating a docker image to run while a test is running.  Provides example for usage in the test_fixtures example.
Tested via unit tests both with and without the docker api installed.
=> Added prototype docker wrapper and fixture for docker

README.md, bootstrap.py, examples/StandAloneFileWatcher/settings.py, examples/StandAloneFileWatcher/standalonefilewatchpublisher.py, requirements.py, scripts/rabbit_dependencies.sh, volttron/platform/auth.py, volttron/platform/vip/agent/subsystems/peerlist.py, volttron/utils/__init__.py, volttrontesting/fixtures/docker_wrapper.py, volttrontesting/testutils/test_fixtures.py
Added a Stand Alone version of the File Watch Publisher Agent.
=> Stand Alone File Watch Publisher Agent

services/core/MasterDriverAgent/master_driver/interfaces/modbus_tk/helpers.py, services/core/MasterDriverAgent/master_driver/interfaces/modbus_tk/maps/__init__.py
- [ x] New feature (non-breaking change which adds functionality)
- [ x] Running in production against PM800 power meters on Volttron 5.1x
=> Modbus tk pm800

services/core/VolttronCentralPlatform/vcplatform/agent.py
Added missing encoding to fix the install-agent functionality missing from VC.
=> Fixed issue with encoding for install-agent functionality in VC

volttrontesting/platform/dbutils/test_mysqlfuncts.py
The wait_for_connection method will return None if connection cannot be established within the allotted time, thus letting a test to proceed without having established a connection. Rather, the test should throw a RuntimeError when a connection hasn't been established. Also, this changes cleans up some typos and formatting.
I reran the test on both PyCharm and the command line.
=> Return RuntimeError when connection times out

README.md, docs/source/core_services/control/AgentStatus.rst, docs/source/devguides/agent_development/Agent-Development.rst, docs/source/devguides/agent_development/TestAgent.rst, docs/source/devguides/supporting/examples/FakeDriver.rst, docs/source/devguides/supporting/examples/ListenerAgent.rst, docs/source/docutils.conf, examples/GridAPPS-DAgent/config, volttron_data/agent_templates/common/config
The current example does not match the heartbeat given out by the listener agent. While the time stamps are obviously not worth updating, the message format in general has changed significantly. I have added my current printouts.
Doc only fix.
=> docs: Update listener heartbeat example

services/core/MasterDriverAgent/master_driver/agent.py, services/core/MasterDriverAgent/tests/test_global_override.py
Changes global override pattern comparison in master driver to be case-sensitive, includes case sensitivity tests
Fixes # (2394)
Master Driver tests passing, additional test included for pattern case comparison
* Hardware:
* Toolchain:
* SDK:
=> Issue 2394: Global override pattern is case sensitive

volttron/platform/keystore.py
Added retry logic to generate keys again if keys startswith '-'
Fixes #2371
=> Fixes issue#2371.

volttron/platform/instance_setup.py
=> Modified vcfg to re-include necessary rmq setup

volttron/utils/frame_serialization.py
Fixed issue with frame serialization for python 3.8. 
Fixes #2437
=> Serialize issue

volttron/platform/control.py
Adds the rpc subcommand set to vctl. Contains list and code.
The list subcommand displays all of the agents that have a peer
connection to the instance and which methods are available from
each of these agents.
If a single agent is specified, it will list all methods available for that agent.
If the -v option is selected, all agent subsystem rpc methods will be displayed
for each selected agent as well.
If an agent is specified, and then a method (or methods) are specified,
all parameters associated with the method(s) will be output.
By adding the '-v' option to this stage, the doc-string description
of the method will be displayed along with the method and parameters if available.
The code subcommand functions similarly to list, except that it will output the code
to be used in an agent …
=> Moved vctl rpc code changes to separate branch for pr

docs/source/volttron-topics/change-log/index.rst, docs/source/volttron-topics/change-log/upgrading-versions.rst
Documents changes required to port version 6.x deployments to version 7.  Includes documents describing changes to VOLTTRON_HOME.
Tested using Sphinx Build.
=> Added documentation for upgrading platforms from version 6.x to 7

pytest.ini, services/core/MasterDriverAgent/tests/test_driver.py, services/core/MasterDriverAgent/tests/test_master_driver.py
Adding unit tests for the two main agents, master driver and driver, to support goal of reducing build times and improve developing experience.
Fixes #2350 
I ran the unit tests using Pytest and on the PyCharm IDE. 
**Test Configuration**
- VM: Virtualbox
- OS: Ubuntu
- Python: 3.6.9
- TestFramework: Pytest
Pytest commands and output
```
$ pytest test_driver.py test_master_driver.py
#output
===================== 37 passed in 0.55s =========================
```
=> Add unit tests for master driver and driver

requirements.py
Fixes issue #2477 
Built the documentation after this patch.
=> Fixes #2477 by adding a comma

scripts/scalability-testing/multilistener/README.md, scripts/scalability-testing/multilistener/process_file.py, scripts/scalability-testing/multilistener/raw_output_multi_listener_agent.py
Adding the scripts and some notes related to small-system benchmark testing.
Includes notes and scripts used for benchmarking testing
All testing run on an RPi 4
=> adding notes and scripts from Oct. 2020 benchmarking work

docs/source/developing-volttron/contributing/community.rst, docs/source/developing-volttron/contributing/contributing-code.rst
Brief addition directing people to ECA
Lack of ECA
Documentation
Local creation of documentation
=> Added Eclipse Info

volttron/platform/instance_setup.py
Fixes #2505. Added try-except block to exit cleanly
Fixes #2505
=> Fixes #2505. Added try-except block to exit cleanly

docs/source/deploying-volttron/platform-configuration.rst
Updates platform configuration docs: adds missing entries for VOLTTRON_HOME, clarifies and expands config file section, fixes a heading level issue
Tested using local Sphinx build
=> Platform configuration docs

services/core/MarketServiceAgent/market_service/agent.py, services/core/MarketServiceAgent/market_service/market.py, services/core/MarketServiceAgent/market_service/market_list.py, services/core/MarketServiceAgent/market_service/market_participant.py, services/core/MarketServiceAgent/market_service/market_state.py, services/core/MarketServiceAgent/market_service/offer_manager.py, services/core/MarketServiceAgent/market_service/reservation_manager.py, volttron/platform/agent/base_market_agent/__init__.py, volttron/platform/agent/base_market_agent/point.py, volttron/platform/agent/base_market_agent/poly_line.py, volttron/platform/agent/base_market_agent/poly_line_factory.py, volttron/platform/agent/base_market_agent/registration_manager.py, volttron/platform/agent/base_market_agent/rpc_proxy.py
- [ X] New feature (non-breaking change which adds functionality)
* Hardware:
* Toolchain:
* SDK:
- [ X] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
=> Merge volttron-GS base_market_agent with volttron base_market_agent.

docs/source/index.rst
Changed introductory statement
=> changed intro text

scripts/bacnet/proxy_bacnet_scan.py
Same problem as in https://github.com/VOLTTRON/volttron/pull/2469 - script needs to be updated to work with python 3. Also made sure to close the CSV file, otherwise python makes no guarantees that the writes will make it to the filesystem. 
Ran locally as described in discussion here: https://github.com/VOLTTRON/volttron/issues/2519
=> Fix bacnet proxy scan

.github/workflows/build-dependency-cache.yml, .github/workflows/pytest-testutils.yml, .travis.yml
Added github actions as a better/more integrated runner for pytest.  Allows longer build time for individual jobs.
=> Started github actions to run when a push is done to the main repository

docs/source/agent-framework/core-service-agents/openadr-ven/ven-agent.rst, docs/source/agent-framework/core-service-agents/volttron-central/volttron-central-agent.rst, docs/source/agent-framework/core-service-agents/volttron-central/volttron-central-overview.rst, docs/source/agent-framework/core-service-agents/volttron-central/volttron-central-platform.rst, docs/source/agent-framework/operations-agents/failover/failover.rst, docs/source/conf.py, docs/source/deploying-volttron/multi-platform/datamover-historian-deployment.rst, docs/source/deploying-volttron/multi-platform/index.rst, docs/source/deploying-volttron/multi-platform/multi-platform-multi-bus.rst, docs/source/deploying-volttron/multi-platform/multi-platform-rabbitmq-deployment.rst, docs/source/deploying-volttron/multi-platform/multi-platform-router.rst, docs/source/deploying-volttron/multi-platform/volttron-central-deployment.rst, docs/source/deploying-volttron/platform-configuration.rst, docs/source/developing-volttron/developing-agents/agent-development.rst, docs/source/developing-volttron/developing-agents/example-agents/data-publisher.rst, docs/source/developing-volttron/developing-agents/example-agents/simple-web-agent-walk-through.rst, docs/source/driver-framework/bacnet/bacnet-driver.rst, docs/source/index.rst, docs/source/introduction/definitions.rst, docs/source/introduction/platform-install.rst, docs/source/platform-features/config-store/agent-configuration-store.rst, docs/source/platform-features/config-store/configuration-store.rst, docs/source/platform-features/control/platform-commands.rst, docs/source/platform-features/message-bus/multi-platform/multi-platform-communication.rst, docs/source/platform-features/message-bus/vip/agent-vip-id.rst, docs/source/platform-features/message-bus/vip/vip-json-rpc.rst, docs/source/platform-features/message-bus/vip/vip-known-identities.rst, docs/source/platform-features/security/running-agent-as-user.rst, docs/source/volttron-topics/change-log/scalability/scalability.rst, docs/source/volttron-topics/change-log/upgrading-versions.rst
Added agent resiliency docs, fixed apidocs missing in toctree, fixed refs breaking sphinx build in definitions
Tested with local Sphinx build
=> Agent Resiliency Docs, API Docs, Definition Labels

examples/ListenerAgent/listener/agent.py, volttron/platform/certs.py, volttron/platform/web/csr_endpoints.py
Fix for  jira_306 and jira_307
=> fixes for csr create and delete certificate issues jira_306 jira_307

requirements.py
=> Pin Pyjwt version

docs/source/driver-framework/ecobee/ecobee-web-driver.rst
Adds documentation around the set point feature for the Ecobee driver and updates the format of existing csv tables.
Docs tested using local Sphinx build.
=> Ecobee set point docs

requirements.py
Fix for Jira issue 340
I ran the following commands to observe volttron and ensure that it started. 
```
$  python3 bootstrap.py
$ source env/bin/activate
$  volttron -vv -l volttron.log&
$ vctl status
```
=> Pin idna to versions less than 3.x

docs/source/developing-volttron/developing-agents/agent-development.rst, volttron_data/agent_templates/common/agent.py_, volttron_data/agent_templates/common/config, volttron_data/agent_templates/historian/agent.py_, volttron_data/agent_templates/historian/config
Updates deprecated StandardError to Exception, fixes pep8 issues, and cleans up pydocs for agent development templates used by vpkg init.
Testing using the agent development instructions from readthedocs.
=> Update agent dev templates for Python3

volttron/platform/agent/utils.py, volttron/platform/config.py, volttron/platform/instance_setup.py, volttron/utils/rmq_setup.py
fixes for "vcfg rabbitmq shovel" command
Fixes for jira tickets 362, 363, 365
=> vcfg rabbitmq shovel fixes

docs/source/introduction/platform-install.rst
Minor documentation update to include notes from experience updating campus
Doc update
No code changes
N/A
=> notes on sqlite3 requirement and certificate lifecycle

volttron/platform/control.py, volttron/platform/instance_setup.py, volttrontesting/fixtures/rmq_test_setup.py, volttrontesting/platform/test_instance_setup.py, volttrontesting/utils/platformwrapper.py
Added prompt for instance name to vcfg in all cases.
Updated tests to match.
=> Vcfg add instance name

volttron/platform/control.py
Allows subprocessor functions to call sys.exit(0) and have that short circuit and exit properly.
=> Fix vctl to handle systemexit from sub commands properly

docs/source/agent-framework/historian-agents/forwarder/forward-historian.rst, docs/source/deploying-volttron/multi-platform/multi-platform-rabbitmq-deployment.rst, docs/source/deploying-volttron/multi-platform/multi-platform-router.rst, docs/source/driver-framework/platform-driver/platform-driver.rst, examples/JupyterNotebooks/BacnetCollector.ipynb, examples/JupyterNotebooks/ChargePointCollector.ipynb, examples/JupyterNotebooks/IEEE2030_5Collector.ipynb, scripts/scalability-testing/README.md, scripts/scalability-testing/multilistener/README.md, scripts/scalability-testing/test_settings.py, services/core/ActuatorAgent/actuator/agent.py, services/core/PlatformDriverAgent/platform_driver/interfaces/IEEE2030_5.py
Changed references to master driver to use platform driver
=> renamed references to master driver as platform driver

docs/source/agent-framework/historian-agents/historian-framework.rst
fix for jira_375
included historian tutorial video in historian framework read the docs page.
=> embed historian video in rtd

docs/source/conf.py, volttron/platform/__init__.py
=> Bumped version to 8.0

volttron/platform/auth.py, volttron/platform/certs.py, volttrontesting/platform/auth_tests/test_auth_control.py, volttrontesting/platform/auth_tests/test_auth_file.py
Updated Auth Tests based on changes made to pending cert/credential handling
=> vctl auth tests update

volttron/platform/vip/agent/subsystems/rmq_pubsub.py, volttron/platform/vip/rmq_router.py, volttron/utils/rmq_setup.py, volttrontesting/fixtures/rmq_test_setup.py, volttrontesting/utils/platformwrapper.py
Fix for jira_386
Fixed rmq test environment setup for pytests
Fixed router ping
=> Fixed rmq test environment setup for pytests

services/ops/AgentWatcher/tests/test_agent_watcher.py
Agent watcher default config test assumed watchlist was empty.  This PR updates the tests to validate the contents of the config and to handle both cases where the config's watchlist is empty as well as populated.
Agent integration tests
=> Fixed agent watcher default config test

services/ops/AgentWatcher/tests/test_agent_watcher.py, volttrontesting/services/tagging/test_tagging.py, volttrontesting/testutils/test_platformwrapper.py, volttrontesting/utils/platformwrapper.py
temporary workaround for jira_392. splitting
=> temporary workaround for jira_392. splitting installing and starting agent

services/core/Ambient/tests/test_ambient_agent.py, services/core/Darksky/tests/test_darksky.py, services/core/WeatherDotGov/tests/test_weatherdotgov.py
Fixes non-deterministic behavior in weather service agent polling tests.
Weather service agent unit/integration tests.
=> Fix polling tests in weather service agents

services/core/ForwardHistorian/tests/test_multi_messagebus_forwarder.py, volttrontesting/utils/platformwrapper.py
Fixes test_multi_messagebus_forwarder_reconnection(). The platform was not getting cleanup at the end of the test.
=> Pytest fix

README.md
Cleans up broken links and grammar in README.md
Clicked new links
=> Updated README for releases 8.x

docs/source/agent-framework/historian-agents/mongodb/mongo-historian.rst
Updates MongoDb agent doc in RTD to be up to date with latest requirements
=> Updated mongo docs with requirement updates

examples/GridAPPS-D/test_gridappsd.json, integrations/gridappsd_integration.py
Added username and password into config and passed as parameters into GridAPPSD connection object
Fixes #2645
=> Fixes #2645

volttron/platform/web/platform_web_service.py, volttrontesting/platform/web/test_web_agent.py, volttrontesting/utils/web_utils.py
Added check that the resolved path passed from the environment (from client) is within the registered path.
Fixes # voltdev-344
Added unit test for testing the functionality that will fix this issue.
=> http directory traversal using register_path_route function

README.md
Fixes VOLTTRON Slack channel sign-up link in README.md
=> README Slack Sign-up

volttron/platform/web/platform_web_service.py, volttron/platform/web/templates/login.html
Hotfix to properly set Bearer to contain the access token properly.
Added minor check for expired signature to jsonrpc_verify_and_dispatch
=> Hotfix to properly set Bearer to contain the access token.

services/core/PlatformDriverAgent/tests/test_platform_driver_forward_cov.py
What is the change?
* Create absolute path to configuration files used for test setup
* Use check_call instead of Popen to make vctl-specific commands in test
* Rename test_driver_bacnet_cov.py to more accurate name: test_platform_driver_forward_cov.py; the test does not use BACnet Drivers or any BACnet-related code; the PlatformDriver is the component being tested
* Use yield/cleanup pattern instead of addfinalizer to simplify teardown code
Why is it needed?
* Integration tests in test_driver_bacnet_cov.py fails because the path to the configuration files are not absolute and therefore the volttron platform instance cannot load the configuration files onto the platform driver.
* check_call throws a more helpful error message, i.e. CalledProcessError, if a vctl command fails. Currently, …
=> Fix bacnet integration test; rename test to more accurate name

volttron/platform/dbutils/postgresqlfuncts.py
Fixes #2683 
* Hardware:
* Toolchain:
* SDK:
=> Add index only when index isn't already there

.github/workflows/pytest-auth.yml, .github/workflows/pytest-testutils.yml, scripts/rabbit_dependencies.sh, volttron/platform/certs.py
Updated github action to
1. Include erlang install for ubuntu 16.04 and 18.04
2. bootstrap with --rabbitmq for ubuntu 16.04 and 18.04
Updated erlang install script to support ubuntu version numbers in addition to names
=> Added erlang install and rabbitmq bootstrap to github action tests

volttron/platform/certs.py
=> removed log statements

services/core/VolttronCentral/volttroncentral/agent.py
Modified VC to properly use access token for get_user_claims.
=> Fix VC to handle new auth changes

volttron/platform/store.py
fix for rpc timeout error when doing config store operations on agents that are not running. 
jira-484
=> fix for rpc timeout error when doing config store operations on agents that are not running

docs/source/developing-volttron/community.rst
Added link to volttron publications
=> Added link to volttron publications

.gitattributes
Fixes line endings for all repos.
=> Added .gitattributes file for line endings

.github/workflows/pytest-auth.yml, .github/workflows/pytest-dbutils.yml, .github/workflows/pytest-testutils.yml, .github/workflows/pytest-vctl.yml, .github/workflows/pytest-web.yml
Changes the workflows to only build when a pull request is made, not when a push to a branch is done.
=> Modified actions to only build on pr.

volttron/platform/control.py, volttron/platform/instance_setup.py
This issue fixes the installation of larger agents (platform driver) timing out during installation. 
=> Transfer more data per request during install to prevent timeout

.github/workflows/pytest-dbutils-backup_db.yml, .github/workflows/pytest-dbutils-influxdbfuncts.yml, .github/workflows/pytest-dbutils-sqlitefuncts.yml, .github/workflows/pytest-dbutils-timescaldbfuncts.yml, volttrontesting/platform/dbutils/test_influxdbutils.py, volttrontesting/platform/dbutils/test_mongoutils.py, volttrontesting/platform/dbutils/test_mysqlfuncts.py, volttrontesting/platform/dbutils/test_postgresql_timescaledb.py, volttrontesting/platform/dbutils/test_postgresqlfuncts.py
Added splitting up of different database types into different workflows.
=> Develop to Releases 8.1

services/core/PlatformDriverAgent/platform_driver/interfaces/modbus_tk/requirements.txt, services/core/PlatformDriverAgent/requirements.txt
Update and/or pin versions in requirements.txt for the following agents or drivers:
* PlatformDriver
* ModbusTK Driver
Installed agents or drivers using the updated requirements.txt and verified that they installed successfully.
=> Update and/or pin versions in requirements.txt for agents and drivers

volttron/platform/instance_setup.py
=> fix for issue #2778. fixed identity used for platform.historian install from vcfg

bootstrap.py, requirements.py
=> fix for issue#2796 (jira #533)

scripts/rabbit_dependencies.sh
Updating rabbitmq dependency script since the rabbitmq server repos have changed
=> Updating rabbitmq dependency script

requirements.py
Fixing requirements.py related to wheels entry in option requirements
=> Fixing requirements.py related to wheels entry in option requirements

README.md, docs/source/volttron-topics/VOLTTRON-releases/upgrading-versions.rst, services/core/SQLHistorian/tests/test_sqlitehistorian_unit.py, volttron/platform/agent/base_historian.py, volttron/platform/aip.py, volttron/platform/upgrade/move_sqlite_files.py, volttron/platform/upgrade/update_auth_file.py, volttron/platform/upgrade/upgrade_volttron.py, volttrontesting/platform/dbutils/test_backup_database.py, volttrontesting/services/historian/test_base_historian.py, volttrontesting/testutils/test_base_historian_unit.py
Fixes for issue #2802 and #2803 
Updated 
How was this tested:
1. Ran unit and integration test that refer to backup.sqlite
2. Ran historian integration tests for - sqlite, mysql, postgres, cratedb
3. Manually tested upgrade sqlite historian from VOLTTRON 7.x to VOLTTRON 8.1.1
=> Historian upgrade 8.x

README.md, docs/source/volttron-topics/VOLTTRON-releases/upgrading-versions.rst
Documentation updates for VOLTTRON 8.x upgrade
=> README update for 8.x upgrade

docs/source/developing-volttron/developing-drivers/driver-development.rst
Signed-off-by: Elijah J. Passmore <elijah@elijahjpassmore.com>
Fix incorrect indentation in Python code.
I ran `make html`.
=> Fix Python indentation in Driver Development

docs/source/agent-framework/agents-overview.rst, docs/source/agent-framework/core-service-agents/index.rst, docs/source/agent-framework/historian-agents/crate/crate-historian.rst, docs/source/agent-framework/historian-agents/data-mover/data-mover-historian.rst, docs/source/agent-framework/historian-agents/forwarder/forward-historian.rst, docs/source/agent-framework/historian-agents/historian-framework.rst, docs/source/agent-framework/historian-agents/influxdb/influxdb-historian.rst, docs/source/agent-framework/historian-agents/mongodb/mongo-historian.rst, docs/source/agent-framework/historian-agents/mqtt/mqtt-historian.rst, docs/source/agent-framework/historian-agents/openeis/openeis-historian.rst, docs/source/agent-framework/historian-agents/sql-historian/sql-historian.rst, docs/source/agent-framework/operations-agents/index.rst
Signed-off-by: Elijah J. Passmore <elijah@elijahjpassmore.com>
I added directory paths to all of the relevant agent sections. I personally found the location of each agent confusing when I was first reading the framework sections, so I think this could help people save some time.
Feel free to edit the contribution as while I followed the style outlined, there may still be room for improvement in the general presentation.
I ran `make html`.
=> Add directory paths to agent documentation

volttron/platform/dbutils/mysqlfuncts.py, volttron/platform/dbutils/postgresqlfuncts.py, volttron/platform/dbutils/redshiftfuncts.py, volttron/platform/dbutils/sqlitefuncts.py, volttrontesting/platform/dbutils/test_mysqlfuncts.py, volttrontesting/platform/dbutils/test_postgresql_timescaledb.py, volttrontesting/platform/dbutils/test_postgresqlfuncts.py, volttrontesting/platform/dbutils/test_sqlitefuncts.py
#2821 
Manually tested it for sqlite, mysql and postgresql historians
=> fix for issue #2821

volttron/platform/control.py
Removed the unused upgrade_agent function, and it's parser command. This method is not relevant to the new handling of install agent.
Fixed typo in list_connections function.
- [ x] Bug fix (non-breaking change which fixes an issue)
Ran pytests for control tests.
=> Removed Unused Methods in Control

volttron/platform/dbutils/mysqlfuncts.py, volttron/platform/dbutils/postgresqlfuncts.py, volttron/platform/dbutils/redshiftfuncts.py, volttron/platform/dbutils/sqlitefuncts.py, volttrontesting/platform/dbutils/test_mysqlfuncts.py, volttrontesting/platform/dbutils/test_postgresql_timescaledb.py, volttrontesting/platform/dbutils/test_postgresqlfuncts.py, volttrontesting/platform/dbutils/test_sqlitefuncts.py
=> Hotfix - sqlhistorian

volttron/platform/packaging.py
Fixes #2843 
Ran 'vctl install' script on test agent (e.g. OpenADR agent) and verified that it only used the Volttron-built wheel and that the agent had a 'metadata.json' file. Also, ensured that the agent can successfully start.
=> Cleanup dist directory when creating wheel from agent source

volttron/platform/instance_setup.py
Install web dependencies if not found while vcfg command for rabbitmq
Fixes Issue #2816
=> Install web dependencies if not found

.github/workflows/pytest-auth.yml, .github/workflows/pytest-dbutils-backup_db.yml, .github/workflows/pytest-dbutils-influxdbfuncts.yml, .github/workflows/pytest-dbutils-mysqlfuncts.yml, .github/workflows/pytest-dbutils-postgresqlfuncts.yml, .github/workflows/pytest-dbutils-sqlitefuncts.yml, .github/workflows/pytest-dbutils-timescaldbfuncts.yml, .github/workflows/pytest-testutils.yml, .github/workflows/pytest-vctl.yml, .github/workflows/pytest-web.yml, volttrontesting/platform/dbutils/test_mysqlfuncts.py, volttrontesting/platform/dbutils/test_postgresql_timescaledb.py, volttrontesting/platform/dbutils/test_postgresqlfuncts.py
Update all Github Actions to use Python 3.7, 3.8, and 3.9. Remove Python 3.6
=> Change GithubWorkflows to use minimal job matrix

services/core/Ambient/tests/test_ambient_agent.py
=> Set pytestmark for Ambient tests

services/core/Ambient/tests/test_ambient_agent.py, volttron/platform/agent/utils.py
Fix test and test infrastructure so that Ambient and Volttron Central properly run and pass. This PR cherry picks the following merge commits from the 'develop' branch:
[d322baacf812d8a431125b8ca1eb529d4ba73b5f](https://github.com/VOLTTRON/volttron/pull/2850)
[bac5447df148a8013950dd6877d77df84b5eba7c](https://github.com/VOLTTRON/volttron/pull/2840)
=> Fix Ambient tests and load_config

volttron/platform/web/vui_endpoints.py
Updated Response to authenticated vui endpoints to return 401 Not Authorized for all exceptions.
#2863 
Tested with invalid token from Postman.
=> Updates to web API

.github/workflows/run-downstream-tests.yml
* Addresses #2867 
* Creates dispatch workflow to trigger workflows in other repos such as volttron-openadr and volttron-listener-agent
=> Add dispatch workflow for downstream testing

volttron/utils/prompt.py
=> Cleanup volttron.utils.prompt

volttron/platform/agent/utils.py, volttron/platform/instance_setup.py, volttrontesting/platform/test_instance_setup.py
VCFG can be used when VOLTTRON is running during special use cases.
Tested manually. Created new test to verify that vcfg works with a currently running instance of volttron.
=> VCFG with VOLTTRON On

debugging_utils/peerlist-watcher.py
Easier to ask for forgiveness than permission. 
This is more Pythonic.
=> Cleanup get_volttron_home()

README.md, volttrontesting/platform/control_tests/test_vctl_commands.py
Updated environment for tests.
=> update env for test

examples/CSVDriver/README.rst
Tested that the CSVDriver agent and driver are running successfully by viewing the volttron.log file. Added details to the README. 
This is a part of Jira ticket [VOLTDEV-143](https://jira.pnnl.gov/jira/browse/VOLTDEV-143), but does not close this ticket.
Tested that the CSVDriver agent and driver are running successfully by viewing the messages logged that indicate the driver is functioning.
=> Test example CSVDriver agent

docs/source/index.rst, docs/source/tutorials/quick-start.rst
Please include a summary of the change and which issue is fixed
- Added `quick-start.rst`
- Modified `index.rst` to reflect the change in content structure.
Please also include relevant motivation and context.
- Provide an easy-to-follow tutorial for first-time users.
List any dependencies that are required for this change.
- None
Fixes #2889 (Documentation update) 
1. `index.rst` rendering, (readthedocs entry): https://volttron-km-readthedocs.readthedocs.io/en/latest/
2. `quick-start.rst` rendering, (core content):
https://volttron-km-readthedocs.readthedocs.io/en/latest/devel …
=> #2889 added quick-start tutorial to documentation

examples/MatLabAgent_v2/README.md
Added a README with a link to the Volttron docs page regarding the MatLabAgentV2. 
This is a part of the Jira ticket [VOLTDEV-143](https://jira.pnnl.gov/jira/browse/VOLTDEV-143) but does not close the ticket. 
Tested that I was able to run the agent successfully.
=> Added README for MatLabAgentV2 example agent

services/contrib/MessageDebuggerAgent/messagedebugger/agent.py, volttron/platform/dbutils/postgresqlfuncts.py, volttron/platform/dbutils/redshiftfuncts.py
See https://github.com/VOLTTRON/volttron/pull/2907
=> Explicitly use class name in super() call

volttrontesting/utils/test_agent_configuration.py, volttrontesting/utils/test_config
Added tests for new and existing load_config functionality. Added tests using a valid config file and also invalid config paths. 
New tests
New tests pass
=> created tests for load_config

examples/configurations/drivers/fake.config
In original file
Hot fix
Not applicable
Not applicable
=> get rid of the repetivie driver_type: fakedriver

CONTRIBUTING.md
This current link doesn't exist.
=> Update contributing docs link

examples/DataPuller/README.md, examples/DataPuller/config
Tested that I was able to run the DataPuller example agent. Added a README.
This change is a documentation update
Tested that I was able to run the agent.
=> Data puller example agent

volttrontesting/platform/auth_tests/test_auth.py, volttrontesting/platform/auth_tests/test_auth_control.py
Added fixture at module level to skip tests for non auth case
Pytest fix
=> Added fixture to skip for non auth case

volttron/platform/instance_setup.py, volttrontesting/fixtures/volttron_platform_fixtures.py, volttrontesting/utils/platformwrapper.py
Protecting rabbitmq file imports within guard condition 
Fixes: #2997
=> 8.2 authfixes

services/core/OpenADRVenAgent/openadr_ven/agent.py
Fixes parsing error logic for Events. This PR is created to mirror changes from the modular OpenADRVenAgent; see https://github.com/VOLTTRON/volttron-openadr-ven/pull/36
=> Add logic to parse unsupported objects

docs/source/agent-framework/core-service-agents/openadr-ven/ven-agent.rst
Updates OpenADR docs at https://volttron.readthedocs.io/en/releases-8.2/agent-framework/core-service-agents/openadr-ven/ven-agent.html to align with the new OpenADRVenAgent.
Fixes #3020 
I ran `make docs` script and checked the generated documentation locally.
=> Update openadr docs

docs/source/volttron-topics/VOLTTRON-releases/release-history.rst
Updated release history. fixes #3031
=> Updated release history. fixes #3031

volttron/platform/main.py
- Remove unused imports
- Add missing import
- Remove import *
=> Improve imports in main.py

volttrontesting/platform/test_instance_setup.py
Fix for issue #3119 and minor assert statement fix in test_instance_setup.py
=> Fix for issue 3119

volttron/platform/control/control_utils.py
=> Brought back working filter

.github/workflows/code_analysis.yml, .github/workflows/pytest-auth.yml, .github/workflows/pytest-dbutils-backup_db.yml, .github/workflows/pytest-dbutils-influxdbfuncts.yml, .github/workflows/pytest-dbutils-mysqlfuncts.yml, .github/workflows/pytest-dbutils-postgresqlfuncts.yml, .github/workflows/pytest-dbutils-sqlitefuncts.yml, .github/workflows/pytest-dbutils-timescaldbfuncts.yml, .github/workflows/pytest-miscellaneous-tests.yml, .github/workflows/pytest-testutils.yml, .github/workflows/pytest-vctl.yml, .github/workflows/pytest-web.yml, deprecated/Ambient/ambient/agent.py, deprecated/Ambient/tests/test_ambient_agent.py, examples/CSVDriver/csvdriver.py, examples/HELICS/helics_federate.py, pytest.ini, services/core/PlatformDriverAgent/platform_driver/interfaces/ecobee.py, services/core/PlatformDriverAgent/platform_driver/interfaces/home_assistant.py, services/core/PlatformDriverAgent/requirements.txt, services/core/PlatformDriverAgent/tests/test_home_assistant.py, services/ops/ThresholdDetectionAgent/tests/test_threshold_agent.py, update_copyright.py, volttron/platform/vip/__init__.py, volttron/platform/vip/zmq_connection.py, volttrontesting/fixtures/volttron_platform_fixtures.py, volttrontesting/platform/dbutils/test_mysqlfuncts.py, volttrontesting/platform/test_basehistorian.py, volttrontesting/utils/build_agent.py, volttrontesting/utils/platformwrapper.py
Culmination of some of the things to get 9.x ready for release. 
Getting Ready For Release
=> Culmination of 9.x items.

services/core/PlatformDriverAgent/platform_driver/interfaces/modbus_tk/tests/test_battery_meter.py, services/core/PlatformDriverAgent/platform_driver/interfaces/modbus_tk/tests/test_driver_demo_board.py, services/core/PlatformDriverAgent/tests/test_bacnet.py
Updated some driver tests to make them run more reliably.
=> New minor driver test updates

volttron/platform/aip.py
Adds a cache so that agent name resolution doesn't hit the filesystem after initial resolution
- Verified in test platforms, pushed to production in our systems
=> Added a cache for agent names since platform start

requirements.py
Fix for: https://github.com/gevent/gevent/issues/1989
=> Update gevent to 23.9.1

requirements.py
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] This change requires a documentation update
This change was used to build an updated docker image with the base being debian bookworm (natet/volttron
* Hardware:
* Toolchain:
* SDK:
- [ x  ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] My changes generate no new warnings
=> Changed library requirements for docker container updates
